### ISSUE TITLE
Ford error when attempting to change the names of types in %chat

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#1898] opened 2019-10-31 00:37 UTC
@belisarius222 Could you take a look at this? Joe has no idea what is causing it.

I started by booting a fakezod from master. I then copied in the updated files from my [branch](https://github.com/urbit/urbit/tree/la-chat-type-renames). I'm attempting to test "OTA" conditions where I simply rename the types within the chat app with no changes to the content.

Ford fails on committing the files, and I'm quite confused by it.

<img width="612" alt="Screen Shot 2019-10-30 at 5 33 55 PM" src="https://user-images.githubusercontent.com/1377557/67909197-99979080-fb3b-11e9-9067-51cb415c1f90.png">

**Comment by matildepark** [comment] 2019-10-31 00:39
Also ran into this today working on dojo stuff. All I did was move a line with a sur import. It worked on creating a new zod, but all other commits had no effect on the first ship after that error.

**Comment by belisarius222** [comment] 2019-10-31 00:40
Looking

**Comment by belisarius222** [comment] 2019-10-31 01:01
Looks like a Ford bug.  This line failed:
https://github.com/urbit/urbit/blob/master/pkg/arvo/sys/vane/ford.hoon#L5559

That means the build to parse a scaffold from lib/chat-json wasn't in the state during a rebuild of the app, but it should have been.  Not sure why it wasn't.  Part of the stack trace is missing here because +reduce has a `!.` around it.

I'll make a PR to make the `!.` narrower so we can get better forensics on this.  In the meantime, don't delete the piers that had this error.  We'll want to load the new Ford code onto them to try to reproduce.

**Comment by belisarius222** [comment] 2019-10-31 01:15
Hmm, I'm not sure this is the best way to debug it.  @loganallenc can you send me your pier?  I want to mess with it.

**Comment by loganallenc** [comment] 2019-10-31 03:05
Thanks for the fast response. I’ll get you a pier tomorrow.

**Comment by joemfb** [comment] 2019-11-06 00:24
#1915 includes not a fix, but a workaround. I think a real fix will require propagating %drip errors back to %ford.

**Comment by matildepark** [comment] 2020-06-30 23:05
I think Fusion was meant to specifically address stuff like this (or at least so that we don't need to goad anymore)? @belisarius222

**Comment by belisarius222** [comment] 2020-07-01 00:22
Yeah, I'd be inclined to close this unless someone has experienced something like it after ford-fusion.

—
~rovnys-ricfer
https://urbit.org

**Closed** 2020-09-25 03:24 UTC
Labels: bug, ford
