### ISSUE TITLE
Revise behavior of roll/reel

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit#3430] opened 2020-09-03 21:04 UTC
roll and reel don't seem to have been designed as general-purpose accumulators.  That is, they implicitly include an operation against 0/~/%.y which introduces behavior unexpected by the user.

For instance, add works properly:

```hoon
> (roll `(list @)`~[1 2 3 4] |=([a=@ b=@] ~&([a b] (add a b))))
10
```

but mul fails catastrophically:

```hoon
> (roll `(list @)`~[1 2 3 4] |=([a=@ b=@] ~&([a b] (mul a b))))
0
```

Other surprises include logical accumulation operations:

```hoon
> (roll `(list ?)`[%.n %.n ~] |=([a=? b=?] |(a b)))
%.y
```

Either roll and reel need to be refactored (if this behavior isn't relied on somewhere in the kernel) or the documentation needs to be updated and sensible alternatives need to be introduced for other accumulator patterns.

**Comment by sigilante** [comment] 2020-09-03 21:09
Probably the right (or at least simplest) solution is to revise the documentation and recommend the use of `;:` for other cases.

**Comment by ohAitch** [comment] 2020-09-03 21:10
They do not implicitly include an operation against 0, they explicitly include an operation against `+>+.$` - note that just ``(roll `(list @)`~[1 2 3 4] mul)`` works fine, because its default sample is set to `1` for this purpose. Last time I looked at the doc it included this, but possibly should be made more clear.

If you do need an explicit accumulator for an existing gate you don't want to wrap, I think there was also a variant that took an accumulator as an argument? Obviously you do need *some* accumulator to be able to `roll` an empty list.

**Comment by belisarius222** [comment] 2020-09-03 21:10
There have been other reports of this issue before, which is essentially a documentation and ergonomics issue.

This works as I expected:
```
> (roll `(list @)`~[1 2 3 4] mul)
24
```
The difference is that `+mul`'s default sample has 1s, whereas the function you wrote that calls `+mul` defaults the sample to zeros because that's the normal default for `@`.  It's a subtle issue, and there should probably be versions of `+roll` and `+reel` that take an explicit initial value instead of relying on the default sample of the function that gets folded.

`;:` is more like a compile-time fold; it only works for an argument list whose length is known at parse-time, by specifying all the arguments in the source, so it doesn't work for dynamic lists.

**Comment by Fang-** [comment] 2020-09-03 21:53
> If you do need an explicit accumulator for an existing gate you don't want to wrap, I think there was also a variant that took an accumulator as an argument?

You might be thinking of `+spin` aka "stateful `+turn`"? It does both accumulation _and_ transformation though.

```hoon
> (spin (gulf 1 4) 1 |=([a=@ b=@] a^(mul a b)))
[p=~[1 2 3 4] q=24]
```

**Comment by Fang-** [comment] 2020-09-04 09:21
(Also cc @syzygyzer @baudtack for updating docs to highlight/explain this. As per discussion in chat somewhere, "an opportunity to explain `$_` and |:`".)

**Comment by drbeefsupreme** [comment] 2021-06-16 15:34
The docs have been fixed to show how to work around this. This doesn't seem like unintended behavior, so maybe we can close this issue as well?

**Comment by joemfb** [comment] 2021-07-13 19:31
Closing as documented

**Closed by joemfb** 2021-07-13 19:31 UTC
