### ISSUE TITLE
Opening a links page again can cause the urbit to go into a long processing process

### ISSUE THREAD

**Issue by somlus-savlev** [urbit/urbit#2839] opened 2020-05-03 20:10 UTC
There is an issue whereby when the links pages are opened up from the group page, it can bog down the ship in a long process full of errors until it finally kicks out and loads the links page. During that time the ship is very slow and minimally responsive, as are the chats that the ship is hosting.

Stated differently: Starting from the groups page and with a group's contents (links, chats, etc) open, if you click on a link set within the group (and it should theoretically open up that link group quickly in the window), what happens is that the page takes forever to open, and in the dojo you can see that it's sort of trying to process something for each ship that is not going through, all of the time it's doing that it is not able to quickly process other requests, including all of the postings for the chats that the ship in question is hosting.

Here is a link to what the dojo is seeing during this time, as was seen on the hiddev-dannut ship which hosts the Hooniverse, when that ship was trying to open one of the links pages it created for the hooniverse (starting from the groups screen within the hooniverse group):

https://pastebin.com/qjXgC4Va

The actual error process was very long - this was a small component of it.

**Comment by Fang-** [comment] 2020-05-03 21:15
I suspect there's something like "subscribe wire not unique" near the end of that error?

The performance component of this got (at least partially) addressed in #2728, and got sent OTA about a week ago. Can you confirm you're running latest?  
(ie check `.^(@uv %cz /=base=)`, ensure it ends in `ontk0`, then check if `.^(@uv %cz /=base=/app/link)` and `.^(@uv %cz /=home=/app/link)` match, and if they do maybe run `:goad %force` for good measure.)

CLI printing, when done in large batches, has historically been "not fast" as well. And link-listen-hook is likely to have a lot of subscriptions open. I'm not sure why we print all subscriptions instead of the one with the matching wire... But this _could_ add to the slowness.

You shouldn't be getting that error in the first place though, it shouldn't ever try to subscribe to the same source twice. That's a bug.

> During that time the ship is very slow and minimally responsive, as are the chats that the ship is hosting.

Urbit does only one thing at a time, so this is expected behavior.

**Comment by somlus-savlev** [comment] 2020-05-07 12:54
I figured it out and the fix is simple.  Here is a sample URL for a links group within a group I run as copied from the "open" hyperlink in the list of contents within that group:

[MY BASE URL]/~link**/join**/links-to-flashcards--review-sheets--other-tools-904

Because it is a "join" command, it goes into a long series of errors because my own ship has already joined that group's links page.  if you simply remove the /join in the generated URLs once a ship is already a member of that group, or add code to recognize that a join is not needed, it will be fixed.

If you enter this instead into the address bar:

[MY BASE URL]/~link/links-to-flashcards--review-sheets--other-tools-904

It loads right away, no problem, without this 5-8 minutes of error after error as it tries to work through re-joining.

**Comment by somlus-savlev** [comment] 2020-05-07 12:55
In short, there should be no "join" when you've already joined. the URL is wrong for people who have gone through the joining process already.

**Comment by matildepark** [comment] 2020-05-07 14:09
I disagree that the URL is wrong — the Join view in Links just has a bug in it. We use new and join views as conditional redirects in every app.

— 
~haddef-sigwen
https://urbit.org

**Comment by loganallenc** [comment] 2020-05-07 15:06
My bet is that it is sending a join command before the page data has loaded instead of checking to see if the resource exists. @Fang- ?

**Comment by Fang-** [comment] 2020-05-07 15:20
The frontend sends join commands unconditionally, but the backend should no-op where appropriate. ([see `+handle-listen-action`](https://github.com/urbit/urbit/blob/69b6495d3d4c8cd3d81c5842a2cc90bf8059d63c/pkg/arvo/app/link-listen-hook.hoon#L220)) The fact that it doesn't is probably a bug.

I can't reproduce this on my ship, so, @somlus-savlev does this happen _every time_ you click that join button? I'd be curious to see your output from running `:link-listen-hook +dbug [%state '(~(has by reasoning) [~some-group-member /the-link-collection-123])']`, where the ship is any member of the group the collection is in, and `/the-link-collection` is the name/path you see in the URL bar. If you've already joined it (or tried), this should say `%.y`.

Did you do anything special with this group or collection, like leaving and rejoining? Might help us get a repro on this.

**Comment by ixv** [comment] 2020-05-08 00:17
I also have this issue, it happened in the course of removing and readding myself to the tlon group while chasing another bug. Are you interested in taking a look at my ship?

**Comment by Fang-** [comment] 2020-07-01 14:43
Hmm, still haven't been able to repro this, and just manually walking through the code doesn't turn up anything interesting. Are people still hitting this? @ixv, @somlus-savlev ?

The "wire not unique" printfs got slimmed down significantly in #2840. They should arguably not be happening in the first place, but I suspect any serious slowness would be gone at this point.

**Comment by loganallenc** [comment] 2020-07-01 22:20
I imagine this could have been fixed by the Linux sigsegv work Phil did.

**Comment by matildepark** [comment] 2020-08-31 19:57
Could not be reproduced for several months without subsequent reports.

**Closed by matildepark** 2020-08-31 19:57 UTC
Labels: landscape, link
