### ISSUE TITLE
Can't join any notebook

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2509] opened 2020-03-14 21:11 UTC
**Describe the bug**

Getting errors when I try to join a Notebook from a Group. The join flow seemingly returns successful — no fail in the JS console — but since we never get the notebook, it doesn't redirect.

```
{ [p=[wire=/permissions ship=~haddef-sigwen term=%permission-store] q=[acked=%.y path=/updates]]
  [p=[wire=/subscribe/~dopzod/fora ship=~dopzod term=%publish] q=[acked=%.y path=/notebook/fora]]
  [p=[wire=/subscribe/~wicdev-wisryt/philip-s-digest ship=~wicdev-wisryt term=%publish] q=[acked=%.n path=/notebook/philip-s-digest]]
  [p=[wire=/collection/the-new-era ship=~minder-folden term=%publish] q=[acked=%.n path=/collection/the-new-era]]
  [p=[wire=/collection/anonymous-urbit-inspired-fiction ship=~ravmel-ropdyl term=%publish] q=[acked=%.y path=/collection/anonymous-urbit-inspired-fiction]]
  [p=[wire=/invites ship=~haddef-sigwen term=%invite-store] q=[acked=%.y path=/invitatory/publish]]
  [p=[wire=/collection/bulletin-board ship=~wicdev-wisryt term=%publish] q=[acked=%.y path=/collection/bulletin-board]]
}
subscribe wire not unique
%publish
/subscribe/~wicdev-wisryt/philip-s-digest
[p=~wicdev-wisryt q=%publish]
error in %publish
%watch-not-unique
! subscribe wire not unique
! %publish
! /subscribe/~wicdev-wisryt/philip-s
```

**Desktop (please complete the following information):**
 - Base hash of your urbit ship. Run ` .^(@uv %cz /=base=)` in Dojo to see this.

0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl

**Comment by ixv** [comment] 2020-03-14 21:44
Can you run `:publish +dbug %bowl` and paste the output here?

**Comment by matildepark** [comment] 2020-03-14 21:46
```
[ [our=~haddef-sigwen src=~haddef-sigwen dap=%publish]
  [   wex
    { [p=[wire=/permissions ship=~haddef-sigwen term=%permission-store] q=[acked=%.y path=/updates]]
      [p=[wire=/subscribe/~dopzod/fora ship=~dopzod term=%publish] q=[acked=%.y path=/notebook/fora]]
      [p=[wire=/collection/the-new-era ship=~minder-folden term=%publish] q=[acked=%.n path=/collection/the-new-era]]
      [p=[wire=/invites ship=~haddef-sigwen term=%invite-store] q=[acked=%.y path=/invitatory/publish]]
      [p=[wire=/collection/bulletin-board ship=~wicdev-wisryt term=%publish] q=[acked=%.y path=/collection/bulletin-board]]
    }
    sup={[p=~[/g/use/launch/~haddef-sigwen/out/~haddef-sigwen/publish/publishtile /d //term/1] q=[p=~haddef-sigwen q=/publishtile]]}
  ]
  act=4.282
  eny=0v3ms.n96dq.gkus5.4mr0a.k625m.isd36.1e4e2.n6gqi.jek8g.dm18a.rc1bl.pf098.r19gs.e92kh.84umi.hvttu.cmka9.ld35v.0gqid.k8ejj.4iakj
  now=~2020.3.14..21.46.00..6950
  byk=[p=~haddef-sigwen q=%home r=[%da p=~2020.3.13..14.44.29..b797]]
]
```

**Comment by ixv** [comment] 2020-03-14 21:51
Very strange, it says subscribe wire not unique, but the subscription isn't in there. In the first printout it says `acked=%.n` for that notebook.

Did you successfully subscribe to the fora notebook? I suspect this is an issue related to using foreign groups with a notebook.

**Comment by matildepark** [comment] 2020-03-14 21:52
I did subscribe to it successfully. It's the only Notebook I have. (I thought I had more pre-OTA though. Now I have none but Fora.)

**Comment by ixv** [comment] 2020-03-14 22:15
Okay, looks like when you make a notebook from a foreign pre-existing group, it does not mirror that in the permission store. Then when someone tries to subscribe, the scry for permissions doesn't work.

cc @loganallenc This is related to the modifications to +make-groups you did in the metadata integration.

**Comment by pimato** [comment] 2020-03-15 17:58
I have the same issue!

**Comment by vvisigoth** [comment] 2020-03-16 18:45
Closing as duplicate of #2511

**Closed by vvisigoth** 2020-03-16 18:45 UTC
Labels: OS1, groups, landscape, publish
