### ISSUE TITLE
Message scroll appears with a large number of "new messages" many times, though these have been read previously.

### ISSUE THREAD

**Issue by dabblerdev** [urbit/urbit#2993] opened 2020-06-08 13:41 UTC
This is ~somlus-savlev.  I have an issue where sometimes (but not always) when I refresh my browser or log back on I have a ton of "new messages" (like in the thousands, currently 10,345) but these are messages that I have already read or recognized in bulk as not new by clicking on "Mark as Read." 

I'm not sure why the ship is resetting what it considers to be new. When this happens, the browser freezes up for the landscape tab while I wait for the items to load.  If I wait long enough, the "Mark as read" appears, and then waiting a bit longer will allow it to become active.  Clicking on it and then waiting a bit longer allows those new messages to go away.  Then I'm back down to a reasonable number of new messages.  But eventually the whole process starts again.

This is one of the things I was trying to use |pack to fix, but that caused a crashing issue for me recently so I will not be trying that any longer.

**Comment by matildepark** [comment] 2020-06-08 16:18
This is sort of similar to #2908 but with the addition that your ship isn't processing the `read` action we send as you scroll (or click that 'mark as read' button). Probably this starts because it has to get so many messages to the FE to render, but shouldn't it *eventually* process the read?

**Comment by Fang-** [comment] 2020-06-08 17:22
fwiw I've also experienced the "things marked as unread again" behavior. Generally happens around OTAs or other kinds of downtime, and follows a curious pattern where all the chats affected are hosted by the same ship. Maybe a resubscribe-related bug? The host in question did lose their backlog at one point, so maybe the mismatch in backlog size is causing trouble?

**Comment by matildepark** [comment] 2020-06-08 17:27
> Generally happens around OTAs or other kinds of downtime, and follows a curious pattern where all the chats affected are hosted by the same ship. Maybe a resubscribe-related bug? The host in question did lose their backlog at one point, so maybe the mismatch in backlog size is causing trouble?

Intriguing point — would explain the "seeing messages multiple times" issue we saw last Friday...

**Comment by philipcmonk** [comment] 2020-06-08 19:17
I see this regularly, more often than OTAs, but mostly since I switched to running on my laptop.  It happens from two ships that I know of, and only those.  And it happens always after my laptop was off.

**Comment by somlus-savlev** [comment] 2020-06-09 00:11
The host hiddev-dannut remains on nearly all of the time with rare restarts of the ship or the box. It is happening much more frequently than the number of OTAs or host ship (if by host we mean host of the chat). if by host we mean my ship / server ~somlus-savlev hosting my landscape app then it does indeed seem to correlate quite often with opening up a browser to see what's going on in urbit, not a sudden uptick in unread items in an already open browser accessing landscape. I'll keep a closer eye on this though and report in if I see anything else.

**Comment by matildepark** [comment] 2020-09-09 13:52
@Fang- @philipcmonk Still experiencing?

**Comment by Fang-** [comment] 2020-09-09 15:49
Haven't observed this with recent OTAs. But fwiw I'm pretty sure root cause is a backend issue, and I don't think /app/chat has been touched in a while...

**Comment by matildepark** [comment] 2021-01-13 20:21
Closing as Hark has rendered this issue obsolete.

**Closed by matildepark** 2021-01-13 20:21 UTC
Labels: chat, landscape
