### ISSUE TITLE
Leaving chat...

### ISSUE THREAD

**Issue by gilletteonmeheleparim** [urbit/urbit#2964] opened 2020-06-01 16:35 UTC
`Leaving chat...` on Landscape takes forever
CLI shows: `--------------| del: ~/~dopzod/urbit-help`
and
`[%mailbox-kick i=%~.mailbox t=[i=~.~ t=/~dopzod/urbit-help]]`

**Comment by gilletteonmeheleparim** [comment] 2020-06-01 16:36
it's when I'm trying to leave urbit-help to try rejoining because I'm not getting any more recent messages after 30th may

**Comment by vvisigoth** [comment] 2020-06-22 17:09
@gilletteonmeheleparim just checking on this, did the leave and join ever work? If not, can help debug.

**Comment by gilletteonmeheleparim** [comment] 2020-06-22 19:20
unfortunately I can't remember exactly but I think I had to leave and join multiple times after I had waited some time after I did a continuity breach. it was probably this issue: #2952

**Comment by matildepark** [comment] 2020-08-27 19:42
Duplicate of #2952.

**Closed by matildepark** 2020-08-27 19:42 UTC
