### ISSUE TITLE
publish: endless spinner on submitting post update

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3859] opened 2020-11-02 20:06 UTC
**Describe the bug**
Updating an existing post doesn't terminate. But edit is propagated.

**To Reproduce**
1. Make a post
2. Click on "Update"
3. Update the post
4. Click save

**Expected behavior**
Edit is saved and returned to post screen

**Comment by matildepark** [comment] 2020-11-02 20:22
Dupe of #3844.

**Closed by matildepark** 2020-11-02 20:22 UTC
Labels: landscape
