### ISSUE TITLE
Failed to apply OTA `out of loom!`

### ISSUE THREAD

**Issue by kennyrowe** [urbit/urbit#3730] opened 2020-10-16 00:42 UTC
Can't boot `sicdev-pilnup` failed while apply OTA

```
kiln: OTA to %home succeeded from %kids on ~litzod
kiln: applying OTA to %kids from %kids on ~litzod
vega: compiling hoon
ride: parsing
ride: compiling
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in in, parent 4d4c75a1 not found at 7
fund: in apt, parent 599a8695 not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
fund: in by, parent 4d4c75a1 not found at 7
fund: in apt, parent 6e041c2c not found at 7
ride: compiled
ride: parsing
ride: compiling
ride: compiled
vega: compiling kernel ~hosfur-morwes
ride: parsing
ride: compiling
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
fund: in part, parent 42b21e81 not found at 7
ride: compiled
vega: extracting core
arvo: assembly
arvo: assembled
vega: +load
ride: parsing
ride: compiling
ride: compiled
ride: parsing
ride: compiling
ride: compiled
vega: evolving
zuse: ~watpel-nomdel
vane: %a ~botsep-falluc
vane: %b ~nocsed-radtul
vane: %c ~magdel-lactux
vane: %d ~binlyt-migmec
vane: %e ~labtul-figrux
vane: %g ~livlud-molmed
vane: %i ~rivdyn-fosfer
vane: %j ~fasdyl-filner
~sicdev-pilnup:chat-cli! |\«behn»
bail: meme
bailing out
pier: serf error: end of file
~sicdev-pilnup:chat-cli! |
address 0x438 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 677)
Aborted (core dumped)
```

**Comment by joemfb** [comment] 2020-10-16 03:25
`bail: meme` is the relevant error here. closing as a duplicate of #3645, which has the latest details and instructions.

**Closed by joemfb** 2020-10-16 03:25 UTC
Labels: bug
