### ISSUE TITLE
Leap doesn't respond to any input

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3284] opened 2020-08-11 15:19 UTC
**Describe the bug**
Nothing autofills when I type in Leap

**To Reproduce**
1. Press Cmd + /
2. Modal opens, type name of existing channel in
3. No dropdown, no nothing

**Expected behavior**
A drop down would appear with options

**Screenshots**
<img width="1152" alt="Screen Shot 2020-08-11 at 10 17 57 AM" src="https://user-images.githubusercontent.com/1609955/89915537-1a4fe680-dbbc-11ea-82e3-0e90eb73e747.png">

**Desktop (please complete the following information):**
 - MacOS
 - Browser Chrome

**Additional context**
I have latest base hash dg0q1

**Comment by matildepark** [comment] 2020-08-11 15:57
Duplicate of #3278.

**Closed by matildepark** 2020-08-11 15:57 UTC
Labels: landscape
