### ISSUE TITLE
Twitter embeds don't work with ?s=xx query strings

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3597] opened 2020-09-27 00:40 UTC
**Describe the bug**
Twitter embeds don't seem to work if the url includes a query string, and twitter seems to add ?s=21 or w/e when it's shared. This causes a large amount of twitter embeds to fail

**To Reproduce**
1. Paste twitter url with ?s=21 query string into chat
2. Click expand
3. Observe it doesn't work

**Expected behavior**
Embed should work

**Desktop (please complete the following information):**
 - OS: arch linux 64-bit
 - Browser qutebrowser (chromium engine)
 - Base hash: 0v1g.m6eju.huu13.7ort2.j8fkd.cv693.hlvao.2kkd5.ng36g.3h4jv.oeaff

**Comment by matildepark** [comment] 2020-09-27 01:02
If you refresh the page does it work? Just want to see if dupe of #3500.

**Comment by mike-cr** [comment] 2020-09-27 01:06
yes upon refreshing the query strings have gone and the embeds work correctly

**Comment by matildepark** [comment] 2020-09-27 01:06
Dupe of #3500. (Thanks for testing!)

**Closed by matildepark** 2020-09-27 01:06 UTC
Labels: landscape
