### ISSUE TITLE
group notifications persist until refresh

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#3983] opened 2020-11-20 16:31 UTC
**Describe the bug**

Even after visiting the channels in question and manually clearing notifications from the inbox page, groups still show the same (nonzero) number of notifications.  This appears to affect all groups.  Reloading the page fixes it.

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser: chrome
 - Base hash of your urbit ship: kb4n

**Comment by timlucmiptev** [comment] 2020-11-21 14:14
Exactly the same issue here, same browser and hash. Consistently reproducible.

**Comment by matildepark** [comment] 2020-11-23 16:27
Duplicate of #3977. (I suspect just one line is missing from a reducer for when we're in a room where it's partially dismissing but not decrementing the number of unreads.)

**Closed by matildepark** 2020-11-23 16:27 UTC
Labels: landscape

**Comment by timlucmiptev** [comment] 2020-12-13 14:18
This behavior is still occurring; issue should be re-opened @matildepark
