### ISSUE TITLE
Timestamps Out Of Sequence

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1385] opened 2019-07-25 19:06 UTC
![image](https://user-images.githubusercontent.com/51895363/61901456-6cf12e80-aee5-11e9-9226-34fb39efbef0.png)

**Comment by Fang-** [comment] 2019-07-25 19:25
Depending on circumstances, this is either a duplicate of urbit/arvo#514 (which will be moved over to this repo soon), or not-an-issue. So I'll close this, but thank you for submitting regardless!

If a sender composes & submits a message, its timestamp gets set. But the message isn't guaranteed to reach the host right away, there could be any number of communication issues. If the host doesn't receive the message until an hour later, the timestamp of the message will appear to be an hour behind (and possibly appear delivered out of sequence) by the time it can actually relay it to the subscribers.

**Closed by Fang-** 2019-07-25 19:25 UTC

**Comment by jfranklin9000** [comment] 2019-07-26 01:22
We could show two timestamps: the timestamp from the sender (what is seen now if I understand Fang), and the timestamp when received.  This would give some interesting info on ames latency.  This is totally something I'd do in my program.

**Comment by galenwp** [comment] 2019-07-26 17:33
I like that idea
