### ISSUE TITLE
Moon born with subscriptions

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2154] opened 2020-01-07 00:59 UTC
I created a moon, and when I started it up, I immediately received messages from ~minder-folden's channel subscriptions with the * glyph for all of them. When I ran `;what` it returned nothing.

**Comment by Fang-** [comment] 2020-01-07 05:03
This seems like half-intended behavior. Expected behavior is for moons to get messages from your planet, which is (at least partially) happening. It's showing up with the `*` (unbound audience) special-glyph because glyph bindings aren't synced right now, as they live in chat-cli only.

**Comment by matildepark** [comment] 2020-08-31 19:36
Closed via #2901.

**Closed by matildepark** 2020-08-31 19:36 UTC
Labels: chat
