### ISSUE TITLE
Question: how to create a planet? (how to get friends on board?)

### ISSUE THREAD

**Issue by bstro** [urbit/urbit#1215] opened 2019-02-27 17:19 UTC
I'd ask this in `~dopzod/urbit-help` but my client says it can't connect, so that's a whole other thing.

I'm wondering how to create points for friends to join me in a private chat. First, I have no idea how to do any of this. My current set of assumptions are:

I need to spawn a child point from my star. Though bridge doesn't specifically say this, I'm assuming that if I issue a child point from my star using bridge, that will create a planet. I assume that if my friends give me addresses to their individual eth wallets, I can spawn a child point for each and bind to their wallets respectively.

Am I right about this?

Or do I need to issue child points from a ship? I believe I have two stars and a ship but I don't know what the functional differences are between them and haven't found any documentation so far that clears this up for me.

Thanks a bunch for your help!!

**Comment by Fang-** [comment] 2019-02-27 17:28
You seem entirely on the right track! You issue planets from a star if you want to get your friends their own identities. You use Bridge to "spawn" planets from your star to their Ethereum addresses. They then accept this planet, and then configure from there. You'll all need a bit of ETH to pay for the on-chain transactions representing these operations.

Note that your star will need to be live for any of its planets to be able to connect to the network.  
There's currently also [an issue](https://github.com/urbit/arvo/issues/1032) where new public keys don't get propagates to the entire network properly, so that may keep both your star and planet from connecting, depending on circumstances and who you're talking to. This may or may not be the cause behind your connectivity issue with ~dopzod, too.

The current process for this is very bare-bones, "you're on your own"-style onboarding. We'll have a better flow for inviting people onto the network later this year.

**Comment by bstro** [comment] 2019-02-27 17:40
Thanks, @Fang- ! When you say that my "star will need to be live", what exactly do you mean by that? Thanks again.

**Comment by Fang-** [comment] 2019-02-27 18:06
I mean that, for the planets to get onto the Arvo network, their star needs to be live/connected on the Arvo network.

**Comment by bstro** [comment] 2019-02-28 05:20
Ah, so probably best if I get my star running on AWS or something, yeah?

**Comment by Fang-** [comment] 2019-02-28 16:55
Yes, it's advisable to run a star on a "real" server, rather than, say, a personal laptop.

**Comment by jtobin** [comment] 2019-05-02 13:02
(I'll close this as it seems to have been resolved.)

**Closed by jtobin** 2019-05-02 13:02 UTC
Labels: question

**Comment by anthonykarrick** [comment] 2020-01-16 05:01
hi @Fang- , what commands do i use to go from my server hosted start to an ETH address so i can get them with bridge?  Thanks!

**Comment by Fang-** [comment] 2020-01-16 19:34
ftr, currently resolving @anthonykarrick's question out of band.
