### ISSUE TITLE
Web Interface Dead

### ISSUE THREAD

**Issue by minderfolden** [urbit/urbit#6134] opened 2022-12-07 19:11 UTC
**Describe the bug**
I go to my URL and nothing loads because it takes too long and times out. I try with the direct IPAddress:port and same thing. I can ssh into my cloud instance and use dojo just fine. I've |suspended almost everything to reduce variables; still not working.

Here's my +vats output: https://pastebin.com/83iuX4h4

**To Reproduce**
Steps to reproduce the behaviour:
1. Receive update
2. Have web interface break.

**Expected behavior**
Input URL, have grid show up.

**System (please supply the following information, if relevant):**
 - OS: DigitalOcean droplet
 - Running 1.13 binaries.
 - Your ship's `%base` hash (use `+trouble` to check)

**Additional context**
`¯\_(ツ)_/¯`

**Notify maintainers**
`¯\_(ツ)_/¯`

**Comment by sigilante** [comment] 2022-12-07 19:38
Can you post `+vats` and maybe `+agents %base`, `+agents %landscape`, `+agents %garden`?

**Comment by minderfolden** [comment] 2022-12-07 19:40
```
> +agents %base
status: running   %acme
status: running   %hood
status: running   %lens
status: running   %dbug
status: running   %azimuth
status: running   %ping
status: running   %dojo
status: running   %eth-watcher
status: running   %spider
status: running   %herm

> +agents %landscape
status: running   %group-store
status: running   %metadata-store
status: running   %graph-push-hook
status: running   %group-view
status: running   %hark-graph-hook
status: running   %hark-group-hook
status: running   %metadata-pull-hook
status: running   %contact-pull-hook
status: running   %contact-push-hook
status: running   %invite-hook
status: running   %contact-view
status: running   %invite-view
status: running   %s3-store
status: running   %contact-store
status: running   %clock
status: running   %group-pull-hook
status: running   %launch
status: running   %metadata-push-hook
status: running   %group-push-hook
status: running   %graph-pull-hook
status: running   %weather
status: running   %dm-hook
status: running   %sane
status: running   %contact-hook
status: running   %invite-store
status: running   %graph-store
status: running   %metadata-hook
status: running   %chat-view
status: running   %observe-hook
status: running   %hark-invite-hook
status: running   %chat-hook
status: running   %chat-cli
status: running   %hark-chat-hook
status: running   %chat-store

> +agents %garden
status: running   %hark-system-hook
status: running   %treaty
status: running   %docket
status: running   %settings-store
status: running   %hark-store
```

**Comment by minderfolden** [comment] 2022-12-07 19:41
installing %garden skipped due to being identical. 

```
kiln: beginning install into %base from ~lander-dister-dozzod-dozzod/%base
> |install ~lander-dister-dozzod-dozzod %base
>=
```

**Comment by sigilante** [comment] 2022-12-07 19:43
I meant `|install ~lander-dister-dozzod-dozzod %landscape`, sorry, but that shouldn't mess anything up for you anyway.

**Comment by sigilante** [comment] 2022-12-07 19:43
Switch back to `|install ~mister-dister-dozzod-dozzod %base`

**Comment by minderfolden** [comment] 2022-12-07 19:45
```
kiln: beginning install into %landscape from ~lander-dister-dozzod-dozzod/%landscape
> |install ~lander-dister-dozzod-dozzod %landscape
>=
kiln: activated install into %landscape from ~lander-dister-dozzod-dozzod/%landscape
kiln: downloading update for %landscape from ~lander-dister-dozzod-dozzod/%landscape
kiln: finished downloading update for %landscape from ~lander-dister-dozzod-dozzod/%landscape
kiln: remote is identical to %landscape from ~lander-dister-dozzod-dozzod/%landscape, skipping
kiln: beginning install into %base from ~mister-dister-dozzod-dozzod/%base
> |install ~mister-dister-dozzod-dozzod %base
>=
kiln: activated install into %base from ~mister-dister-dozzod-dozzod/%base
kiln: downloading update for %base from ~mister-dister-dozzod-dozzod/%base
```

**Comment by minderfolden** [comment] 2022-12-07 19:46
Still timing out

**Comment by sigilante** [comment] 2022-12-07 19:49
I had a similar unresponsiveness and after the above I got it working with this:

```
|suspend %landscape
|suspend %garden
|revive %garden
|revive %landscape
```

**Comment by joemfb** [comment] 2022-12-07 19:56
This might be #6113?

**Comment by minderfolden** [comment] 2022-12-07 20:10
Suspended both, revived both; no dice.

**Comment by minderfolden** [comment] 2022-12-07 20:10
I also tried running the cert thing from #6113 about an hour ago; my problem persists.

**Comment by joemfb** [comment] 2022-12-07 20:14
Just to be sure: you are trying to access the web interface on the same port that urbit is using?

**Comment by minderfolden** [comment] 2022-12-07 20:17
I boot with `./minder-folden/.run -p 34543 --loom 32`
Which gets
```
~
urbit 1.13
boot: home is /mnt/volume_nyc1_02/minder-folden
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 4096MB
boot: protected loom
live: loaded: GB/1.430.159.360
boot: installed 351 jets
vere: checking version compatibility
ames: live on 34543
conn: listening on /mnt/volume_nyc1_02/minder-folden/.urb/conn.sock
gall: not running %ducket yet, got %leave
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12323
pier (590012119): live
```
And I put in `http://minderfolden.com` which then tries to resolve to `https://minderfolden.com:8444/`

**Comment by sigilante** [comment] 2022-12-07 20:19
What about `https://minderfolden.com:8080`?

**Comment by minderfolden** [comment] 2022-12-07 20:22
Spinner. Times out.

**Comment by joemfb** [comment] 2022-12-07 20:36
This looks like firewall rules and/or reverse proxy. Are you using Caddy or nginx? In the past, did you set `CAP_NET_BIND` on the binary so that it could get port 80?

**Comment by minderfolden** [comment] 2022-12-07 20:43
Caddy I believe, and yes to cap_net_bind. But I didn't change any of those after the OTA.

Back when I set up the droplet I ran:

```
sudo apt-get install libcap2-bin
sudo setcap 'cap_net_bind_service=+ep' ./urbit
```

**Comment by tomholford** [comment] 2022-12-07 21:01
Can you run Caddy server with verbose logging and try a few requests?

**Comment by minderfolden** [comment] 2022-12-07 21:16
> Can you run Caddy server with verbose logging and try a few requests?

That's a little beyond my current technical abilities.

**Comment by minderfolden** [comment] 2022-12-07 21:17
> you have to redo `CAP_NET_BIND` every time you update the binary. it lives on the file itself, not the file path.

I updated to the 1.13 binaries and the url still worked.

**Comment by wundrellama** [comment] 2022-12-08 01:36
Having the same issue with a star on a DO droplet using the 1.13 binaries. Almost identical config.

**Comment by zalberico** [comment] 2022-12-08 06:04
<img width="418" alt="Screenshot 2022-12-07 at 10 03 09 PM" src="https://user-images.githubusercontent.com/441466/206369715-1af5795a-1860-4883-9d27-d677e78a2480.png">

This looks like #6113 to me - or at least it seems too similar for me to dismiss it.

@tinnus-napbus and @tomholford is there anything else he should check here to fix/confirm?

**Comment by joemfb** [comment] 2022-12-08 06:11
```
$ curl -v http://minderfolden.com/
*   Trying 67.205.149.123:80...
* Connected to minderfolden.com (67.205.149.123) port 80 (#0)
> GET / HTTP/1.1
> Host: minderfolden.com
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 308 Permanent Redirect
< Connection: close
< Location: https://minderfolden.com/
< Server: Caddy
< Date: Thu, 08 Dec 2022 06:07:49 GMT
< Content-Length: 0
<
* Closing connection 0
```

#6113 is related to a 301 redirect, but this is a 308 redirect from Caddy. A quick search turns up relevant discussion, see https://github.com/caddyserver/caddy/issues/3722 or https://caddy.community/t/reverse-proxy-continual-308-replies/9687, for example.

**Comment by joemfb** [comment] 2022-12-08 06:15
Continuing down the rabbit hole:

```
$ curl -v https://minderfolden.com/
*   Trying 67.205.149.123:443...
* Connected to minderfolden.com (67.205.149.123) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=minderfolden.com
*  start date: Oct 25 03:16:29 2022 GMT
*  expire date: Jan 23 03:16:28 2023 GMT
*  subjectAltName: host "minderfolden.com" matched cert's "minderfolden.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x138012c00)
> GET / HTTP/2
> Host: minderfolden.com
> user-agent: curl/7.79.1
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
```

and then it just hangs there...

The certificate is valid here, but not in my browser (brave). This looks to me like Caddy is misconfigured, but it was working for you before, so the proximate cause is presumably #6113 (or something else in this upgrade, but nothing seems relevant).

**Comment by tomholford** [comment] 2022-12-08 07:47
@minderfolden One other idea (originally suggested by @tinnus-napbus while troubleshooting #6113) is to try `curl` like so:

```
curl -v -s -L --max-redirs 5  http://minderfolden.com/ 1> /dev/null
```

**Comment by minderfolden** [comment] 2022-12-08 11:46
> @minderfolden One other idea (originally suggested by @tinnus-napbus while troubleshooting #6113) is to try `curl` like so:
> 
> ```
> curl -v -s -L --max-redirs 5  http://minderfolden.com/ 1> /dev/null
> ```

I put this into my droplet outside the urbit environment, right?

**Comment by minderfolden** [comment] 2022-12-08 11:52
The domain is registered at dreamhost: 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/51895363/206439470-25be4004-e62b-4fc8-8702-78c625861cb1.png">

Using custom nameservers that point to digitalocean:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/51895363/206439523-40450d1c-fedc-4bec-a3e7-d2d9c24b6614.png">

With these settings in digital ocean:
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/51895363/206439863-bd8a9881-ca76-4dd8-841e-d0c16c236082.png">


And this setup was working before the OTA, nothing changed on my end, then the OTA wipes me out. `¯\_(ツ)_/¯`

**Comment by minderfolden** [comment] 2022-12-08 14:27
Oh, and I had tried `|pass [%e %rule %cert ~]` too.

**Comment by vcavallo** [comment] 2022-12-08 14:28
Do you have access to VPS in order to try `curl`ing localhost:8080 from within the machine, just to see if there's any difference there?

**Comment by minderfolden** [comment] 2022-12-08 14:28
> Do you have access to VPS in order to try `curl`ing localhost:8080 from within the machine, just to see if there's any difference there?

Not sure; don't know what that is.

**Comment by vcavallo** [comment] 2022-12-08 14:32
> Caddy I believe, and yes to cap_net_bind. But I didn't change any of those after the OTA.
> 
> Back when I set up the droplet I ran:
> 
> ```
> sudo apt-get install libcap2-bin
> sudo setcap 'cap_net_bind_service=+ep' ./urbit
> ```

The terminal where you ran these commands seems to be the terminal of the server that is running the urbit you're trying to reach.

When you started the urbit this way:

> I boot with `./minder-folden/.run -p 34543 --loom 32` Which gets
> 
> ```
> ~
> urbit 1.13
> boot: home is /mnt/volume_nyc1_02/minder-folden
> loom: mapped 2048MB
> lite: arvo formula 11a9e7fe
> lite: core 38d4ad4d
> lite: final state 38d4ad4d
> loom: mapped 4096MB
> boot: protected loom
> live: loaded: GB/1.430.159.360
> boot: installed 351 jets
> vere: checking version compatibility
> ames: live on 34543
> conn: listening on /mnt/volume_nyc1_02/minder-folden/.urb/conn.sock
> gall: not running %ducket yet, got %leave
> http: web interface live on http://localhost:8080
> http: loopback live on http://localhost:12323
> pier (590012119): live
> ```
> 
> And I put in `http://minderfolden.com` which then tries to resolve to `https://minderfolden.com:8444/`

One of the bits of logging was:

> > http: web interface live on http://localhost:8080

I'd be curious what you get if you do - from the same command line where these commands were run - this:

`curl -v http://localhost:8080`

For instance, on my local machine with a running fake zod, I get this:

```
+$ curl -v http://localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.71.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 moved
< Date: Thu, 08 Dec 2022 14:30:50 GMT
< Connection: close
< Server: urbit/vere-1.13
< location: /~/login?redirect=/
< 
* Closing connection 0
```

Where we can see the redirect to ` location: /~/login?redirect=/` - which tells me that I'm hitting the urbit web interface and getting redirected to the login.

**Comment by minderfolden** [comment] 2022-12-08 15:26
```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 504 gateway timeout
< Date: Thu, 08 Dec 2022 15:05:27 GMT
< Connection: keep-alive
< Content-Length: 15
< Server: urbit/vere-1.13
< content-type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
```

**Comment by minderfolden** [comment] 2022-12-08 15:40
I tried it from the folder where my Caddyfile lives, then realized I should probably go to where the pier lives. Here's what I got:

```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 504 gateway timeout
< Date: Thu, 08 Dec 2022 15:37:51 GMT
< Connection: keep-alive
< Content-Length: 15
< Server: urbit/vere-1.13
< content-type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
```

**Comment by minderfolden** [comment] 2022-12-08 16:39
shut down and restarted with this: `./minder-folden/.run -p 34543 -b 67.205.149.123 --loom 32` in hopes that binding it to the ip address would do something. Nope.

**Comment by vcavallo** [comment] 2022-12-08 16:55
Essentially everyone else in this thread is going to be better than me at interpreting that, but unless I'm mistaken, the fact that you're getting a 504/Gateway Timeout when curling from localhost seems to implicate urbit, not Caddy nor SSL nor DNS.
But good chance I'm totally wrong on that :)

**Comment by zalberico** [comment] 2022-12-08 17:45
<img width="485" alt="Screenshot 2022-12-08 at 9 40 54 AM" src="https://user-images.githubusercontent.com/441466/206525049-c3e79e47-efe5-43b6-bc14-29110db831ea.png">

I still suspect this is the cause, but don't understand the issue @tomholford and @tinnus-napbus hit well enough to know why the fix in their case isn't working in this one (or if there is something else different).

I think it's definitely the OTA that started causing this to reveal itself due to https://github.com/urbit/urbit/pull/5987 

@philipcmonk do you have an idea what the next steps might be for this (also tagging @baudtack for context)

**Comment by jfranklin9000** [comment] 2022-12-09 03:44
Have you `sudo setcap 'cap_net_bind_service=+ep'  ./minder-folden/.run` since upgrading the runtime?

**Comment by minderfolden** [comment] 2022-12-09 11:36
> Have you `sudo setcap 'cap_net_bind_service=+ep' ./minder-folden/.run` since upgrading the runtime?

Yep yep.

**Comment by minderfolden** [comment] 2022-12-09 11:39
I powered down and restarted just now:
```
urbit 1.13
boot: home is /mnt/volume_nyc1_02/minder-folden
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 4096MB
boot: protected loom
live: loaded: GB/1.629.765.632
boot: installed 351 jets
vere: checking version compatibility
ames: live on 34543
conn: listening on /mnt/volume_nyc1_02/minder-folden/.urb/conn.sock
gall: not running %ducket yet, got %leave
gall: not running %ducket yet, got %leave
gall: not running %ducket yet, got %leave
gall: not running %ducket yet, got %leave
gall: not running %ducket yet, got %leave
gall: not running %ducket yet, got %leave
gall: not running %ducket yet, got %leave
gall: not running %ducket yet, got %leave
gall: not running %ducket yet, got %leave
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12323
pier (595416135): live
```
Is %ducket important?

**Comment by minderfolden** [comment] 2022-12-09 13:31
I have a droplet with an extra drive installed. The two moons that are still working with Caddyfile are on the original droplet. The planet is on the extra drive. I don't know if that has anything to do with it; figured I'd add the context.

**Comment by minderfolden** [comment] 2022-12-09 20:03
Is there a way to cancel / wipe any/all IP bindings + SSL requests done from inside dojo and just start clean from the dojo side of things?

**Comment by minderfolden** [comment] 2022-12-09 20:08
I updated my moon that hosts my main group; same thing is happening now. Spins until it tries port 8443 and says timed out.

**Comment by minderfolden** [comment] 2022-12-10 01:58
I ran the `|pass cert` thing on my moon and I got: 

```
> |pass [%e %rule %cert ~]
>=
http: restarting servers to apply configuration
http: web interface live on http://localhost:8081
http: loopback live on http://localhost:12321
```
But I've never seen that output on my planet.

And it also didn't fix the spinner of death.

**Comment by zalberico** [comment] 2022-12-10 16:59
Closing the loop on this - @minderfolden was able to get things up and running (debugging with people on the network), @minderfolden when you have a chance to update what you did here that'd be helpful for others that find themselves in the same place, then we're good to close.

Glad you're back online!

**Comment by minderfolden** [comment] 2022-12-10 17:08
Will do; full baby duty; when the wife gets back I'll write a full outline to help others. ::high five::

**Comment by minderfolden** [comment] 2022-12-10 18:37
I have my domain `minderfolden.com` registered at Dreamhost. I forward it to the IP Address of my Digital Ocean droplet. I went through their guide for setting up the DNS records. That's all I needed to access my ship by itself. Then I wanted to host a couple moons on the droplet so I learned that I needed to set up Caddy.

I set up two subdomains on Dreamhost, forwarded them to Digital Ocean, set up the DNS there, and then set up Caddy for two subdomains. They worked, as did the main domain (without adding it to the Caddy file).

Then the OTA came through and the main domain stopped working.

Turns out that I needed to add the main domain to the Caddyfile. It started working when we put in the droplet's IP address with port 8080, but you'd have to add the port to the URL to get it to load like `minderfolden.com:8080` and it would be visible in the address bar.

The trick to getting it to work is not using the digital ocean droplet IP. Instead add the main domain `minderfolden.com` to the Caddyfile with the IP equivalent of localhost:8080 which is `127.0.0.1:8080`.

Once we did that, then the URL would load cleanly. 

#ProblemSolved

**Closed** 2022-12-10 18:39 UTC
Labels: bug
