### ISSUE TITLE
My DMs are still broken

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3218] opened 2020-07-29 17:48 UTC
**Describe the bug**
DM's only appear for one side (the owner).

**To Reproduce**
1. Send a DM
2. If you're the owner, the DM appears in UI
3. If you're not, it is greyed out forever
4. Owners can also recieve new DMs

**Expected behavior**
It works

I have the latest OTA on both ships 0v14.6jq85.45bbd.olulk.d6ahq.p6q00.duosn.0uu5d.grv3j.9i7m1.n91u1

**Comment by matildepark** [comment] 2020-07-29 17:57
@tacryt-socryp @liam-fitzgerald wasn’t the OTA last night supposed to address this?

**Comment by vvisigoth** [comment] 2020-07-29 17:58
hold please, now it seems like some work, haha.

I'll try to notch down on the failure states some more.
—
~poldec-tonteg
http://urbit.org

**Comment by Fang-** [comment] 2020-07-29 22:41
Can reproduce the above, pre-existing DMs still borked for me. Nothing visible changed for me (no DMs deleted, no invites received) with recent OTAs.

**Comment by mikolajpp** [comment] 2020-08-09 14:14
Tried to get a friend on-board. Indeed DM's are borked. I could see the invite, but accepting would result in a black screen of sigils

**Comment by matildepark** [comment] 2020-08-09 14:18
Wait, this shouldn’t be hitting fresh onboards at all. This ticket is about a migration case.

**Comment by matildepark** [comment] 2020-08-09 14:19
Can you file another ticket and include more information here? Screenshot? I’m unsure what blank screen of sigils is.

**Comment by mikolajpp** [comment] 2020-08-09 14:24
Right now I am making a personal breach to rule out some missed OTA issue. 
However, DM's indeed are broken for my ship, even though I could send DM to other ships before. 

This is what happened when I clicked "accept"

```
poke failed from %chat-hook on wire /                                                                        
/~ponmep-litsem/home/0/app/chat-view/hoon:<[258 7].[258 37]>                                                 
/~ponmep-litsem/home/0/app/chat-view/hoon:<[257 7].[258 37]>                                                 
/~ponmep-litsem/home/0/app/chat-view/hoon:<[256 5].[262 7]>                                                  
/~ponmep-litsem/home/0/app/chat-view/hoon:<[208 3].[331 5]>                                                  
/~ponmep-litsem/home/0/app/chat-view/hoon:<[207 3].[331 5]>                                                  
/~ponmep-litsem/home/0/app/chat-view/hoon:<[206 3].[486 5]>                                                  
/~ponmep-litsem/home/0/app/chat-view/hoon:<[205 3].[486 5]>                                                  
/~ponmep-litsem/home/0/app/chat-view/hoon:<[100 7].[100 54]>                                                 
/~ponmep-litsem/home/0/app/chat-view/hoon:<[99 7].[100 54]>                                                  
/~ponmep-litsem/home/0/app/chat-view/hoon:<[86 5].[101 7]>                                                   
/~ponmep-litsem/home/0/app/chat-view/hoon:<[85 5].[101 7]>                                                   
/~ponmep-litsem/home/0/app/chat-view/hoon:<[84 5].[101 7]>                                                   
/~ponmep-litsem/home/~2020.6.13..07.19.29..ea92/sys/vane/gall:<[1.285 9].[1.285 37]>    
```

I will just breach the ship and if the issue persist then I will open a new ticket.

**Comment by matildepark** [comment] 2020-08-09 14:26
We’d first want to establish if you’re running latest OTA — but if you want to breach... as for your friend, they should delete the chat and send you a fresh DM once you’re booted again. It may take 5-10 mins for keys to propagate.

**Comment by mikolajpp** [comment] 2020-08-09 14:27
Here is the `+trouble`

```
[ [%base-hash 0vf.55um2.dupti.knt0u.1fekl.e84eu.e7bbk.q0akf.kore3.ie6ks.m77da]                               
  [%home-hash 0vf.55um2.dupti.knt0u.1fekl.e84eu.e7bbk.q0akf.kore3.ie6ks.m77da]                               
  [%our ship=~ponmep-litsem point='17433088' life=[~ 6] rift=[~ 2]]                                          
  [%sponsor ship=~binzod point='512' life=[~ 3] rift=[~ 0]]                                                  
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]                                                  
  "Compare lifes and rifts to values here:"                                                                  
  "https://etherscan.io/address/azimuth.eth#readContract"                                                    
  "  life - getKeyRevisionNumber"                                                                            
  "  rift - getContinuityNumber"                                                                             
  ~     
```

**Comment by matildepark** [comment] 2020-08-09 14:37
Oddly enough, I can’t find that hash anywhere. But the fact that you don’t have %kids or %glob hash would make you quite old indeed I think.

— 
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment] 2020-08-27 19:24
Duplicate of #3164.

**Closed by matildepark** 2020-08-27 19:24 UTC
Labels: landscape
