### ISSUE TITLE
the urbit binary ought to look for terminfo in standard locations

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3052] opened 2020-06-25 04:26 UTC
If you wanna install urbit with a package manager on linux you must write some kind of wrapper script that executes it with the TERMINFO env-var or cd's over to another directory or some such thing so that it can find its terminfo files. It would be nice if it automatically looked in /usr/share/terminfo and other standard locations so that its binaries can by put in /usr/bin or wherever without additional hackery.

**Comment by joemfb** [comment] 2020-06-25 05:16
This is a long-standing problem (ever since we started shipping static binaries), and I don't know how to handle it correctly --  cross-compiling ncurses is apparently quite involved.

But I have a much dumber solution in the works ... I have a branch (`ipc-redux`) that entirely removes the ncurses dependency and use of the terminfo database. Our terminal requirements are modest, so we can just directly emit widely-supported escape sequences. I'm polishing up the branch (which is part of a much larger set of changes), and hope to release it soon.

**Comment by ohAitch** [comment] 2020-06-25 06:03
And if we need to do more involved terminal-agnostic escapes, there's
always libuncursed…

**Comment by syzygyzer** [comment] 2020-06-25 20:17
@joemfb that sounds like it might address this issue https://github.com/urbit/urbit/issues/1960 which continues to plague me. I would be happy to test once you get to that point, since it seems like a tricky issue to reproduce.

**Comment by joemfb** [comment] 2020-07-01 03:28
This is fixed in #3064.

**Closed** 2020-07-24 05:23 UTC
