### ISSUE TITLE
+-get:by is untyped

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#323] opened 2015-06-22 18:10 UTC
``` hoon
> (~(get by *(map ,^ ,*)) 1)
~
```

should instead be a `type-fail`.

**Comment by juped** [comment] 2015-08-23 02:31
This might require bulls. I haven't forgotten it, though.

**Comment by cgyarvin** [comment] 2015-08-23 02:57
This should be relatively straightforward - you just have to cast the
sample to the container type in ++get (and all the others).  No bulls
required.

**Comment by juped** [comment] 2015-08-23 03:44
As I understand it, the issue is that a the type of a map is a fork of `~` or `[n=[p q] l r]`. If we want to mention `p.n`, say to `^+  p.n  b`, we have to take the second branch of this fork, but here our map is `~` so we can't.

**Comment by cgyarvin** [comment] 2015-08-23 04:08
That's what I thought when I wrote the code, but this is very old code.
You'll see a number of containers that get around this just fine:
^+(?>(?=(^ a) p.n.a) b)

Since we're just casting statically, the ?> is not actually executed and
doesn't cause a problem with empty maps.

You can't actually create a dynamic value that's a p.n.a, but checking the
type statically is no problem.  Which is exactly what we want.

**Comment by juped** [comment] 2015-08-23 04:51
Asserting that `a` isn't empty in order to handle the case where it *is* empty is *crazy* unintuitive, man. I can see what you mean, though - the assert's actually in a tile, not a twig, here. I'll give it a try,

**Comment by cgyarvin** [comment] 2015-08-23 04:56
Well, ^+ is a twig, it's just that the head of that twig is never executed.

It's certainly a hack!  When you have a low-powered type system like this
one, you need to pull out the hacks at the edge of the power envelope.

**Comment by ohAitch** [comment] 2015-08-24 16:16
Heh, I think the solution I'd go for is
|=  _?~(n ** p.n)

Iirc the type system can reason through "a thing nests in 'noun or foo' iff
it's a foo".

**Comment by cgyarvin** [comment] 2015-08-24 17:36
Your sample will be just a noun then, good luck trying to put it in a node...

**Comment by ohAitch** [comment] 2015-08-24 17:44
Then maybe
^+  ?>(?=(^ n) |=(_p.n *(unit ,_ q.n)))
?~  n  |=(* ~)
|=  b=_p.n
?:  =(b p.n)  [~ u=q.n]
?:  (hor b p.n)
  ?~(l ~ $(a l))
?~(r ~ $(a r))

**Comment by cgyarvin** [comment] 2015-08-24 18:00
That works only for reading, though.  And it's kind of gnarly.

**Comment by ohAitch** [comment] 2015-08-24 18:42
I'm guessing it wouldn't be possible to
+-  put
  ^+  ?>(?=(^ a) |=(_n ?:(| ~ a)))
  =+  a
  ?~  -  |*(b=^ `_a`[b ~ ~])
  |=  b=_n
  ...
because |*(^ ...) doesn't nest in |=(_n ...)?

**Comment by cgyarvin** [comment] 2015-08-24 18:45
There's a fine line between hacking and thrashing...

**Comment by ohAitch** [comment] 2015-08-24 18:47
Actually wait put already works fine because of the ^+ a

**Comment by ohAitch** [comment] 2015-08-24 18:51
It's just get where we throw away the value without type-checking it.
Though I suppose
  |*  b=^
  =>  .(b `_?~(a !! n.a)`b)
would be more consistent there. (I maintain "type =."
=>(.({p.gen} ^-({q.gen} {p.gen})) {r.gen}) should be a rune)

**Comment by juped** [comment] 2015-08-24 19:08
Maybe if you have a pathological aversion to `^+`!

**Comment by ohAitch** [comment] 2015-08-24 19:10
or ^+, sure
It would also be helpful for TMI stuff however:

?~  a  ...
=>  .(a `(list foo)` a)
...

comes up a lot.

**Comment by joemfb** [comment] 2019-07-18 19:45
fixed in #1354

**Closed by joemfb** 2019-07-18 19:45 UTC
Labels: arvo issue - moving soon, bug, difficulty medium, hoon language, type system
