### ISSUE TITLE
Local -F fake Ames is now broken between (at least) galaxies and stars

### ISSUE THREAD

**Issue by keatondunsford** [urbit/urbit#935] opened 2018-02-28 17:51 UTC
I discovered this now trying to debug a Womb issue with @belisarius222 by attempting to recreate a local fake network starting with a fake `~zod` and `~marzod`.

Reproduction:

Booting a -F `~zod` on the last working commit urbit/urbit@285c6d2ad2d1e010555a08de0d80d8a9c419f0cd, then booting a -F `~marzod`, works.

Booting a -F `~zod` on the next commit, urbit/urbit@91f2eaadaf0ba968ee54c00589bf32bf502699af, which seems to affect -F in Vere, breaks this. `~marzod` hangs on `~zod not responding still trying`.

CC @cgyarvin

**Comment by keatondunsford** [comment] 2018-02-28 18:10
Another detail: Ted mentioned a new `-N` option. Running the above commands with `-FNI` for `~zod` and `-FN` respectively still doesn't get `~marzod` to successfully talk to local fake `~zod`.

**Comment by cgyarvin** [comment] 2018-02-28 18:30
I’m at a school thing but can poke at it in the afternoon if it’s still broken

**Comment by keatondunsford** [comment] 2018-03-28 18:53
@cgyarvin @ohAitch What's the status on this?

**Comment by ohAitch** [comment] 2018-03-28 19:00
@belisarius222 changed the semantics of `-F` from "fake network with fake keys" to "no network 'with' fake keys", the relevant commits should be reverted so everyone stops being confused.

This was initially prompted by a breach caused by running `-F` on a cloned non-fake-network ship, which should probably be checked for so fake and real ships can't be mixed up again. (the `-N` "make -F fake keys actually do anything" flag can be repurposed for "disable networking regardless of network fakeness", to fulfill the original "we want to run a copy of marzod for forensics without bringing down the network" goal; alternately you could have a `.urb/canonical` or sth flag file that you can delete if you want a ship to never speak to the network again)

**Comment by belisarius222** [comment] 2018-03-28 19:06
This really isn't that much code. I'd expect it would be almost as quick to
just fix the issue.

What's the priority level on this issue? I don't have a gold sense of that.

**Comment by keatondunsford** [comment] 2018-03-28 20:41
@belisarius222, well, we can't really do local development on master Vere until this is fixed by someone.

**Comment by ohAitch** [comment] 2018-03-28 20:44
You can, using `-FN`, but I'd really rather not get everyone into that habit / change all the docs / etc. if we can just restore the semantics that were in place before 2018

**Comment by keatondunsford** [comment] 2018-03-28 20:50
That doesn't work for me.

From a fake ~nec running current master (9978ad8), I can't `|hi` my fake ~zod running on the same local network. I started both with:

```
bin/urbit -FNI zod zod

bin/urbit -FNI nec nec
```

**Comment by ohAitch** [comment] 2018-03-28 21:05
Hm I stand corrected, I've just been running off 5c5374c1f back when -F still worked

**Comment by joemfb** [comment] 2018-09-25 17:15
fixed by #972

**Closed by joemfb** 2018-09-25 17:15 UTC
Labels: %ames, bug, command-line options
