### ISSUE TITLE
unread count too high

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#4128] opened 2020-12-11 10:57 UTC
**Describe the bug**
If like 1 new message comes in the unread count shows 8 or so and the new messages line creeps up past already read messages

**To Reproduce**
1. Go to a chat channel
2. Wait for new message
3. Observe unread count too high and new messages line is above already-read messages

**Expected behavior**
unread count should be accurate

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser qutebrowser
 - Base hash im23k

**Comment by matildepark** [comment] 2020-12-11 14:18
I suspect this is a duplicate of #4012 that is becoming more legible — both are addNode notifications

**Comment by matildepark** [comment] 2020-12-11 16:48
Duplicate of #4012 — we'll tackle this there in one place.

**Closed by matildepark** 2020-12-11 16:48 UTC
Labels: landscape
