### ISSUE TITLE
Can't load Landscape and lots of log errors

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#4426] opened 2021-02-12 01:49 UTC
Landscape doesn't load at all and I have a lot of these in the console:

```
error in %contact-pull-hook
%fact
! closing subscription
! nest-fail
!
  - have
  [ %edit
    ship=@p
    edit-field=?([%add-group resource=[entity=@p name=@tas]] [%avatar avatar=u(@t)] [%bio bio=@t] [%color color=@ux] [%cover cover=u(@t)] [%nickname nickname=@t] [%remove-group resource=[entity=@p name=@tas]] [%status status=@t])
    timestamp=@da
  ]
!
  - need
  ?(
    [%add ship=@p contact=[nickname=@t bio=@t status=@t color=@ux avatar=u(@t) cover=u(@t) groups=nlr([entity=@p name=@tas]) last-updated=@da]]
    [%allow beings=?([%group resource=[entity=@p name=@tas]] [%ships ships=nlr(@p)])]
    [%disallow beings=?([%group resource=[entity=@p name=@tas]] [%ships ships=nlr(@p)])]
    [%edit ship=@p edit-field=?([%add-group resource=[entity=@p name=@tas]] [%avatar avatar=u(@t)] [%bio bio=@t] [%color color=@ux] [%cover cover=u(@t)] [%nickname nickname=@t] [%remove-group resource=[entity=@p name=@tas]] [%status status=@t])]
    [%initial rolodex=nlr([p=@p q=[nickname=@t bio=@t status=@t color=@ux avatar=u(@t) cover=u(@t) groups=nlr([entity=@p name=@tas]) last-updated=@da]]) is-public=?(%.y %.n)]
    [%remove ship=@p]
    [%set-public public=?(%.y %.n)]
  )
! /lib/contact/hoon:<[19 22].[19 43]>
! /lib/contact/hoon:<[19 3].[28 5]>
! /lib/contact/hoon:<[18 3].[43 5]>
! /lib/contact/hoon:<[17 3].[43 5]>
! /lib/pull-hook/hoon:<[521 46].[521 75]>
! /lib/pull-hook/hoon:<[521 19].[521 76]>
! /lib/pull-hook/hoon:<[521 9].[521 76]>
! /lib/pull-hook/hoon:<[521 5].[526 83]>
! /lib/pull-hook/hoon:<[519 5].[526 83]>
! /lib/pull-hook/hoon:<[518 5].[526 83]>
! /lib/pull-hook/hoon:<[324 11].[324 44]>
! /lib/pull-hook/hoon:<[324 9].[324 45]>
! /lib/pull-hook/hoon:<[323 9].[324 45]>
! /lib/pull-hook/hoon:<[319 9].[324 45]>
! /lib/pull-hook/hoon:<[302 7].[325 9]>
! /lib/pull-hook/hoon:<[300 7].[325 9]>
! /lib/pull-hook/hoon:<[298 7].[325 9]>
! /lib/pull-hook/hoon:<[294 7].[325 9]>
! /lib/pull-hook/hoon:<[293 7].[325 9]>
! /sys/vane/gall/hoon:<[1.443 9].[1.443 49]>
```

**Comment by matildepark** [comment] 2021-02-12 01:50
Duplicate of https://github.com/urbit/landscape/issues/403

**Closed by matildepark** 2021-02-12 01:50 UTC
Labels: bug

**Comment by tylershuster** [comment] 2021-02-12 01:54
Is it? Mine is `%contact-pull-hook`

**Comment by matildepark** [comment] 2021-02-12 01:54
Yeah, basically.
