### ISSUE TITLE
This is getting spit out every couple seconds after |hi ~dopzod

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1384] opened 2019-07-25 19:04 UTC
`/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.383 7].[1.384 16]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.383 22].[1.383 52]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.527 5].[1.630 48]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.528 5].[1.630 48]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.530 5].[1.630 48]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.544 5].[1.630 48]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.547 5].[1.630 48]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.547 9].[1.623 11]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.548 9].[1.623 11]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.549 9].[1.623 11]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[1.564 11].[1.564 59]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[660 7].[673 24]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[661 7].[673 24]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[662 7].[673 24]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[663 7].[673 24]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[665 7].[673 24]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[667 7].[673 24]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[669 7].[673 24]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[670 7].[673 24]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[672 7].[673 24]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[889 13].[1.002 15]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[890 13].[1.002 15]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[890 17].[890 21]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[895 15].[929 19]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[900 15].[929 19]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[905 15].[929 19]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[910 15].[929 19]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[911 17].[911 21]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[933 15].[950 19]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[934 15].[950 19]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[935 15].[950 19]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[936 15].[950 19]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[936 25].[936 29]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[953 15].[993 17]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[954 15].[993 17]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[973 17].[982 34]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[974 17].[982 34]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[975 17].[982 34]>
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ames:<[976 17].[982 34]>
~minder-folden:dojo>`

**Comment by Fang-** [comment] 2019-07-25 19:18
Seems like a duplicate of what's discussed in #1379, so closing this. Thanks though!

**Closed by Fang-** 2019-07-25 19:18 UTC
