### ISSUE TITLE
Group Weirdness

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#3100] opened 2020-07-07 13:22 UTC
**Describe the bug**
Strange group behavior: Inviting ship (~roswet) could send to receiving ship (~minder-folden) and both can `|hi` each other. ~minder can accept invitation to the group, and the group channels are visible in group management area immediately after accepting. The group, however, does not show up in the group management page's left sidebar even after waiting awhile. The member custom sigils never show up, and even after sharing `~minder-folden`'s details the pre-share notification text is present. Additionally `~minder-folden` is able to join a chat channel and view it, and the group shows up in the left sidebar of the chat page there.

**Expected behavior**
Join and share info.

**Screenshots**
![image](https://user-images.githubusercontent.com/51895363/86787175-7017f880-c02a-11ea-8812-754dfe0769d0.png)

**Desktop (please complete the following information):**
 - OS: PopOS Linux
 - Browser Chromium
 - Base hash of your urbit ship: `~minder-folden: dhk61` & `~roswet: dhk61`
(I used `.^(@uv %cz /=base=)` instead of `+trouble` and got `t74k1` but `+trouble` gives me the proper one.)

**Additional context**
`~roswet` is getting this too:
```
[ %missing-subscription-in-unsubscribe
  /channel/subscription/1594066253465-50decc/13
]
[ %missing-subscription-in-unsubscribe
  /channel/subscription/1594066253465-50decc/14
]
```

**Comment by matildepark** [comment] 2020-07-07 14:49
Suspect this is a dupe of #2857, addressed by #2937. Though I would also ask that you ensured you removed your old ship from the group before reinviting?

**Closed** 2020-07-13 17:56 UTC
Labels: landscape
