### ISSUE TITLE
`-c` with `-F` but without `-I` loops indefinitely

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#451] opened 2015-10-22 22:11 UTC
`bin/urbit -F -I zod -c [pier directory]`

works as expected,  but

`bin/urbit -F -c [pier directory]`

doesn't.  It gets stuck in `<awaiting hood, this may take a few minutes>`.

OK, fine, don't do that, but we should detect this in `main()` and exit with a helpful message.

Do all usages of -F expect -I?  Or just -c (and maybe a few others)?

**Comment by juped** [comment] 2015-10-22 22:12
Not a bug. If you actually made a fake `~zod`, then your fake comet should come up fine.

**Comment by chc4** [comment] 2015-10-23 01:51
Related question, does -F currently imply -L? Or are all packets being broadcasted to the live network, just not being acked due to invalid keys.

**Comment by juped** [comment] 2015-10-23 02:07
See [lines 140-145](https://github.com/urbit/urbit/blob/c7658e3894132410abb12d300e53cb587b8386a6/vere/main.c#L140).

Closing this since it's not a bug (I tested a -F local network).

**Closed by juped** 2015-10-23 02:07 UTC
