### ISSUE TITLE
Strange Selection Behavior

### ISSUE THREAD

**Issue by benjamin-tlon** [urbit/urbit#2331] opened 2020-02-21 13:04 UTC
Apologies if this has already been noted. This is my first time using the issues system.

![screenshot](https://i.imgur.com/q59RzQp.png "Screenshot")

Selection behavior is strange:

- Selection is right-to-left on each line?

- As soon as the selection includes the first line, it also jumps to include the sender/date, so it's impossible to just select only the text of a message.

**Comment by Fang-** [comment] 2020-02-21 13:16
This is caused by our strange message log rendering implementation. I expect this is fixed by #2295.

**Comment by litpub** [comment] 2020-02-24 19:19
That's correct, selection works as you'd expect in #2295

**Comment by litpub** [comment] 2020-02-24 23:36
This is closed now that #2295 is merged

**Comment by matildepark** [comment] 2020-03-12 18:04
Reopened as of #2438.

**Comment by matildepark** [comment] 2020-06-09 16:36
This is a won't fix — I don't think we're going to go off the `flex-column-reverse` implementation anytime soon.

**Closed by matildepark** 2020-06-09 16:36 UTC
Labels: chat, landscape
