### ISSUE TITLE
%dangling-bone ~binzod 452 on a planet

### ISSUE THREAD

**Issue by mrdomino** [urbit/urbit#5549] opened 2022-01-20 02:09 UTC
Related to (instance of?) #2359.

I'm now seeing %dangling-bone errors often in my console. They seem to have started around the last OTA, but it could've been before that and I just didn't notice. I still seem able to reach ~binzod from ~silsyn-wathep, which is the affected ship.

Most recent log output:

```
[%poke %crud]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[880 3].[909 20]>
/sys/vane/ames/hoon:<[882 3].[909 20]>
/sys/vane/ames/hoon:<[883 3].[909 20]>
/sys/vane/ames/hoon:<[885 3].[909 20]>
/sys/vane/ames/hoon:<[886 5].[907 7]>
/sys/vane/ames/hoon:<[889 5].[907 7]>
/sys/vane/ames/hoon:<[890 7].[893 9]>
/sys/vane/ames/hoon:<[892 16].[892 60]>
/sys/vane/ames/hoon:<[1.243 5].[1.243 43]>
/sys/vane/ames/hoon:<[1.249 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.251 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.254 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.330 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.331 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.334 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.342 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.343 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.344 5].[1.379 62]>
[%ames-crash-on-packet-from ~binzod]
/sys/vane/ames/hoon:<[1.345 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.349 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.378 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.379 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.379 10].[1.379 62]>
/sys/vane/ames/hoon:<[1.933 7].[1.958 69]>
/sys/vane/ames/hoon:<[1.936 7].[1.958 69]>
/sys/vane/ames/hoon:<[1.938 7].[1.958 69]>
/sys/vane/ames/hoon:<[1.940 7].[1.958 69]>
/sys/vane/ames/hoon:<[1.941 9].[1.946 65]>
/sys/vane/ames/hoon:<[1.946 9].[1.946 65]>
/sys/vane/ames/hoon:<[2.174 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.177 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.180 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.181 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.182 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.185 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.185 11].[2.193 37]>
/sys/vane/ames/hoon:<[2.186 11].[2.193 37]>
/sys/vane/ames/hoon:<[2.187 11].[2.193 37]>
/sys/vane/ames/hoon:<[2.188 11].[2.193 37]>
/sys/vane/ames/hoon:<[2.189 13].[2.192 15]>
/sys/vane/ames/hoon:<[2.190 22].[2.190 63]>
/sys/vane/ames/hoon:<[2.226 9].[2.244 21]>
/sys/vane/ames/hoon:<[2.229 9].[2.244 21]>
/sys/vane/ames/hoon:<[2.229 24].[2.229 66]>
/sys/vane/ames/hoon:<[2.229 30].[2.229 45]>
/sys/vane/ames/hoon:<[2.098 7].[2.100 50]>
/sys/vane/ames/hoon:<[2.099 7].[2.100 50]>
[%dangling-bone ~binzod 452]
/sys/vane/ames/hoon:<[2.100 7].[2.100 50]>
hear: bail: %exit

[%poke %hear]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[880 3].[909 20]>
/sys/vane/ames/hoon:<[882 3].[909 20]>
/sys/vane/ames/hoon:<[883 3].[909 20]>
/sys/vane/ames/hoon:<[885 3].[909 20]>
/sys/vane/ames/hoon:<[886 5].[907 7]>
/sys/vane/ames/hoon:<[889 5].[907 7]>
/sys/vane/ames/hoon:<[895 5].[907 7]>
/sys/vane/ames/hoon:<[897 14].[897 53]>
/sys/vane/ames/hoon:<[1.243 5].[1.243 43]>
/sys/vane/ames/hoon:<[1.249 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.251 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.254 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.330 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.331 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.334 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.342 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.343 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.344 5].[1.379 62]>
[%ames-crash-on-packet-from ~binzod]
/sys/vane/ames/hoon:<[1.345 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.349 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.378 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.379 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.379 10].[1.379 62]>
/sys/vane/ames/hoon:<[1.933 7].[1.958 69]>
/sys/vane/ames/hoon:<[1.936 7].[1.958 69]>
/sys/vane/ames/hoon:<[1.938 7].[1.958 69]>
/sys/vane/ames/hoon:<[1.940 7].[1.958 69]>
/sys/vane/ames/hoon:<[1.941 9].[1.946 65]>
/sys/vane/ames/hoon:<[1.946 9].[1.946 65]>
/sys/vane/ames/hoon:<[2.174 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.177 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.180 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.181 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.182 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.185 7].[2.308 9]>
/sys/vane/ames/hoon:<[2.185 11].[2.193 37]>
/sys/vane/ames/hoon:<[2.186 11].[2.193 37]>
/sys/vane/ames/hoon:<[2.187 11].[2.193 37]>
/sys/vane/ames/hoon:<[2.188 11].[2.193 37]>
/sys/vane/ames/hoon:<[2.189 13].[2.192 15]>
/sys/vane/ames/hoon:<[2.190 22].[2.190 63]>
/sys/vane/ames/hoon:<[2.226 9].[2.244 21]>
/sys/vane/ames/hoon:<[2.229 9].[2.244 21]>
/sys/vane/ames/hoon:<[2.229 24].[2.229 66]>
/sys/vane/ames/hoon:<[2.229 30].[2.229 45]>
/sys/vane/ames/hoon:<[2.098 7].[2.100 50]>
/sys/vane/ames/hoon:<[2.099 7].[2.100 50]>
[%dangling-bone ~binzod 452]
/sys/vane/ames/hoon:<[2.100 7].[2.100 50]>
crud: bail: %exit
ames: packet failed (6000 total)
```

**Comment by joemfb** [comment] 2022-06-04 02:33
Closing as duplicate of #2359

**Closed by joemfb** 2022-06-04 02:33 UTC
Labels: bug
