### ISSUE TITLE
Sometimes lose changes when autosynced desks are both mounted

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#370] opened 2015-07-15 22:44 UTC
For people with a tendency to mount everything, there can be a problem where a change made to an upstream desk (say, `%base`) gets autosynced to the downstream desk (say, `%home`) and then gets immediately reverted by unix sync, which is still awaking from its slumber.

**Comment by Fang-** [comment] 2018-03-02 17:58
Closing as duplicate of urbit/arvo#633.

**Closed by Fang-** 2018-03-02 17:58 UTC
Labels: %clay, difficulty medium, newunix, priority low

**Comment by ohAitch** [comment] 2018-03-02 21:02
uh, it seems reasonable to close new issues as duplicates of old ones and not the other way around, though I guess sometimes the new discussion has more detail?

**Comment by Fang-** [comment] 2018-03-02 21:05
This also seems like more of an urbit/arvo clay issue than an urbit/urbit one.
