### ISSUE TITLE
Spider causes excess use of resources, needs to be killed to recover ship functionality

### ISSUE THREAD

**Issue by HalifaxShadow** [urbit/urbit#4303] opened 2021-01-18 06:51 UTC
Hi, at approximately 0830 local time for reasons which I am not able to pinpoint my ship began to consume large amounts of resources on my vps.  At first I thought its failure to load and Gateway Timeout (error 504) was related to internet connectivity or potential blacklisting of my domain, but after troubleshooting various guesses I determined that the load on the VPS was way outside of the normal range.  I attempted to reset the ship and server to see if that solved the problem but it did not. 

Eventually, a user on urbit advised me that this sort of problem has been encountered before, and to try :spider|kill, which I ran and the ship recovered functionality as loads on the server went back to normal levels.

I have not restarted spider and I'm not sure if restarting it will cause the problem to recur.  I will experiment.  Here is a graph of utilization on me server so you can see what was happening.  The first drop was me resetting the machine.  The second drop became sustained after using :spider|kill.

I hope this helps identify and resolve an issue that may impact other users.

![Screenshot from 2021-01-18 10-57-09](https://user-images.githubusercontent.com/64690771/104881538-6d646b80-599c-11eb-9d2a-cf9ab4ae95ae.png)

**Comment by matildepark** [comment] 2021-01-18 06:52
Duplicate of #4211. We should probably step an intermediate fix up.

**Closed by matildepark** 2021-01-18 06:52 UTC

**Comment by HalifaxShadow** [comment] 2021-01-18 06:56
Thank you for the attention to this, @matildepark
