### ISSUE TITLE
Booting: Eth-tracker issue during boot makes connections to ~monrel ~samzod ~dopzod, etc impossible

### ISSUE THREAD

**Issue by maxwell-black** [urbit/urbit#2404] opened 2020-03-06 02:05 UTC
When trying to boot my Urbit, I get an eth-watcher failure similar to the one found in #2099 . However, during the boot the dojo command interface is inaccessible, instead  the chat-cli is what's running during boot, so I'm unable to enter in the fix found in #2099 Is there any reason the chat-cli is what's displayed rather than dojo during boot?

```
urbit 0.10.3
boot: home is /Users/maxwellblack/urbit-darwin-v0.10.3/mitlyr-biclys
loom: mapped 2048MB
lite: arvo formula 69dfe787
lite: core 31c5cfd7
lite: final state 31c5cfd7
boot: downloading pill https://bootstrap.urbit.org/urbit-v0.10.3.pill
boot: retrieving latest block
boot: retrieving ~mitlyr-biclys's public keys
boot: verifying keys
boot: getting sponsor
boot: retrieving galaxy table
boot: retrieving network domains
boot: retrieving keys for sponsor ~monrel
boot: retrieving keys for sponsor ~rel
loom: mapped 2048MB
boot: protected loom
live: logical boot
boot: installed 262 jets
work: play 1
boot: ship: ~mitlyr-biclys
work: (1)| boot
work: (2)| boot
work: (3)| boot
work: (4)| boot
work: (5)| boot
work: (5)| pill: 480dbadc
1-b
1-c (compiling compiler, wait a few minutes)
ride-parsing
ride-compiling
ride-compiled
1-d
1-e
ride-parsing
ride-compiling
ride-compiled
1-f
ride-parsing
ride-compiling
ride-compiled
1-g
%arvo-assembly
%arvo-assembled
work: (5)| core: 2572f150
[%tang /~zod/home/~2020.1.30..11.22.58..1f0b/sys/zuse ~nacmug-libsug]
arvo: metamorphosis
%hoon-load
[%vane %a /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/ames ~tabsyx-fidfer]
[%vane-parsed ~widdyn-fosseb]
[%vane-compiled ~labnet-tannex]
[%vane %b /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/behn ~sipsym-tidref]
[%vane-parsed ~lomlug-lardev]
[%vane-compiled ~pinwer-tintex]
[%vane %c /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/clay ~dastyc-holwyc]
[%vane-parsed ~sappyx-sovlun]
[%vane-compiled ~sartux-fodhex]
[%vane %d /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/dill ~pitlyr-dilmed]
[%vane-parsed ~hobfun-dovbep]
[%vane-compiled ~palmel-sabmer]
[%vane %e /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/eyre ~hilreg-maghul]
[%vane-parsed ~pacmud-mapbyt]
[%vane-compiled ~dospub-harfes]
[%vane %f /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/ford ~marlud-ribsef]
[%vane-parsed ~topmev-sovlen]
[%vane-compiled ~miprud-minset]
[%vane %g /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/gall ~roppec-mocdyl]
[%vane-parsed ~ramtep-lopdet]
[%vane-compiled ~winmus-fosber]
[%vane %i /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/iris ~sovden-nocryg]
[%vane-parsed ~narrel-saldec]
[%vane-compiled ~holfet-tanler]
[%vane %j /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/jael ~fosweb-ralryt]
[%vane-parsed ~lomben-rontev]
[%vane-compiled ~fonrem-nidten]
pier: boot complete
ames: live on 0
gall: not running %azimuth-tracker yet, got %poke
gall: not running %azimuth-tracker yet, got %watch
clay: committed initial filesystem (hoon)
http: live (insecure, public) on 8080
http: live (insecure, loopback) on 12321
clay: committed initial filesystem (all)
ames: metamorphosis
finding ship and desk from %base on ~mitlyr-biclys to %home
finding ship and desk from %kids on ~monrel to %base
finding ship and desk from %base on ~mitlyr-biclys to %kids
gall: not running %eth-watcher yet, got %watch
gall: not running %eth-watcher yet, got %poke
gall: not running %eth-watcher yet, got %poke
gall: not running %chat-store yet, got %watch
gall: not running %invite-store yet, got %poke
gall: not running %invite-store yet, got %watch
gall: not running %permission-store yet, got %watch
gall: not running %launch yet, got %poke
gall: not running %launch yet, got %poke
[~mitlyr-biclys, driving ~mitlyr-biclys]
activated app home/acme
activated app home/azimuth-tracker
activated app home/chat-cli
activated app home/chat-hook
activated app home/chat-store
activated app home/chat-view
activated app home/clock
activated app home/dojo
activated app home/eth-watcher
activated app home/goad
activated app home/group-hook
activated app home/group-store
activated app home/invite-hook
activated app home/invite-store
activated app home/invite-view
activated app home/launch
activated app home/lens
activated app home/permission-group-hook
activated app home/permission-hook
activated app home/permission-store
activated app home/ping
activated app home/publish
activated app home/soto
activated app home/spider
activated app home/weather
[linked to [p=~mitlyr-biclys q=%dojo]]
[linked to [p=~mitlyr-biclys q=%chat-cli]]
ames: czar rel.urbit.org: ip .35.247.119.159
activated sync from %base on ~mitlyr-biclys to %home
activated sync from %base on ~mitlyr-biclys to %kids
goad: recompiling all apps
[ %thread-not-started
  ~[
    \/~.eth-watcher--0v1so.hnhge.h5hvs.rbq9o.3fdml.t9hs6.bdu1r.154hg.dc5g7.38s\/
      nv.a6i5h.fnjlr.cdfvl.15ku0.e2p1n.g3s9a.j5eg7.l2r33.8e9cg.o5odu.dq6ti
    \/                                                                        \/
  ]
]
eth-watcher failed; will retry
%cancelled
; ~monrel not responding still trying
; ~rel not responding still trying
\/spider got sign for non-existent ~.eth-watcher--0v1so.hnhge.h5hvs.rbq9o.3fdm\/
  l.t9hs6.bdu1r.154hg.dc5g7.38snv.a6i5h.fnjlr.cdfvl.15ku0.e2p1n.g3s9a.j5eg7.l2
  r33.8e9cg.o5odu.dq6ti
\/                                                                            \/
sync succeeded from %base on ~mitlyr-biclys to %home
; ~rel is ok
sync succeeded from %base on ~mitlyr-biclys to %kids
\/ping: strange state [~rel ~ u=[rift=0 ship-state=[%waiting until=~2020.3.6..\/
  01.51.45..3fc6]]]
\/                                                                            \/
; ~rel not responding still trying
; ~rel is ok
~mitlyr-biclys:chat-cli/

```
<img width="567" alt="Screen Shot 2020-03-05 at 9 08 06 PM" src="https://user-images.githubusercontent.com/61848209/76043271-02957780-5f25-11ea-85d5-9f039becae36.png">

**Comment by maxwell-black** [comment] 2020-03-06 02:06
> When trying to boot my Urbit, I get an eth-watcher failure similar to the one found in #2099 . However, during the boot the dojo command interface is inaccessible, instead the chat-cli is what's running during boot, so I'm unable to enter in the fix found in #2009. Is there any reason the chat-cli is what's displayed rather than dojo during boot?
> 
> `urbit 0.10.3
> boot: home is /Users/maxwellblack/urbit-darwin-v0.10.3/mitlyr-biclys
> loom: mapped 2048MB
> lite: arvo formula 69dfe787
> lite: core 31c5cfd7
> lite: final state 31c5cfd7
> boot: downloading pill https://bootstrap.urbit.org/urbit-v0.10.3.pill
> boot: retrieving latest block
> boot: retrieving ~mitlyr-biclys's public keys
> boot: verifying keys
> boot: getting sponsor
> boot: retrieving galaxy table
> boot: retrieving network domains
> boot: retrieving keys for sponsor ~monrel
> boot: retrieving keys for sponsor ~rel
> loom: mapped 2048MB
> boot: protected loom
> live: logical boot
> boot: installed 262 jets
> work: play 1
> boot: ship: ~mitlyr-biclys
> work: (1)| boot
> work: (2)| boot
> work: (3)| boot
> work: (4)| boot
> work: (5)| boot
> work: (5)| pill: 480dbadc
> 1-b
> 1-c (compiling compiler, wait a few minutes)
> ride-parsing
> ride-compiling
> ride-compiled
> 1-d
> 1-e
> ride-parsing
> ride-compiling
> ride-compiled
> 1-f
> ride-parsing
> ride-compiling
> ride-compiled
> 1-g
> %arvo-assembly
> %arvo-assembled
> work: (5)| core: 2572f150
> [%tang /~zod/home/~2020.1.30..11.22.58..1f0b/sys/zuse ~nacmug-libsug]
> arvo: metamorphosis
> %hoon-load
> [%vane %a /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/ames ~tabsyx-fidfer]
> [%vane-parsed ~widdyn-fosseb]
> [%vane-compiled ~labnet-tannex]
> [%vane %b /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/behn ~sipsym-tidref]
> [%vane-parsed ~lomlug-lardev]
> [%vane-compiled ~pinwer-tintex]
> [%vane %c /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/clay ~dastyc-holwyc]
> [%vane-parsed ~sappyx-sovlun]
> [%vane-compiled ~sartux-fodhex]
> [%vane %d /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/dill ~pitlyr-dilmed]
> [%vane-parsed ~hobfun-dovbep]
> [%vane-compiled ~palmel-sabmer]
> [%vane %e /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/eyre ~hilreg-maghul]
> [%vane-parsed ~pacmud-mapbyt]
> [%vane-compiled ~dospub-harfes]
> [%vane %f /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/ford ~marlud-ribsef]
> [%vane-parsed ~topmev-sovlen]
> [%vane-compiled ~miprud-minset]
> [%vane %g /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/gall ~roppec-mocdyl]
> [%vane-parsed ~ramtep-lopdet]
> [%vane-compiled ~winmus-fosber]
> [%vane %i /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/iris ~sovden-nocryg]
> [%vane-parsed ~narrel-saldec]
> [%vane-compiled ~holfet-tanler]
> [%vane %j /~zod/home/~2020.1.30..11.22.58..1f0b/sys/vane/jael ~fosweb-ralryt]
> [%vane-parsed ~lomben-rontev]
> [%vane-compiled ~fonrem-nidten]
> pier: boot complete
> ames: live on 0
> gall: not running %azimuth-tracker yet, got %poke
> gall: not running %azimuth-tracker yet, got %watch
> clay: committed initial filesystem (hoon)
> http: live (insecure, public) on 8080
> http: live (insecure, loopback) on 12321
> clay: committed initial filesystem (all)
> ames: metamorphosis
> finding ship and desk from %base on ~mitlyr-biclys to %home
> finding ship and desk from %kids on ~monrel to %base
> finding ship and desk from %base on ~mitlyr-biclys to %kids
> gall: not running %eth-watcher yet, got %watch
> gall: not running %eth-watcher yet, got %poke
> gall: not running %eth-watcher yet, got %poke
> gall: not running %chat-store yet, got %watch
> gall: not running %invite-store yet, got %poke
> gall: not running %invite-store yet, got %watch
> gall: not running %permission-store yet, got %watch
> gall: not running %launch yet, got %poke
> gall: not running %launch yet, got %poke
> [~mitlyr-biclys, driving ~mitlyr-biclys]
> activated app home/acme
> activated app home/azimuth-tracker
> activated app home/chat-cli
> activated app home/chat-hook
> activated app home/chat-store
> activated app home/chat-view
> activated app home/clock
> activated app home/dojo
> activated app home/eth-watcher
> activated app home/goad
> activated app home/group-hook
> activated app home/group-store
> activated app home/invite-hook
> activated app home/invite-store
> activated app home/invite-view
> activated app home/launch
> activated app home/lens
> activated app home/permission-group-hook
> activated app home/permission-hook
> activated app home/permission-store
> activated app home/ping
> activated app home/publish
> activated app home/soto
> activated app home/spider
> activated app home/weather
> [linked to [p=~mitlyr-biclys q=%dojo]]
> [linked to [p=~mitlyr-biclys q=%chat-cli]]
> ames: czar rel.urbit.org: ip .35.247.119.159
> activated sync from %base on ~mitlyr-biclys to %home
> activated sync from %base on ~mitlyr-biclys to %kids
> goad: recompiling all apps
> [ %thread-not-started
> ~[ /~.eth-watcher--0v1so.hnhge.h5hvs.rbq9o.3fdml.t9hs6.bdu1r.154hg.dc5g7.38s/
> nv.a6i5h.fnjlr.cdfvl.15ku0.e2p1n.g3s9a.j5eg7.l2r33.8e9cg.o5odu.dq6ti
> / /
> ]
> ]
> eth-watcher failed; will retry
> %cancelled
> ; ~monrel not responding still trying
> ; ~rel not responding still trying
> /spider got sign for non-existent ~.eth-watcher--0v1so.hnhge.h5hvs.rbq9o.3fdm/
> l.t9hs6.bdu1r.154hg.dc5g7.38snv.a6i5h.fnjlr.cdfvl.15ku0.e2p1n.g3s9a.j5eg7.l2
> r33.8e9cg.o5odu.dq6ti
> / /
> sync succeeded from %base on ~mitlyr-biclys to %home
> ; ~rel is ok
> sync succeeded from %base on ~mitlyr-biclys to %kids
> /ping: strange state [~rel ~ u=[rift=0 ship-state=[%waiting until=~2020.3.6../
> 01.51.45..3fc6]]]
> / /
> ; ~rel not responding still trying
> ; ~rel is ok
> <img alt="Screen Shot 2020-03-05 at 9 08 06 PM" width="567" src="https://user-images.githubusercontent.com/61848209/76043271-02957780-5f25-11ea-85d5-9f039becae36.png">
> 
> ~mitlyr-biclys:chat-cli/`

**Comment by Fang-** [comment] 2020-03-06 14:35
> However, during the boot the dojo command interface is inaccessible, instead the chat-cli is what's running during boot

The cli app that first shows on-boot is not consistent for everyone because of... technical reasons.

Dojo should still have been booted, however, and you should be able to swirch to it (and back t chat-cli) by pressing ctrl-x.

**Comment by loganallenc** [comment] 2020-03-06 20:07
I'm having this same issue (but dojo works fine, just switch to it with ctrl+x)

**Comment by loganallenc** [comment] 2020-03-06 20:09
I'm also getting repeated crud: %hole event failed

**Comment by loganallenc** [comment] 2020-03-06 20:10
<img width="1277" alt="Screen Shot 2020-03-06 at 12 09 57 PM" src="https://user-images.githubusercontent.com/1377557/76119056-75ddce80-5fa3-11ea-8c6f-44c6c637229c.png">


Looks like it's crashing on an Ames packet

**Comment by loganallenc** [comment] 2020-03-06 20:10
@belisarius222 what's up here?

**Comment by loganallenc** [comment] 2020-03-06 20:11
It's not just crashing on packets from this person, it seems to be crashing on every ames packet it receives from anyone other than ~zod.

**Comment by loganallenc** [comment] 2020-03-06 20:21
<img width="758" alt="Screen Shot 2020-03-06 at 12 20 17 PM" src="https://user-images.githubusercontent.com/1377557/76119775-f6e99580-5fa4-11ea-8df4-fc381c692df6.png">

~samzod's console looks very similar

**Comment by loganallenc** [comment] 2020-03-06 20:24
`+azimuth-block` on ~samzod outputs 9.545.947, whereas the actual eth block height is 9.619.815

**Comment by loganallenc** [comment] 2020-03-06 20:26
Alright! ~dopzod finally connected.

**Comment by loganallenc** [comment] 2020-03-06 20:29
Alright, now I just got the whole backlog and %chat-cli is crashing a bunch.

**Comment by belisarius222** [comment] 2020-03-06 21:05
It sounds like the initial errors were caused by PKI propagation lag, which resolved itself.  What are the new :chat-cli crashes?  I don't know enough to say whether they're related.

—
~rovnys-ricfer
https://urbit.org

**Comment by loganallenc** [comment] 2020-03-06 21:35
I think the subscription between chat-cli and chat-store got overloaded with too many entries or something

**Comment by belisarius222** [comment] 2020-03-06 21:46
Maybe you know all this, but here's my understanding of how this works.

The publisher's Ames, if five or more %fact's back up locally without getting acked for ~s30, sends a %clog back to Gall.  Gall kills the subscription if it gets this.  Those messages will eventually go through, but the subscriber will need to resubscribe if it wants to restart the subscription.

Currently deployed chat and whatnot seem to handle this pretty well (I think that's what the %mailbox-kick printout is about), but maybe the new OS1 agents don't; I don't know much about that work.

—
~rovnys-ricfer
https://urbit.org

**Comment by belisarius222** [comment] 2020-03-06 21:47
If the agents in question are on the same ship, I don't think there's any kind of limit on number of messages.

—
~rovnys-ricfer
https://urbit.org

**Comment by loganallenc** [comment] 2020-03-06 22:18
That was all currently deployed code (not new OS1 agents), and the agents in question were on the same ship. It was strange to me too...

**Comment by belisarius222** [comment] 2020-03-06 22:21
Trace?

—
~rovnys-ricfer
https://urbit.org

**Comment by loganallenc** [comment] 2020-03-06 22:59
It's this one: https://github.com/urbit/urbit/issues/2404#issuecomment-595952289

**Comment by belisarius222** [comment] 2020-03-06 23:14
Hm, not sure that's related to Ford.  Seems like a parsing bug of some kind in :chat-cli, not a build problem.

**Comment by loganallenc** [comment] 2020-03-06 23:17
yah agreed... just real weird

**Comment by loganallenc** [comment] 2020-04-12 04:43
Fixed by Mark’s recent eth-watcher update.

**Closed** 2020-04-12 04:43 UTC
