### ISSUE TITLE
%behn timers sometimes get stuck

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#5747] opened 2022-05-05 19:20 UTC
%behn timers sometimes get stuck (don't ever fire for a particular agent), and then only fire when ship is ctrl+d'ed and started back up. cc: @dr-frmr @philipcmonk

**Comment by dr-frmr** [comment] 2022-05-05 20:05
Here is an example of this phenomenon occurring. This is on a fresh ~zod fakeship running on Ubuntu 20.04. My program creates a 20 second %behn timer, on loop, forever. But on my machine, this loop is frequently interrupted. It seems that if the ship does not receive external inputs, it forgets to fire the timer.
```
[%epoch 137 {~zod} 0x3fbd]
[%timer [%our %.y] 137 0 ~2022.5.5..19.19.31..ea96]
"producing a block size=1.889 at ~2022.5.5..19.19.31..ea97"
>   "uqbar-indexer: got block 137:0, update size 1.912"
[%epoch 138 {~zod} 0xba26]
[%timer [%our %.y] 138 0 ~2022.5.5..19.19.51..ea96]
"producing a block size=1.889 at ~2022.5.5..19.19.51..ea96"
>   "uqbar-indexer: got block 138:0, update size 1.912"
[%epoch 139 {~zod} 0x5210]
[%timer [%our %.y] 139 0 ~2022.5.5..19.20.11..ea96]
~zod:dojo> 
benj@min:~/fakeships$ ./urbit zod
~
urbit 1.8
boot: home is /home/benj/fakeships/zod
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/658.063.360
boot: installed 348 jets
vere: checking version compatibility
ames: live on 31337 (localhost only)
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12321
pier (14474): live
>>> "%ziggurat: skipping own block, we're late or have no chunks to package"
[%epoch 140 {~zod} 0xde5c]
[%timer [%our %.y] 140 0 ~2022.5.5..19.20.31..ea96]
>>> "%ziggurat: skipping own block, we're late or have no chunks to package"
[%epoch 141 {~zod} 0x1167]
[%timer [%our %.y] 141 0 ~2022.5.5..19.20.51..ea96]
>>> "%ziggurat: skipping own block, we're late or have no chunks to package"
[%epoch 142 {~zod} 0x701a]
[%timer [%our %.y] 142 0 ~2022.5.5..19.21.11..ea96]
>>> "%ziggurat: skipping own block, we're late or have no chunks to package"
[%epoch 143 {~zod} 0xf108]
[%timer [%our %.y] 143 0 ~2022.5.5..19.21.31..ea96]
>>> "%ziggurat: skipping own block, we're late or have no chunks to package"
[%epoch 144 {~zod} 0x7330]
```
Note that after I turn off the ship and turn it back on, it suddenly reacts to the last several minutes' worth of timers that should have been firing. There were no other external inputs to the ship, so I think something is occurring that puts the ship into some kind of stasis or something. Happy to provide more info about my environment if there's any questions there -- same bug occurs on my laptop, also Ubuntu.

**Comment by dr-frmr** [comment] 2022-05-05 22:33
BTW, any input to the ship in question triggers the cascade of missed timers. If I'm browsing from the web interface and a gall agent gets poked or scryed from, the same thing happens as when I quit the ship and reboot it.

**Comment by philipcmonk** [comment] 2022-05-05 23:31
Does this output somewhere show the amount of time between timer events?  If this is reproducible, it would be useful to turn on `|verb` and see it happen.

I've seen this happen very occasionally in the past, and last time I thought through it I believed it could happen when a timer event crashed if it wasn't properly handled, but it doesn't sound like that's the case here.  There should be a 10-minute "backstop" timer ( which should get it going again -- can you tell if that's being triggered?  That's not a solution, but it would give a hint as to where the problem is.

https://github.com/urbit/urbit/blob/1f76be7f4baa73dc51f382166fb15439292fd550/pkg/urbit/vere/io/behn.c#L67-L72

**Comment by philipcmonk** [comment] 2022-05-05 23:32
Also the output of `+timers` would be useful.  It's possible this issue only happens when that's the only timer set, and so we haven't noticed it on livenet, where typically there are several timers set at all times.

**Comment by dr-frmr** [comment] 2022-05-06 21:04
Yeah, I haven't seen this on livenet.

This is the output of +timers when the loop is running as it should. I can't get the output at the moment of failure because the dojo input triggers the "wake" and the timers immediately catch up.
```
~[
  [date=~2022.5.6..20.54.29..ac41 duct=~[/gall/use/ziggurat/0w2.mBcG1/~zod/timers/slot/3/0 /dill //term/1]]
  [date=~2022.5.6..20.55.25..5318 duct=~[/ames/pump/~dister-dozzod-dozzod/0 /ames]]
  [date=~2022.5.6..20.55.46..9cf7 duct=~[/ames/pump/~mister-dister-dozzod-dozzod/0 /ames]]
  [date=~2022.5.6..20.55.46..dfa4 duct=~[/ames/pump/~mister-dister-dozzod-dozzod/4 /ames]]
  [date=~2022.5.6..20.55.46..e9db duct=~[/ames/pump/~mister-dister-dozzod-dozzod/8 /ames]]
  [date=~2022.5.6..20.55.46..f058 duct=~[/ames/pump/~lander-dister-dozzod-dozzod/0 /ames]]
  [date=~2022.5.6..20.55.49..5399 duct=~[/gall/use/hark-system-hook/0w1.okxeb/~zod/check-lag /dill //term/1]]
]
```

I'll add another comment with the printout of the timers with |verb on, before it gets stuck and immediately after

**Comment by dr-frmr** [comment] 2022-05-06 21:20
Oddly enough the issue hasn't happened with |verb on for several hours. Usually it manifests itself within ~20 mins of starting up this timer loop. Also, the 10-minute backstop may indeed be working here. When I start up the app and leave it running overnight or something, I see the blocks of missed timers, but the loop has started itself afterwards. I'm guessing that's the backstop at work?

**Comment by philipcmonk** [comment] 2022-05-07 04:04
That sounds correct.  The ames pump timers are when we tried to communicate with those ships. 
 If the issue indeed has to do with having 0-1 timers set, then you might need to do it on a ship which hasn't tried to talk to any other ships.

If you're able to detect that it happened overnight, then leaving on |verb overnight could give useful information.  You'll obviously need large scrollback.

**Comment by dr-frmr** [comment] 2022-05-07 04:38
I don’t think it’s limited to when only 0-1 timers are active — these tests are all on freshly booted fake ships, which for me always have Ames pump timers from trying to hit ~mister-dister-dozzod-dozzod. So those pump timers to my knowledge are always active when the timer in my gall app stops triggering

**Comment by dr-frmr** [comment] 2022-05-10 22:53
This is an example of the bug occuring where @tacryt-socryp and I added some printouts in %behn. At the end, you can see a timer gets set for 22.39.00 but never receives a %wake. It seems to be an ames pump timer that's getting stuck.
```
[%epoch 87 {~zod} 0x6319]
>   "%ziggurat: slot 0 producer is ~zod"
[%timer [%our %.y] 87 0 ~2022.5.10..22.37.40..3e0b]
>>  [%wait p=~2022.5.10..22.37.40..3e0b]
>>  [%wake ~]
>   "%ziggurat: producing a block size=3.657 at ~2022.5.10..22.37.40..4146"
>   "uqbar-indexer: got block 87:0, update size 3.680"
[%epoch 88 {~zod} 0x236f]
>   "%ziggurat: slot 0 producer is ~zod"
[%timer [%our %.y] 88 0 ~2022.5.10..22.38.00..3e0b]
>>  [%wait p=~2022.5.10..22.38.00..3e0b]
>>  [%wake ~]
>   "%ziggurat: producing a block size=3.658 at ~2022.5.10..22.38.00..414a"
>   "uqbar-indexer: got block 88:0, update size 3.681"
[%epoch 89 {~zod} 0xe070]
>   "%ziggurat: slot 0 producer is ~zod"
[%timer [%our %.y] 89 0 ~2022.5.10..22.38.20..3e0b]
>>  [%wait p=~2022.5.10..22.38.20..3e0b]
>>  [%wake ~]
>   "%ziggurat: producing a block size=3.658 at ~2022.5.10..22.38.20..4149"
>   "uqbar-indexer: got block 89:0, update size 3.681"
[%epoch 90 {~zod} 0xe190]
>   "%ziggurat: slot 0 producer is ~zod"
[%timer [%our %.y] 90 0 ~2022.5.10..22.38.40..3e0b]
>>  [%wait p=~2022.5.10..22.38.40..3e0b]
>>  [%wake ~]
>   "%ziggurat: producing a block size=3.658 at ~2022.5.10..22.38.40..4043"
>   "uqbar-indexer: got block 90:0, update size 3.681"
[%epoch 91 {~zod} 0x59fd]
>   "%ziggurat: slot 0 producer is ~zod"
[%timer [%our %.y] 91 0 ~2022.5.10..22.39.00..3e0b]
>>  [%wait p=~2022.5.10..22.39.00..3e0b]
>>  [%wake ~]
>>  [%wait p=~2022.5.10..22.40.58..549b]
>>  [%wake ~]
>>  [%wait p=~2022.5.10..22.40.59..6d4d]
```

Here's the result of +timers after this, when it's stuck, and `now` right after.
```
> +timers
~[
  [date=~2022.5.10..22.38.59..aa82 duct=~[/ames/pump/~mister-dister-dozzod-dozzod/4 /ames]]
  [date=~2022.5.10..22.38.59..dddb duct=~[/ames/pump/~mister-dister-dozzod-dozzod/8 /ames]]
  [date=~2022.5.10..22.39.00..0f10 duct=~[/ames/pump/~lander-dister-dozzod-dozzod/0 /ames]]
  [date=~2022.5.10..22.39.00..3e0b duct=~[/gall/use/ziggurat/0w1.ByRRm/~zod/timers/slot/91/0 /dill //term/1]]
  [date=~2022.5.10..22.40.58..549b duct=~[/ames/pump/~dister-dozzod-dozzod/0 /ames]]
  [date=~2022.5.10..22.40.59..6d4d duct=~[/ames/pump/~mister-dister-dozzod-dozzod/0 /ames]]
  [date=~2022.5.10..22.42.27..2bd0 duct=~[/gall/use/hark-system-hook/0w1.okxeb/~zod/check-lag /dill //term/1]]
]
> now
~2022.5.10..22.43.47..57c2
```

**Comment by dr-frmr** [comment] 2022-05-10 22:53
So I was wrong about all other inputs to the ship triggering a catchup. It only "realized" that there were timers overdue after restarting the ship.

**Comment by dr-frmr** [comment] 2022-05-11 00:49
This gall agent is useful for testing. On my machine, this timer loop will occasionally fail to trigger, and the 10-minute backstop mentioned above will catch it. If I let it run for a few hours, it appears to happen once or twice per hour.

```
/+  default-agent, dbug, verb
|%
+$  card  card:agent:gall
--
::
%-  agent:dbug
%+  verb  |
^-  agent:gall
|_  =bowl:gall
+*  this  .
    def   ~(. (default-agent this %.n) bowl)
::
++  on-poke
  |=  [=mark =vase]
  ^-  (quip card _this)
  ~&  >>>  "Timer set at {<now.bowl>}"
  =+  (add now.bowl ~s30)
  :_  this
  [%pass /test-timer/(scot %da -) %arvo %b %wait -]~
::
++  on-arvo
  |=  [=wire =sign-arvo]
  ^-  (quip card _this)
  ?>  ?=([%test-timer @ ~] wire)
  =/  set-time  (slav %da i.t.wire)
  ~&  ?:  (gth now.bowl (add set-time ~s1))
        "Timer went off LATE at {<now.bowl>}"
      "Timer went off at {<now.bowl>}"
  =+  (add now.bowl ~s30)
  :_  this
  [%pass /test-timer/(scot %da -) %arvo %b %wait -]~
::
++  on-init   on-init:def
++  on-save   on-save:def
++  on-load   on-load:def
++  on-watch  on-watch:def
++  on-leave  on-leave:def
++  on-peek   on-peek:def
++  on-agent  on-agent:def
++  on-fail   on-fail:def
--
```

I'd definitely be interested to see if this happens on other machines. Still running on Ubuntu 20.04, Intel i5-7200U CPU.

**Comment by dr-frmr** [comment] 2022-05-20 20:01
Just want to add that this issue hasn't been seen yet in macOS. Only Linux

**Comment by ryjm** [comment] 2022-05-27 18:10
I found something strange when trying to debug this with verb:

```
["" %unix %hear /a/ames ~2022.5.27..17.50.21..9a39]
["|" %pass [%ames %b] [%rest /pump/~watryp-loplyd-dozzod-bacrys/173] ~[/ames]]
["" %unix %wake /b/behn ~2022.5.27..17.50.22..257c]
["" %unix %hear /a/ames ~2022.5.27..17.50.24..0a23]
["|" %pass [%ames %g] [%plea /bone/~ronnys-datwet/1] ~[//ames]]
["||" %pass [%gall %g] [[%deal [~ronnys-datwet ~mipber] %ping %raw-poke] /sys/req/~ronnys-datwet/ping] ~[/ames/bone/~ronnys-datwet/1 //ames]]
["|||" %pass [%gall %c] [%warp /nowhere] ~[/gall/sys/req/~ronnys-datwet/ping /ames/bone/~ronnys-datwet/1 //ames]]
["||||" %give %clay %writ i=/gall/nowhere t=~[/gall/sys/req/~ronnys-datwet/ping /ames/bone/~ronnys-datwet/1 //ames]]
["|||" %give %gall [%unto %poke-ack] i=/gall/sys/req/~ronnys-datwet/ping t=~[/ames/bone/~ronnys-datwet/1 //ames]]
["||||" %give %gall %done i=/ames/bone/~ronnys-datwet/1 t=~[//ames]]
["" %unix %wake /b/behn ~2022.5.27..17.50.35..9a81]
["|" %give %behn %wake i=/gall/use/hark-system-hook/0wkPpNP/~mipber/check-lag t=~[/dill //term/1]]
["||" %pass [%gall %b] [%wait /use/hark-system-hook/0wkPpNP/~mipber/check-lag] ~[/dill //term/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.39..c122]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653601453-3c1703 t=~[//http-server/0vi.li4oi/114/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653601453-3c1703] ~[//http-server/0vi.li4oi/114/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..65cb]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653596391-cce905 t=~[//http-server/0vi.li4oi/58/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653596391-cce905] ~[//http-server/0vi.li4oi/58/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..6a62]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..6dca]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653596393-d5f6a5 t=~[//http-server/0vi.li4oi/66/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653596393-d5f6a5] ~[//http-server/0vi.li4oi/66/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..738c]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653601447-ed6c8b t=~[//http-server/0vi.li4oi/89/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653601447-ed6c8b] ~[//http-server/0vi.li4oi/89/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..78a6]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653603293-460313 t=~[//http-server/0vi.li4oi/125/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653603293-460313] ~[//http-server/0vi.li4oi/125/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..7d3c]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653601449-8ee90f t=~[//http-server/0vi.li4oi/97/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653601449-8ee90f] ~[//http-server/0vi.li4oi/97/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..81c6]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653596383-f8db42 t=~[//http-server/0vi.li4oi/50/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653596383-f8db42] ~[//http-server/0vi.li4oi/50/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..86ac]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..891b]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653587503-1daceb t=~[//http-server/0vi.li4oi/17/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653587503-1daceb] ~[//http-server/0vi.li4oi/17/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..8dd0]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653587504-3319d0 t=~[//http-server/0vi.li4oi/22/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653587504-3319d0] ~[//http-server/0vi.li4oi/22/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..9298]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653587506-51d029 t=~[//http-server/0vi.li4oi/29/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653587506-51d029] ~[//http-server/0vi.li4oi/29/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..975f]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653587498-67bb52 t=~[//http-server/0vi.li4oi/9/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653587498-67bb52] ~[//http-server/0vi.li4oi/9/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..9c7d]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653670234-32b700 t=~[//http-server/0vi.li4oi/269/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653670234-32b700] ~[//http-server/0vi.li4oi/269/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..a16d]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653670236-bece21 t=~[//http-server/0vi.li4oi/277/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653670236-bece21] ~[//http-server/0vi.li4oi/277/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.40..a689]
["|" %give %behn %wake i=/eyre/channel/heartbeat/1653601451-99cf96 t=~[//http-server/0vi.li4oi/106/1]]
["||" %pass [%eyre %b] [%wait /channel/heartbeat/1653601451-99cf96] ~[//http-server/0vi.li4oi/106/1]]
["" %unix %hear /a/ames ~2022.5.27..17.50.43..3e4d]
["" %unix %crud //arvo ~2022.5.27..17.50.43..3e4d.0000.0000.0001]
%goof
["" %unix %wake /b/behn ~2022.5.27..17.50.43..86d7]
["" %unix %wake /b/behn ~2022.5.27..17.50.43..8976]
["|" %give %behn %wake i=/gall/use/ziggurat/0w3.NFr8o/~mipber/timers/slot/2.754/2 t=~[/dill //term/1]]
["" %unix %wake /b/behn ~2022.5.27..17.50.49..884d]
["|" %give %behn %wake i=/gall/use/ziggurat/0w3.NFr8o/~mipber/timers/slot/2.755/0 t=~[/dill //term/1]]
>   "%ziggurat: producing a block: height=3.124, size=3.875, at ~2022.5.27..17.50.49..884d"
>   "%ziggurat: slot 2 producer is ~ricmun-lasfer-hosted-fornet"
["||" %give %gall [%unto %fact] i=/gall/sys/req/~ricmun-lasfer-hosted-fornet/ziggurat t=~[/ames/bone/~ricmun-lasfer-hosted-fornet/121 //ames]]
["|||" %give %gall %boon i=/ames/bone/~ricmun-lasfer-hosted-fornet/121 t=~[//ames]]
["||||" %pass [%ames %b] [%wait /pump/~ricmun-lasfer-hosted-fornet/121] ~[/ames]]
["||" %give %gall [%unto %fact] i=/gall/sys/req/~watryp-loplyd-dozzod-bacrys/ziggurat t=~[/ames/bone/~watryp-loplyd-dozzod-bacrys/173 //ames]]
["|||" %give %gall %boon i=/ames/bone/~watryp-loplyd-dozzod-bacrys/173 t=~[//ames]]
["||||" %pass [%ames %b] [%wait /pump/~watryp-loplyd-dozzod-bacrys/173] ~[/ames]]
["||" %give %gall [%unto %fact] i=/gall/use/uqbar-indexer/0w3.NFr8o/out/~mipber/ziggurat/chain-update t=~[/dill //term/1]]
>   "uqbar-indexer: got block 2.755:0, update size 3.895"
["|||" %give %gall [%unto %fact] i=/gall/use/wallet/0w3.NFr8o/out/~mipber/uqbar-indexer/holder/0x2.4a1c.4643.b429.dc12.6f3b.03f3.f519.aebb.5439.08d3.e0bf.8fc3.cb52.b92c.9802.636e t=~[/dill //term/1]]
["||||" %give %gall [%unto %fact] i=/eyre/channel/subscription/1653670236-bece21/1/~mipber/wallet t=~[//http-server/0vi.li4oi/273/1]]
["|||||" %pass [%eyre %c] [%warp /conversion-cache/zig-wallet-update] ~[//http-server/0vi.li4oi/273/1]]
["||||||" %give %clay %writ i=/eyre/conversion-cache/zig-wallet-update t=~[//http-server/0vi.li4oi/273/1]]
["||" %give %gall [%unto %fact] i=/gall/use/sequencer/0w1.HcCx8/out/~mipber/ziggurat/sequencer/updates t=~[/dill //term/1]]
["" %unix %hear /a/ames ~2022.5.27..17.50.49..a6da]
["|" %pass [%ames %b] [%rest /pump/~watryp-loplyd-dozzod-bacrys/173] ~[/ames]]
["|" %pass [%ames %b] [%wait /pump/~watryp-loplyd-dozzod-bacrys/173] ~[/ames]]
["" %unix %hear /a/ames ~2022.5.27..17.50.49..a833]
["|" %pass [%ames %b] [%rest /pump/~watryp-loplyd-dozzod-bacrys/173] ~[/ames]]
```

Notice the `%goof` before a `%unix %wake` that doesn't seem to trigger anything.

**Comment by zalberico** [comment] 2022-06-15 16:41
@philipcmonk, @belisarius222 is going to reach out - this looks like a pretty serious bug we've hit a couple of times and probably want to assign someone to sooner rather than later.

**Comment by tacryt-socryp** [comment] 2022-06-29 17:39
Question: why is there not *one* 2 minute timer that handles all of the flows at once? Why do they each need their own timers? @belisarius222 @zalberico @Fang-

**Comment by zalberico** [comment] 2022-07-13 16:30
This has been running on the public pre-release moon without issue. We think this is good to go out more broadly. @Fang- to coordinate with @philipcmonk, also flagging this to @lukestiles for any comms that have to happen with UF prior to this going out.

**Comment by zalberico** [comment] 2022-07-13 18:46
Tweet went live here: https://twitter.com/zodisok/status/1547288432069685248

**Comment by joemfb** [comment] 2022-07-14 02:24
Not sure why github didn't auto close this -- in any case, the fix is live now.

**Closed by joemfb** 2022-07-14 02:24 UTC
Labels: bug, behn, vere
