### ISSUE TITLE
Eyre errors, %eyre-no-channel

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#3196] opened 2020-07-27 16:55 UTC
**Describe the bug**
I see regular stream of 

```
crud: %eyre-no-channel event failed
id='1595502659818-a9a43e'
```

in my scrollback

**To Reproduce**
Steps to reproduce the behaviour:
Not sure exactly, but I imagine it's due to something Landscape-related

**Expected behaviour**
Not seeing these errors

**System (please supply the following information, if relevant):**
 - OS: Ubuntu
 - Vere and Urbit OS versions: 10.7 / `jp5fi`

**Comment by matildepark** [comment] 2020-07-27 17:30
Still getting this, Galen? I think this was a side effect of an infinite loop we stumbled into propagating group updates on loop. It seems to have quieted on my ship.

— 
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment] 2020-07-27 17:32
Ah, I still see some. Sorry — hosted ships have a slight delay it seems.

**Comment by matildepark** [comment] 2020-07-27 18:36
I think you're right that this happens during use of Landscape. In particular this happens when I navigate to another chat — we send a request to mark the chat read every time we click on a chat and scroll down or up IIRC, and that seems to instigate this for me.

**Comment by tacryt-socryp** [comment] 2020-07-27 20:23
This occurs when a channel is sent a request from the JS but that channel does not exist or has already been cleaned up. The question here is: why is a nonexistent channel being sent requests? It doesn't cause any problems for this to occur, but we should start automatically establishing a new channel occasionally if we receive enough errors. Hmm... Will look into this behavior. Can't recreate on my ship.

**Comment by tacryt-socryp** [comment] 2020-07-27 22:32
Marking as not an issue, as it’s expected (and fine) behavior.

**Comment by galenwp** [comment] 2020-08-07 21:28
It's not really 'fine', since my console is unusable. It seems like this should either be able to be silenced, or shouldn't happen in the first place. Happy to show someone my pier, it happens constantly.

**Comment by joemfb** [comment] 2020-08-07 22:48
@tacryt-socryp, from reading the %eyre source, I think is the opposite of the situation you describe. The `%eyre-no-channel` message is produced in `+emit-event`, which is only ever called when processing a subscription update from `%gall`. In other words, this happens when %gall thinks %eyre is subscribed to it, but %eyre doesn't (no longer?) know(s) about that subscription.

#3248 is at least partly related.

**Comment by Fang-** [comment] 2020-08-08 10:32
> but %eyre doesn't (no longer?) know(s) about that subscription.

Yeah. The issue here seems to be that eyre forgot to clean up a gall subscription when it closed a channel.

I thought I'd "just like" write a fix for this. We should just close the subscription if the result is unexpected, right?  
But to do that we need the wire and app name. The wire we know, but the app name isn't available when we run into this (`%eyre-no-channel`) case.

For future cases we can still do that, by just including the app name in the wire from now on. This doesn't resolve the root cause (if if still exists) of eyre doing sloppy cleanup, but should help alleviate the symptoms at least.

I'm not sure how to fix this for existing cases though, I don't think there's a way to get at the app name. We of course don't have the relevant state anymore, and it's not in the duct... Best I got is telling gall to forget about all subscriptions with eyre's `/channel/subscription` wires, but that seems rather heavy-handed, doesn't it?

**Comment by tacryt-socryp** [comment] 2020-08-08 18:55
It doesn't seem heavy-handed to me. It's equivalent to "reset all web sessions", which seems like a useful debugging tool.

**Comment by galenwp** [comment] 2020-08-12 14:23
I just noticed this in a bug report from @jalehman, so I think I'm not the only one with this issue.

**Comment by matildepark** [comment] 2020-08-12 16:07
Logging people out once seems like a pretty small cost to fix an issue perpetually, @Fang-, unless I'm misunderstanding you.

**Comment by Fang-** [comment] 2020-08-12 16:23
It wouldn't log out, but rather just kill all open subscriptions.

The reason I say it's heavy-handed is that it fixes an _eyre_-side problem by making _gall_ try to figure out what subscriptions are eyre's (by looking at ducts, no less) and killing those. 

It's far from ideal, so I was holding out for a suggestion for a better solution. If there is none, I guess we'll have to bite the bullet on this though...

**Comment by matildepark** [comment] 2020-08-12 16:27
Have you tried following an inquiry to @eglaysher before going ahead?

**Comment by galenwp** [comment] 2020-08-14 03:44
What does it mean, at the user level, to kill all open subscriptions?

**Comment by Fang-** [comment] 2020-08-14 10:31
Your web ui will silently stop updating and you'll need to refresh to establish new ones.

Talked to @eglaysher briefly, we don't have anything better than the solution I proposed. I'll move forward with that next week.

**Comment by galenwp** [comment] 2020-08-14 16:46
I think I can live with that

**Comment by joemfb** [comment] 2020-08-14 17:51
To be clear: this is a bug, and the proposed solution is only a workaround. We'll need to track down the bug to stop subscriptions from being lost between %eyre and %gall.

**Comment by matildepark** [comment] 2020-08-14 17:53
I personally don't intend to close this when the workaround is merged; but I like to keep track of solutions and delegates in one issue as an informal timeline of work around a problem.

**Comment by galenwp** [comment] 2020-08-19 04:03
Did we get rid of `|knob`? I'd still really just like some way to quiet the console down — but maybe the real solution is just to figure out how to separate out the streams (i.e. errors, chat, etc) with king haskell.

**Comment by matildepark** [comment] 2020-08-19 04:05
`|knob` went away after 0.10.4 but I don’t recall what change prompted it.

— 
~haddef-sigwen
https://urbit.org

**Comment by joemfb** [comment] 2020-08-19 05:02
`|knob` still exists, and the `%eyre-no-channel` console printf goes through the relevant code-path in %dill. so `|knob %eyre-no-channel %hush` should work.

(In v0.10.4, %ames' error-notification events started using a new mechanism, which is not integrated with or related to the `|knob` filtering in %dill.)

**Comment by vvisigoth** [comment] 2020-08-19 19:53
FWIW I think @urcades just got a bunch of these in the console and his ship (hosted) 504'd. Correlation or causation?

**Comment by vvisigoth** [comment] 2020-08-20 15:45
@Fang- my hosted ship appears to have caught the same thing as @urcades a console completely full of these errors followed by a 504. In a hosted ship this is terminal. Did you write this work around?

**Comment by Fang-** [comment] 2020-08-20 17:35
Pretty wild that this would cause 504s... I'll put it in my list for next week, in any case.

**Comment by Fang-** [comment] 2021-09-22 19:36
Pretty sure this was fixed in #3387.

**Comment by zalberico** [comment] 2022-10-25 21:46
> @tacryt-socryp, from reading the %eyre source, I think is the opposite of the situation you describe. The `%eyre-no-channel` message is produced in `+emit-event`, which is only ever called when processing a subscription update from `%gall`. In other words, this happens when %gall thinks %eyre is subscribed to it, but %eyre doesn't (no longer?) know(s) about that subscription.

If I'm reading this thread properly (big if) then I think the gall request queue fix work may have resolved the issue described here? @Fang- @joemfb am I right about that? If so I think this can close, if not I'd probably rewrite this one to be clearer about what we need for it.

**Closed** 2022-11-03 17:22 UTC
Labels: bug

**Comment by Fang-** [comment] 2022-11-10 15:26
With #3387 released, we can tell if there's still an issue here by seeing if people get any `eyre: removing watch for non-existent channel` in their terminal output. If we're still seeing that, the underlying issue that was causing the symptom of "eyre fails to close subscriptions" is still there, and needs fixing.

**Comment by zalberico** [comment] 2022-11-10 17:39
Thanks - if a future person is reading this because they searched that error and ended up here, we can reopen this issue.
