### ISSUE TITLE
+* lustar shouldn't be variadic

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2186] opened 2020-01-23 23:14 UTC
Right now, you can create multiple "virtual arms" in a core with a single `+*` rune, like so.

```hoon
|%
+*  this  .
    parent  +>
++  real-arm  %foo
--
```

This is an unusual syntax for Hoon: variadic with no terminating `==`.  As far as I can tell, this has very little advantage compared to using multiple fixed-arity `+*` runes, and it has disadvantages of being unusual and also likely to cause the parser to give less understandable error messages.

I think the code above should look like this:
```hoon
|%
+*  this  .
+*  parent  +>
++  real-arm  %foo
--
```

**Comment by pilfer-pandex** [comment] 2020-01-24 00:53
This is located in the parser, right? I can’t say I have really any understanding of that component.

**Comment by joemfb** [comment] 2020-01-24 01:09
Do you have an example of confusing parser error messages caused by this?

For posterity, these were discussed in urbit/arvo#361 and added in urbit/arvo#365.

**Comment by pilfer-pandex** [comment] 2020-01-24 01:58
Thanks for the historical context Joe. Based on your test case in urbit/arvo#365, it seems like you intended the "jogging" syntax, no? Would love to hear your perspective on the design here.

I can't think of how parser errors can be made more confusing here, but that could be from a lack of understanding of the specific parser combinator system we have. From a purely grammatical perspective, the rule makes perfect sense, and there can be no ambiguity as to where this construct terminates (namely at the next + rune).

**Comment by ohAitch** [comment] 2020-01-24 02:04
Hah, I am reminded of an early version of hoon that didn't have ++ since
after all |% is perfectly unambiguous as just an alternating sequence of
pairs of arm names and definitions

As I said in the linked thread though, "fixed arity 2" is a lot less
complex to wrap a _brain_ around than "look ahead for a ++ or -- which you
proceed not to even consume". While ?- does exist, it both has an explicit
delimiter, and benefits from visual continuity with the expression being
matched on in a way that I don't see any parallels for in this case.

**Comment by belisarius222** [comment] 2020-01-24 02:26
I don't have an example of parsing errors from this being confusing; it's just my expectation based on what happens when I, say, forget a -- and get nonlocal parsing errors.

I agree with Anton that fixing the arity would primarily be to make it easier for people to understand. I don't like that this category of rune exists (variadic and unterminated), especially since this could just as easily be expressed with two sub-hoons (name and expression) just like other arms.

—
~rovnys-ricfer
https://urbit.org

**Comment by philipcmonk** [comment] 2020-01-24 07:05
I mean, it's not a rune, it's more like a comma, as in %=(foo a b, c d).

I wouldn't necessarily be opposed to a ++-like "tall-form comma" for ?-
(maybe even all king/queenside runes) if it can be done without being too
heavy. The best argument to be inconsistent is that ++ tends to happen more
in outer layers, where heavy syntax is beneficial, and the others happen in
inner layers, where it's nice to use lighter syntax since you can see the
whole expression. Of course, this is self-reinforcing! If cores had a
lighter syntax or %= a heavier, we'd probably use them differently.

**Comment by joemfb** [comment] 2020-01-28 20:28
The `+*` syntax is certainly a bit odd. But I'm not sure having a separate `+*` arms per-alias is an improvement. `+*` creates `=*` aliases in every arm of the core; it's really just a macro that transforms the other arms. It's not currently allowed at any position but the beginning of a battery. And I think be misleading to have a bunch of separate `+*` arms sprinkled throughout a battery. It's basically a header for the entire core. But again, it's certainly not the nicest syntax in hoon.

As for syntax errors, I would expect it to work exactly as well as any other syntax error in a battery. If an expression is not properly terminated/completed, the error should point to the next ++  arm separator or the -- core terminator. If multiple expressions are incorrectly combined, the error should point to the start of the subsequent expression. But I'd be interested in any counterexamples.

@philipcmonk, it's interesting to imagine a core rune with the jogging syntax of `%=`:

```
|%  name-of-core
  arm-1  formula-1
  arm-2  formula-2
--
```

`%brcn` already has a `(unit term)` for an internal core name, but I don't think anything sets it.

**Comment by philipcmonk** [comment] 2020-01-28 20:42
Indeed, I generally feel like the alias form should be used for small snippets of code only (or at least, I haven't seen a need for long aliases), so it seems overkill to allow them to be spread throughout the core, and you're not likely to be confused where they end.

I do think something similar to @pilfer-pandex's notation for |% is good: tall-form jogging as an option, and wide-form regular could be an option as well.

Of course, queenside is commonly criticized for making it hard to see the tag.  A possible synthesis of these that could help both jogging and core forms would be the following three forms:

Wide form:

```
|%(arm-1 formula-1, arm-2 formula-2)
```

Kingside:

```
|%
  arm-1  formula-1
  arm-2  formula-2
--
```

Neo-queenside:

```
|%
++  arm-1
  formula-1
++  arm-2
  formula-2
--
```

Example with `?-`:

```
?-  wing
++  arm-1
  formula-1
++  arm-2
  formula-2
--
```

Each of these could easily include an internal core name or `|_` argument if desired.  Now that there are other forms like `+$` we'd have to make sure those are easy to incorporate (I think irregular `,` would do it).

**Comment by ohAitch** [comment] 2020-01-29 05:38
Personally I feel fairly strongly that multi-arm cores should not have a
wide and definitely not a tall undelimited form, and somewhat strongly that
the ?- family should not have a delimited form. Irregular , is cute but
would break up the two-space conventions and also iirc conflicts with a.,.b
syntax.

Perhaps I just hate change?

Re: hard to see the tag, linter mandating fully outdented :: between any
tag and backdented queenside body would help a lot; this of course may
require me to finish forward-porting the linter :P

**Comment by joemfb** [comment] 2020-01-29 18:13
@ohAitch, I don't know about this linter. Is it online somewhere?

**Comment by ohAitch** [comment] 2020-01-30 05:50
you do not know about it bc it's not in a releasable state, most notably targeting 2018 hoon. Though I suppose this was my excuse three months ago when I pledged to work on that "soon", which has not really occurred, so I may as well link the [repo](https://github.com/jeffreykegler/hoonlint), [overview](https://metacpan.org/pod/distribution/MarpaX-Hoonlint/hoonlint), and [representative output](https://github.com/jeffreykegler/hoonlint/blob/3f9db2e/cpan/suppressions/aberration.suppressions).

<details><summary>Spoilered commentary</summary>

---
"output" is slightly fudged, `.suppressions` is technically an input format that says to skip / expect output error lines for a net `0` exit code in CI, mixed with `#` commentary about why the linter is at odds with the corpus. The corpus in question being a snapshot of `pkg/arvo` from late 2018, referenced by absolute line and column - not exactly a format robust to upstream changes. Tooling is necessary to translate "we want this tall-delimited segment to be at that different column" into actual patches moving it; without which "autofix" functionality the code is of limited utility anyway.

The commits will say "Jeffrey Kegler" who was the paid primary developer, with my input consisting largely of expressing my whims for what Right and Proper hoon indentation entails, and well, the funds. (Though a moderate part of the latter were in my moral opinion already earmarked for the furthering of the urbit mission, for reasons I won't get into)

---

</details>

And the project has certainly produced [whitespace documentation](https://github.com/urbit/urbit/files/4132264/whitespace.pdf) relevant to the current discussion! (To some recent PR reviews, as well)

**Comment by joemfb** [comment] 2020-01-30 17:58
Woah, thanks -- this is extensive! I've saved the PDF for review, which'll take some time ...

**Comment by ohAitch** [comment] 2020-01-30 18:00
It's provisional in a number of ways, but certainly coins some useful
terminology~

**Comment by klaperman** [comment] 2020-01-30 18:14
@belisarius222 , do you have any views on this?

**Comment by belisarius222** [comment] 2020-01-30 22:30
On what?

**Comment by belisarius222** [comment] 2020-01-30 22:32
Oh, on Joe's reply.  Writing up a response now ...

**Comment by belisarius222** [comment] 2020-01-30 22:46
I didn't know about the head-of-battery limitation, so I agree that we should enforce that syntactically -- although just stipulating that `+*` virtual arms must come before `++` real arms in the source would be clear and easy enough for me to be happy.

I think arm names being prefaced with `++` is great; it makes visual inspection faster and clearer, and it makes it easy to script searching through code with an editor.  I have 'g/' in Vim mapped to searching for arms, which helps a lot.  This is part of my objection to the current variadic `+*` syntax: it breaks this pattern.

I think adding a delimiter for tall-form `?-` and `?+` would also be an improvement, for the same reasons.  Not sure what digraph to use as a delimiter, although I do think ideally it would be a repeated character for consistency with `++`, `--`, and `==`.  Maybe `??`:
```hoon
?-  -.val
??  %0
  (return-result %success %call [type.u.slit-result p.val])
::
??  %1
  =/  blocked-paths=(list path)  ;;((list path) p.val)
  (blocked-paths-to-receipt %call blocked-paths)
::
??  %2
  (return-error [[%leaf "ford: %call execution failed:"] p.val])
==
```
Or, this is what it looks like with `:=` delimiters, which look good but might be confusing:
```hoon
?-  -.val
:=  %0
  (return-result %success %call [type.u.slit-result p.val])
::
:=  %1
  =/  blocked-paths=(list path)  ;;((list path) p.val)
  (blocked-paths-to-receipt %call blocked-paths)
::
:=  %2
  (return-error [[%leaf "ford: %call execution failed:"] p.val])
==
```

**Comment by belisarius222** [comment] 2020-01-31 00:20
In general, we want some extra delimiters that aren't strictly necessary.  I'd much rather have a Hoon syntax that's easier to read than one that has a mathematically minimal number of delimiters.  This applies to more than arm definitions; we don't strictly need commas in flat-form `?-`, `?+`, or `%=` expressions, but without commas those expressions would be much harder to read.

**Comment by ohAitch** [comment] 2020-01-31 00:30
My argument against delimiters on `?-` &c is basically: they kill kingside which is useful, unless they're optional which would be weird and inconsistent - and we already have the optional and useful and commonly enforced convention where multiline cases are delimited by blank comments.

also to nitpick, 

```
?-  -.val
??  %&
  (success-result p.val)
::
??  %|
  (abort >%error< ~)
==
```

is very wrong, you want

```
?-    -.val
??  %&
  (success-result p.val)
::
??  %|
  (abort >%error< ~)
==
```

**Comment by belisarius222** [comment] 2020-01-31 01:39
I could make the same argument for ++ in cores, except the current status is the opposite, which implies you do just hate change ;)

> My argument against delimiters on |% &c is basically: they kill kingside which is useful, unless they're optional which would be weird and inconsistent.  We could use the optional and useful and enforceable convention where multiline cases are delimited by blank comments.

I'm not strongly in favor of delimited ?-, but I am somewhat in favor of it.  Imagine how nice it would be to search for `??  %bake` and be able to jump immediately to patterns that look for that.  Plus, if you have a really long ?- with tags you're not familiar with, you could easily jump to the next case by searching for the delimiter.

—
~rovnys-ricfer
https://urbit.org

**Comment by ohAitch** [comment] 2020-01-31 01:54
I believe "cores are generally larger than switches, and could stand to
have more formality" is fairly uncontroversial. They even have formal
section separators!

Relatedly, that part of the discussion is rather moot given we have +* ++
+= +| etc - I can see going either way on e.g. "arms are individually wet"
vs "rune indicates whole core is wet", but it definitely shouldn't be
/modal/

**Comment by pilfer-pandex** [comment] 2020-01-31 02:13
Guys, although I’m in favor of more “bullet points” for jogging runes, I think it’s out of scope for the present discussion. Fair enough?

**Comment by pilfer-pandex** [comment] 2020-02-13 23:07
Alright, since there hasn't been subsequent discussion, I'll say now that I find joe's perspective here more compelling. The syntax is strange for multiple reasons, the complained-about one being only one of them. Given that this "lus rune" (which, as we have seen, is not really a lus rune after all) must occur at the head of a core, its abnormality makes more sense. So I'm going to mark this as wontfix for now.

As for the broader discussion on syntax that's occurred here, I think it's great and would like to resume it in the context of 140 later on.

**Closed by pilfer-pandex** 2020-02-13 23:07 UTC
Labels: hoon
