### ISSUE TITLE
bail:meme on a breach-peer

### ISSUE THREAD

**Issue by ryjm** [urbit/urbit#3116] opened 2020-07-09 15:07 UTC
```
---------------- playback complete----------------
ames: live on 0
eyre: canceling ~[//http-server/0v1v.t7684/2/2]
http: live (insecure, public) on 8081
http: live (insecure, loopback) on 12322
; ~simfur-ritwed not responding still trying
ames: czar zod.urbit.org: ip .35.247.119.159
ames: czar dev.urbit.org: ip .35.227.173.38
ames: czar pub.urbit.org: ip .35.230.48.78
ames: czar rel.urbit.org: ip .34.83.230.207
ames: czar feb.urbit.org: ip .34.82.25.47
ames: czar nus.urbit.org: ip .34.83.26.147
ames: czar ten.urbit.org: ip .104.196.239.18
ames: czar def.urbit.org: ip .35.230.109.40
ames: czar bus.urbit.org: ip .35.247.126.229
ames: czar nes.urbit.org: ip .35.247.80.48
ames: czar nem.urbit.org: ip .66.228.53.179
ames: czar lur.urbit.org: ip .35.233.250.88
ames: czar pem.urbit.org: ip .104.199.124.48
eth-watcher /azimuth-tracker timed out; will restart
; ~nolmeg-hodbyn not responding still trying
spider got sign for non-existent ~.eth-watcher--0v2f2.foifj.7f11f.muaka.dnc7n.qc4mr.b4ocd.ts1i7.js0k4.ijkh6.22svh.bqbjc.sjsf2.fa1p4.ktdj1.9c1bb.ilsgn.qchsj.7lfh4.5or8a.chkf1
; ~macpur-salpyx is ok
; ~dalten is ok
; ~nidsut-tomdun is ok
; ~novtel-holrem is ok
; ~lablud-master is ok
ames: breach peer [~littel-wolfur ~pilhul-hodnup]
~littel-wolfur:chat-cli? allocate: reclaim: half of 1124 entries
allocate: reclaim: half of 562 entries
allocate: reclaim: half of 281 entries
allocate: reclaim: half of 140 entries
allocate: reclaim: half of 70 entries
allocate: reclaim: half of 35 entries
allocate: reclaim: half of 17 entries
allocate: reclaim: half of 8 entries
allocate: reclaim: half of 4 entries
allocate: reclaim: half of 2 entries
allocate: reclaim: half of 1 entries
allocate: reclaim: memo cache: empty

bail: meme
bailing out
pier: work error: end of file
pier: work exit: status 0, signal 6
```

I also noticed ~littel-wolfur was sending thousands of `%plea`s to ~middev, and I have over 9000 behn timers. 

![image](https://user-images.githubusercontent.com/2065299/87057080-6cc07080-c1d4-11ea-90eb-ae0be3e7c53d.png)

**Comment by ryjm** [comment] 2020-07-09 16:50
managed to get through this by compacting ala #3099, but i think it's only a matter of time before it bail memes again, as the timers are still there.

**Comment by Fang-** [comment] 2020-07-09 17:02
9000+ timers is [a lot](https://www.cowcotland.com/images/news/2010/03/Its_over_9000.jpg), and it'd be good to find out why you have so many, but I doubt those are the root cause of your bail: meme.

Meme is strictly about memory. You were probably trying to process something big, and already had low amounts of memory available. You can run `|mass` and take a look at its output to get a sense of the current state of things. If the sweep is <1GB you should be fine for a fair amount of time still.

**Comment by ryjm** [comment] 2020-07-09 18:42
yeah so that's what i did at first, noticed my freelists were 450mb, compacted, and that fixed it. but i'm pretty sure everytime those timers go off, free lists goes up by a fair amount. 

i'll try to measure it the next time it happens.

**Comment by ryjm** [comment] 2020-07-09 18:52
nevermind, must've been something else. 

my sweep is pretty high though - 950MB.

**Comment by joemfb** [comment] 2020-12-17 20:05
Closing in favor of #4182.

**Closed by joemfb** 2020-12-17 20:05 UTC
Labels: bug
