### ISSUE TITLE
Some outbound HTTP requests that should 404 crash with SIGABRT instead.

### ISSUE THREAD

**Issue by keatondunsford** [urbit/urbit#838] opened 2017-04-17 19:20 UTC
1. If `+http://localhost:1111` is run in `:dojo`, without anything bound to TCP port 1111, `vere` will normally correctly yield a 404 `httr` response. However, it will occasionally core with:
  
```
Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type == UV_NAMED_PIPE), function uv___stream_fd, file src/unix/stream.c, line 1545.
```

In that case, after restarting the pier the 404 response will not come in until another request on the same host also receives a response.

2. If before making the request, the port is opened with `nc -l 1111`, but `nc` is `^C`ed immediately; and then `+http://localhost:1111` is run in `:dojo` as before, `vere` behaves similarly, but with more frequent `SIGABRT` `uv__stream_fd` crashes.

4. If `nc -l 1111` is kept open, and after another `+http://localhost:1111` in `:dojo` and `nc` receives the HTTP headers, entering `~\n` into `nc` will cause an `http: parse error`. This will also `404` in most cases, and occasionally cause the `uv__stream_fd` assert.

**Comment by juped** [comment] 2017-04-17 19:26
I should look into this.

**Comment by ohAitch** [comment] 2017-04-17 19:29
#784 is probably higher priority, since people keep coming on talk after hitting it, but yeah piers crashing is no good

**Comment by cgyarvin** [comment] 2017-06-16 20:12
Ray, did you ever look into this?  It may (or may not) be related to the womb crash we just experienced.

**Comment by juped** [comment] 2017-06-16 20:16
My ventures into cttp didn't turn up anything - but since it's SIGABRT it's probably a default error handler. I can look more.

**Comment by ohAitch** [comment] 2017-06-22 00:42
More reproductions:

4. If an http response is entered into `nc` before the request is received, presumably coming immediately upon the socket being opened.

5. Returning excess data, in one packet, by pasting a response of
    ```
    HTTP/1.1 404 fail
    content-length: 0
    
    
    
    ```
    after headers have been received. (note the trailing newlines)

**Comment by cgyarvin** [comment] 2017-06-22 01:02
Nice!

**Comment by Fang-** [comment] 2018-03-12 22:05
For the record, I've been hitting the assertion as well. Not just for error responses, but for 200's whose results get processed fine as well. Booting back up causes the processing to be re-done during playback. More than annoying.

**Comment by joemfb** [comment] 2018-09-25 17:18
resolved by http client rewrite

**Closed by joemfb** 2018-09-25 17:18 UTC
Labels: %eyre, bug, reproduction known
