### ISSUE TITLE
Crash on upgrade

### ISSUE THREAD

**Issue by gusmacaulay** [urbit/urbit#3398] opened 2020-08-28 01:52 UTC
I have ship which was running happily on v0.10.5 - but an OTA update from a month or two back seem to crash it and now it always crashes on startup after first upgrading everything.  Possibly failing to upgrade a 3rd party hackathon app 'rote', or perhaps coincidentally crashes immediately after upgrading that app.  Tried installing a later version of urbit v0.10.8 but same thing happened.

https://pastebin.com/EArAfh6u

**Comment by philipcmonk** [comment] 2020-08-28 04:58
You definitely want to run on v0.10.8.  It looks like you've got autocommit turned on, you should turn that if you can by running `|cancel-autocommit`.

@ryjm, do you remember what was causing the `gall: %rote scry failed` error before and how you fixed it?

**Comment by ryjm** [comment] 2020-08-28 05:57
this definitely sounds like the ford fusion upgrade problems, as i'm pretty sure rote was using the old launch syntax and for runes. lemme scrounge up the commits i used to fix srrs, they'll probably match up.

**Comment by ryjm** [comment] 2020-08-28 06:01
mark update · ryjm/srrs@9aea318
mark update · ryjm/srrs@9aea318
remove ford runes · ryjm/srrs@cdaecd2
remove ford · ryjm/srrs@13dcb5d

**Comment by ryjm** [comment] 2020-08-28 06:01
might give you a clue about what's going. would be good to see the stracktrace too

**Comment by ryjm** [comment] 2020-08-28 06:04
actually... just looked at the stack trace. i don't think i ever fixed my scry problems. srrs currently can't import files from a desk because of the way i'm reading from clay. it doesn't crash cause it's not part of on load, so maybe rote is trying to scry into clay the same way

**Comment by ryjm** [comment] 2020-08-28 06:10
'''++  import-from-file
  =<
  |=  px=path
  =/  pax=path  (welp our-beak px)
  =/  name  `@t`+<:(flop pax)
  =/  items
    %+  parse  name
    %-  of-wall:format
    =+  ark=.^(arch %cy pax)
    ?^  fil.ark
      =/  fyl  .^(noun %cx pax)
      =+  `(unit wain)`?@(fyl `(to-wain:format fyl) ((soft wain) fyl))
      ?^  -  (wain-to-tape u)  !!
    !!
  =/  filtered  (murn (need items) |*(a=(unit *) a))

  abet:(emit-action [%new-stack (string-to-symbol (trip name)) name (molt filtered) %none read=*rule:clay write=*rule:clay])
  |%
  ++  wain-to-tape  |=(a/wain (turn a |=(b/cord (trip b))))
  ++  parse
    |=  [stack-name=@tas =tape]
    |^  (rust tape parser)
    ++  parser
      %+  more  (just `@`10)
      %+  cook
        |=  a=wall
        ^-  (unit (pair @tas item))
        ?.  ?=({* * *} a)  ~
        =/  front  (crip i.a)
        =/  back  (crip i.t.a)
        =/  uid
          %-  string-to-symbol
          "{<(sham %srrs our.bol front eny.bol)>}"
        :-  ~
        :-  uid
        %-  create-item
        =/  act
        :*  %new-item
            our.bol
            our.bol
            stack-name
            uid
            `@tas`front
            [read=*rule:clay write=*rule:clay]
            `@t`front
            `@t`back
         ==
         `$>(%new-item action)`act
      (most (just `@`9) (star prn)) '''

here's how i do it (similar to cat). not sure if we're having the same issue but maybe it will help.

**Comment by philipcmonk** [comment] 2020-08-28 06:55
It looks like "gall: %foo scry failed" is saying that scrying the app out of clay failed -- ie the app failed to compile.  So runtime scry failures in the app won't cause an issue unless they happen in +on-load (and this isn't that)

**Comment by philipcmonk** [comment] 2020-08-28 06:56
@gusmacaulay My guess is that you need to get the most recent version of %srrs, from git if necessary, since it looks like maybe that's how you installed it in the first place.

**Comment by ryjm** [comment] 2020-08-28 17:59
(i think you mean %rote - not sure if it's been updated though)

**Comment by ryjm** [comment] 2020-08-28 18:19
there's still not way to stop and remove an app once it's been started, right?

**Comment by philipcmonk** [comment] 2020-08-28 19:55
Oh yeah, I was conflating %rote with %srrs.  Looks like %rote hasn't been updated for ford fusion.

@gusmacaulay If you don't care about the data in the %rote app, then you should replace app/rote.hoon with this dummy app: https://github.com/urbit/urbit/blob/d47cfdb57d190a40086989ac7c263d726eb7e35c/pkg/arvo/app/invite-view.hoon.  This will throw away its state and hopefully let you upgrade.

**Comment by gusmacaulay** [comment] 2020-08-28 23:20
Thanks to both for investigating this - @philipcmonk I tried replacing rote.hoon with the code you linked but same thing occurred.  Is copying it into my linux mounted desk sufficient? or do I need to get the file in some other way?

latest output in case subtle difference https://pastebin.com/eh8TFN6A

**Comment by philipcmonk** [comment] 2020-08-29 00:02
Ah, I see a prior issue.  It's not actually committing when you boot, it already did commit and somehow gall didn't molt (upgrade all apps).  So it's trying to molt now, and that's failing.  When molting fails, it's supposed to reject the commit, but that can't happen now.  I guess we would need to inject a raw `%into` event and hope gall correctly upgrades before molting.  I don't know if this is possible.  Our old upgrade process was really buggy, and our new one (Ford Fusion) prevents this sort of thing, but the issue is that you're in the middle of the upgrade from the old to the new, and that handoff went wrong.

Sorry, but your best bet is a personal breach.  If you had data you care about that's not in your unix mount point, it's possible you could recover it, but it would take some time (basically you'd replay the event log up to 1000 events ago and then run it --dry-run mode).

**Comment by joemfb** [comment] 2020-12-10 19:36
Closing as obsolete (previous era, ford-fusion OTA).

**Closed by joemfb** 2020-12-10 19:36 UTC
Labels: bug
