### ISSUE TITLE
Chat: Inline sigil viewer is hidden behind chat input

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit#4205] opened 2020-12-28 17:50 UTC
**Describe the bug**
When trying to click on a user to view the expanded sigil menu, it is hidden behind the chat input box when it is close to the bottom of the screen. This is especially bad when accessing the menu from an inline mention.

The bug stops the user from being able to click the 'Send Message' button.

**To Reproduce**
1. Go to any chat
2. Send a message (optionally with a mention)
3. Try to click on the user profile or mention

**Expected behavior**
I expect the sigil viewer menu to popup in front of the chat input box.

**Screenshots**
Baseline
![Baseline](https://i.imgur.com/mUFiyCL.png)

Profile
![Profile](https://i.imgur.com/DIW4nmb.png)

Mention
![Mention](https://i.imgur.com/Bco227l.png)

[Imgur Album](https://imgur.com/a/yfhKk93)

Screenshots were taken using the Brave Browser

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Bug is present on Brave v1.9.72 and Firefox 84.0
 - Base hash: `74m9v`

**Additional context**
No additional context.

Apologies if this is a known issue.

**Comment by matildepark** [comment] 2021-01-04 19:55
Duplicate of #3640.

**Closed by matildepark** 2021-01-04 19:55 UTC
Labels: landscape
