### ISSUE TITLE
'Writers must be in group' when I'm in the group

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#4122] opened 2020-12-10 21:57 UTC
**Describe the bug**
When trying to create a notebook in a group I'm a member in, I hit an error restricting writers

**To Reproduce**
1. Create a notebook in a group
2. Make yourself the only writer

**Expected behavior**
Being able to create a notebook with myself as the sole writer.

**Screenshots**
<img width="420" alt="Screen Shot 2020-12-10 at 1 55 57 PM" src="https://user-images.githubusercontent.com/1467211/101834759-9bc66f80-3aef-11eb-9b36-0772248b7693.png">

**Comment by matildepark** [comment] 2020-12-10 21:58
This is a bug with ship search returning sig'd patps. I patched in #4117.

**Comment by galenwp** [comment] 2020-12-10 22:24
thanks!

**Comment by matildepark** [comment] 2020-12-11 01:01
Duplicate of #4096.

**Closed by matildepark** 2020-12-11 01:01 UTC
Labels: landscape
