### ISSUE TITLE
webchat freezes/crashes browser when loading huge scrollback

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2908] opened 2020-05-19 19:15 UTC
**Describe the bug**
Trying to display a channel with 20k unread messages makes the browser slow to a crawl and never get out.

**To Reproduce**
1. Join a popular channel
2. Don't view it for a while
3. Try to view it

**Expected behavior**
It to load only the handful of messages around the last-read marker, and load more recent ones on scroll-down.

Alternatively, to not auto-upscroll to the last-read marker if there are >1k (or something) unread messages.

**Comment by joemfb** [comment] 2020-05-19 19:22
Another option would be to paginate both forward and backward above some threshold.

**Comment by matildepark** [comment] 2020-05-19 20:22
> Alternatively, to not auto-upscroll to the last-read marker if there are >1k (or something) unread messages.

FWIW this is what other chat clients do. I can look into this ...

**Comment by ohAitch** [comment] 2020-05-19 20:31
"throw away scroll position unpredictably" probably not the play here, you want a prominent "scroll to bottom button" for the option but mostly like need to never mount 50k DOM nodes

**Comment by loganallenc** [comment] 2020-05-19 21:52
> Another option would be to paginate both forward and backward above some threshold.

I believe we may do this already unless the implementation changed.

**Comment by belisarius222** [comment] 2020-05-20 05:58
~rovnys-ricfer has run out of loom, partially due to Eyre's channels using over 140MB, which doubled to 280MB after a process restart.  @joemfb's ship just ran out of memory too, with 800MB in Eyre.  I wonder if big messages from Urbit to the web client on reload could cause unfinished HTTP responses to build up in Eyre?

For the past week or so, trying to load urbit-help would try to load tens of thousands of messages most times I clicked on it, which would often kill the browser tab.  If all those messages were enqueued from Gall to Eyre at once and they built up per channel, maybe that would explain these bail:meme's.

**Comment by joemfb** [comment] 2020-05-20 17:34
I waited out the `~h12` channel timeout, restarted my ship, and %eyre is now using 24 bytes for channels. It's nice that that kind of recovery is possible, but this space leak in %eyre is still very concerning -- a little more memory consumption and my ship wouldn't have been able to boot up and process timers ...

It does look like chat message loading is paginated, so I assume the problem is that the frontend makes lots of paginated requests to load the whole backlog.

**Comment by joemfb** [comment] 2020-05-20 17:46
And of course, now I have > 800MB in free lists, which is its own kind of reward ...

**Comment by loganallenc** [comment] 2020-05-20 18:04
I believe the problem is that in many cases messages are replicated and sent to all of the open channels. Could we do de-dupe nouns like we do in ames?

**Comment by joemfb** [comment] 2020-05-20 18:12
There are two problems (at least ;)): %eyre has a (time-bounded) space leak, and the chat UI apparently loads arbitrary amounts of backlog.

The first would be mitigated by deduplication (and/or lazy serialization) and a shorter timeout (The feature also just might not be worth the risk at this stage).

The second would appear to require new UI pagination (as opposed to just API pagination) -- the chat web interface should only render a slice of up to some N messages, and "infinitely-scroll" forward and back. The second also appears to be exacerbated by the existing issues with unread message counts; at least, that's my best guess as to why `urbit-help` was eagerly loading so much backlog on my ship.

**Comment by belisarius222** [comment] 2020-05-20 19:45
Yeah, urbit-help kept jumping back in time when i loaded the page. Often I only had a few unread messages and my scroll position was at the bottom of the page, but for some reason next time I tried to load it, it would scroll me up by thousands of messages.

If it were only loading the actually unread messages, I suspect the Eyre space leak wouldn't be a problem.

—
~rovnys-ricfer
https://urbit.org

**Comment by Fang-** [comment] 2020-05-22 19:16
Temporary workaround for those getting bitten by this: you can run the following in dojo to clear the unread marker off any chat. (Of course replacing the path there with whatever chat is giving you trouble.)

```hoon
:chat-store &chat-action [%read /~/~dopzod/urbit-help]
```

**Comment by matildepark** [comment] 2020-07-24 20:30
Fixed by #3023.

**Closed by matildepark** 2020-07-24 20:30 UTC
Labels: landscape
