### ISSUE TITLE
Invalid pattern-match on a core hangs urbit

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#866] opened 2017-06-27 22:38 UTC
```
~sathex_solref:dojo> |.(?-(. $-(* *) %a, * %b))
bail: fail

bail: 3
<spins until interrupted>
```
Expected: `%fish-core` or somesuch
Expected by @cgyarvin, while reading the compiler: success, with a nock `[0 0]` emitted to crash at runtime

**Comment by joemfb** [comment] 2018-09-28 04:46
Unable to reproduce on `release-candidate`:

```
> |.(?-(. $-(* *) %a, * %b))
/~zod/home/git-c31bcb95e6/sys/vane/ford:<[4.807 18].[4.807 59]>
fish-core
ford: %slim failed: 
ford: %ride failed to compute type:
```

**Comment by jtobin** [comment] 2019-06-20 00:33
(Closing, as I get comparable output to @joemfb.)

**Closed by jtobin** 2019-06-20 00:33 UTC
Labels: bug, type system
