### ISSUE TITLE
Incorrect default behavior in :begin

### ISSUE THREAD

**Issue by othercriteria** [urbit/urbit#227] opened 2014-12-19 23:44 UTC
On the %lord (and presumably the %lady) paths through :begin-ing a destroyer, the "white" default for banner also appears as the default for first name. @cgyarvin pins this on "sloppy default handling in the new terminal infrastructure".

(behavior as of commit a9d8af4ef8829ab0f208d933061d60c18901eaf7)

**Comment by chc4** [comment] 2015-05-17 05:21
This should be fixed. `:begin` is now completely bare-bones, with it just asking for your name and ticket now (although it would be nice to have aliases back...)

I'm not sure if new %dill actually fixed the root cause, although it might. The prompt still isn't correctly updated, but default input should be updated...

**Comment by galenwp** [comment] 2015-05-17 18:30
yeah, `:begin` has been totally retooled. worth looking at anything tagged dojo — those are all things that would have changed after dojo was merged in.

**Closed** 2015-05-17 18:31 UTC
Labels: dojo
