### ISSUE TITLE
Strange TLS errors when running urbit-king

### ISSUE THREAD

**Issue by ryjm** [urbit/urbit#4613] opened 2021-03-16 00:02 UTC
**Describe the bug**
When running urbit-king, ship spits out strange, serpent-like messages. Posting on behalf of ~sigryn-habrex.

sigryn-habrex: well this appears to be someone spamming my https for TLS weaknesses
sigryn-habrex: i like how it mangles the hell out of the messages though
littel-wolfur: yeah some slytherin shit going on there
sigryn-habrex: who among us hasn't experienced a HandshaHHHkaaaennnFdddasssihhhlaaaekkkdeee FFF(aaaEiiirlllreeeodddr

**Expected behaviour**
No messages from the deep.

**Screenshots**
![](https://static-sigryn-habrex.nyc3.digitaloceanspaces.com/sigryn-habrex/2021.3.15..21.03.07-Screen%20Shot%202021-03-15%20at%205%2C02%2C58%20PM.png)

**System (please supply the following information, if relevant):**
- urbit-king 1.2

**Additional context**
ship URL was shared on UC

**Comment by philipcmonk** [comment] 2021-03-16 00:05
I've also experienced this, though I don't have any more info.  I too use https.

**Comment by pilfer-pandex** [comment] 2021-03-16 04:05
That's pretty funny. The reason you're seeing interlacing like that is that
the standard haskell logger we use, RIO.Logger, just writes to the
underlying handle, without thread-safing it in any way. When I figured this
out last year (by reading the logger code, and, ultimately, the internals
of the GHC file handle implementation, just to be sure), I immediately
asked @benjamin-tlon about it, and he said "Yeah, that's the case. I've
implemented locking loggers in Haskell before in the past and they're
difficult and have performance tradeoffs, which is why snoyberg probably
didn't try in RIO. I think it's best to just keep it like this."
Accordingly, I haven't changed it.

Now as you know, each request to a warp server spawns a new (Haskell,
green) thread. So if you have two inbound invalid requests, it's quite
likely, based on the runtime's thread fairness algorithm, you'll get a
hhaakkeeFFaaiilleedd, or some variant thereof.

Here are some action items:
- actually figure out what causes a "handshake failed" (can you guys
confirm that you weren't trying to make legit requests? are you like on a
cloud provider or something, getting pummeled by roving gangs of bandits?)
- figure out why these get printed to stderr, rather than logged at a lower
priority, if this is an ordinary occurrence for cloudy ships, and change
that (you guys aren't running with --stderr, are you?)
- actually bite the bullet and investigate thread-safing the logger. The
implementation itself will not be difficult (at least for the naive version
of using a lock; if you want a threadlocal queue which blah blah blah, okay
I guess), but after the scaremongering I was subject to, I'll want to
investigate different approaches online, and do some profiling to compare
performance vs null.

(Also what font is that in the screenshot?)

**Comment by philipcmonk** [comment] 2021-03-16 04:14
> can you guys confirm that you weren't trying to make legit requests?

I can confirm that refreshing the page doesn't generate this, and that going to 443 on http prints only `InsecureConnectionDenied` in the console (which probably should also be logged instead of printed).  I haven't seen the "handshake failed" error happen in real time, so I don't know whether that's in response to one of my requests.

> are you like on a cloud provider or something, getting pummeled by roving gangs of bandits?

Yes, so probably.  Another error I get is `HandshakeFailed (Error_Protocol ("no cipher in common with the client",True,HandshakeFailure))`.

> you guys aren't running with --stderr, are you?

I am not.

**Comment by pilfer-pandex** [comment] 2021-03-22 00:22
@philipcmonk, how do I issue a %set-config effect from eyre with dummy tls info just to get the https server running?

**Comment by pilfer-pandex** [comment] 2021-03-22 01:32
Addressed in #4616. We move from the default behavior of printing the exception to stderr, to logging it, with more context. This means you won't see it on the screen unless you run the king with `stderr`, but doesn't address the interlacing issue, as discussed.

**Comment by joemfb** [comment] 2021-03-22 16:22
You can put a certificate at `/=home=/acme/cert/pem`, and the associated private key in `/=home=/acme/privkey/pem`
and then run `:acme %install-from-clay` (see urbit/arvo#1151).

**Comment by joemfb** [comment] 2022-06-04 02:15
King haskell is deprecated

**Closed by joemfb** 2022-06-04 02:15 UTC
Labels: bug, king-haskell
