### ISSUE TITLE
Confusing UX: paths and kiln commands

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#566] opened 2015-11-19 01:14 UTC
`%` should print out as a path: `/~fintud-macrep/home/~2015.11.13..02.24.52..7bed` rather than `[~.~fintud-macrep ~.home ~.~2015.11.13..02.24.52..7bed ~]`.

Common mistakes should have explicit error messages.  For examples, `+ls` should suggest you try `+ls %`, `=% /=examples=` should suggest `=% /=examples`, and `|mount /=examples` should suggest `|mount /=examples=`.

`|merge` should print out "starting merge..." to let the user know we're merging in the background.

On `%init` merge, mention that the new desk is not mounted tell the user how to mount it.

`|mount` of nonexistent desk should either give a readable error or succeed and tell the user it doesn't exist yet.

**Comment by max19** [comment] 2015-11-19 17:20
`+ls` ought to just default to `+ls %`

**Comment by chc4** [comment] 2015-11-19 18:00
The problem is I don't think it's possible for `+ls` to default to `%` like that...
Although it does have access to the current path through the `bec` member of the sample, we don't allow `arg` to have default values. Even if the sample in `+ls` was `[^ [path=(unit path) ~] ~]` it would type-fail due to args being a list for some reason.
There's `opt` for that, but it has a different syntax for calling - it would need to be `+ls =path %` or something for the non-default cause, which isn't ideal.

**Comment by juped** [comment] 2015-11-19 18:07
No, it'll work just fine, there's plenty of generators with optional arguments, you just need to specify the type in a fancy way. `opt` is silly and I don't understand why it exists - some doc claims it's an environment-variable-like feature, but it isn't actually in practice.

I was under the impression that that beak was the beak to the *generator*'s working desk, though. It's not a full path, after all, just a beak...

**Comment by chc4** [comment] 2015-11-19 18:34
Hm, it might be the working desk. Changing directories is currently broken, so I can't really test to see how it works, but if it is that's another problems since then the generator has no way of knowing the current path.

Are there any examples of generators with optional args? I don't see any in /gen. I suppose you could have arg=(list ,@) and check if it has entries...

**Comment by juped** [comment] 2015-11-19 18:37
Just stick in an explicit 0 for the case when changing directories for now. A simple fork of the different types you accept will work just fine, there's some examples of that in hood, for example.

**Comment by cgyarvin** [comment] 2015-11-19 19:00
+ls without an argument definitely doesn't work, because we made a design
decision not to pass the dojo environment to generators.  This connection
has been a source of a lot of cruft in Unix.

Using 0 for the case should work fine, or omit the case and 0 will be
added.  Sorry, still rethinking this a bit.

**Comment by juped** [comment] 2015-11-19 19:03
And yet there is an "environment variable" affordance in the type, but since there's no environment variables, it's just a way to make your syntax extra weird for fun.

**Comment by cgyarvin** [comment] 2015-11-19 19:05
That's not an environment variable, those are option flags for the
generators.  So that on the command line you can have both ordered and
keyword arguments.

**Comment by ohAitch** [comment] 2015-11-19 20:21
If you look at `gen/hood/merge`, for example, one of the less fancy bits is an `opt` of `gem=%auto`. This can be overridden with e.g. `|merge foo bar, =gem %that`; though if I were writing the code today, I'd keep it as a positional argument, `, =` seems like something you'd only want for *infrequently* used optional arguments.
(Another thing I would like to do eventually is make merge/sync have "unixy" order of `|merge from to`, and possibly deprecate the asymmetrical `desk ship desk` form, but these would require considerable care in communicating the breaking syntax change in release notes to everyone)

**Comment by juped** [comment] 2015-11-19 20:27
The precedent in e.g. git is actually also `merge [to] [from]`, though that's long been deprecated in favor of only merging to HEAD.

**Comment by juped** [comment] 2015-11-19 20:29
(In theory, we could merge to `q.bec`.)

**Comment by philipcmonk** [comment] 2015-11-19 20:30
That wouldn't work when merging to a new desk -- the |merge command
wouldn't exist yet.

**Comment by chc4** [comment] 2015-11-19 20:30
If the remote desk being merged was a beak (/~zod/kids= or whatever) it would make the order obvious without having to second guess to or from. I still have to pause a second when I create a symlink, which we definitely don't want.

**Comment by ohAitch** [comment] 2015-11-19 20:32
*would like to avoid having both `|merge from to` and `|merge to from`
sometimes both do the same thing*

**Comment by philipcmonk** [comment] 2015-11-19 20:35
In truth, the remote desk should be a full beak.  Most of the machinery for
version-specific merging exists, and is tested.  There's a `=.  cas  [%da
now]` line in kiln that locks the foreign desk to the present.  This could
come from the command line.

That doesn't work for `|sync`, of course.

**Comment by ohAitch** [comment] 2015-11-19 20:36
Correct behavior in sync is probably "did you mean merge" yeah.

**Closed** 2018-01-13 14:09 UTC
Labels: confusing
