### ISSUE TITLE
Chat: doubly-sent messages rendered multiple times

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2863] opened 2020-05-06 15:23 UTC
I experienced this just now, on latest ota, and it sorta persisted across refresh. All other "duplicate message rendering" issues are closed, and don't quite seem to match this.

The context in which this happened was:

- Chat didn't stick to bottom of scroll even though new messages came in, had to manually scroll down to see this.
- Other party complained about general internet connectivity issues. (#2145 relevant?)

The behavior initially looked like this:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/3829764/81192935-1871f800-8fbb-11ea-878a-5fc05a8c78c5.png">

On refresh, it renders the offending message _twice_, hinting at it being stored in the store twice. Looking at the initial updates in browser console, the message is indeed there twice: same uuid, different timestamp.

Subsequent updates to the message log (such as receiving or sending a message) then cause it to be rendered additional times:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/3829764/81193475-b9f94980-8fbb-11ea-8650-bab5795a5f33.png">

Maybe rendering logic does something with uuids that breaks if they're not unique, or something along those lines? There's no warnings in the browser console, in any case...

**Comment by liam-fitzgerald** [comment] 2020-07-14 01:03
This is pretty usual react behaviour around duplicate keys. We can either 
a) discard uuids as keys and use the index of the array until graph-store lands. This will cause minor perf issues because react it impairs react's diffing algorithm. 
b) Dedupe messages JS-side
c) do nothing until graph-store lands, which will fix this.

**Comment by matildepark** [comment] 2020-07-24 20:33
@Fang- #3122 included a potential fix for this — curious if this persists at all, even though it's hard to repro.

**Comment by Fang-** [comment] 2020-07-24 20:44
I did actually see this just today. I'd take a screenshot, but the chat it happened in also suffers from weird scrollback loading, so I can't get web to actually load the offending message now.

Will try to remember to report back when I encounter it again!

**Comment by matildepark** [comment] 2020-08-31 20:07
ping @Fang- any reproductions? close if not

**Comment by Fang-** [comment] 2020-08-31 20:14
Still an issue. See this example from the movie club management chat.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/3829764/91764208-2df8d680-ebd7-11ea-8446-ba5ae6f5fbf2.png">

**Comment by matildepark** [comment] 2020-12-11 08:18
Fixed in #4058.

**Closed by matildepark** 2020-12-11 08:18 UTC
Labels: chat, landscape
