### ISSUE TITLE
New OTA failure: gall: failed to build agent %eyre

### ISSUE THREAD

**Issue by jalehman** [urbit/urbit#5273] opened 2021-09-30 15:06 UTC
I've got a new one. Somewhat resembles #5270, but seems different. Ideas?

```
gall: %notify dozing, got %fact
...
gall: %notify dozing, got %fact
gall: %notify dozing, got %fact
gall: reviving %hark-group-hook
gall: installing %hark-invite-hook
gall: reviving %invite-hook
gall: installing %invite-view
gall: reviving %launch
gall: reviving %metadata-hook
gall: reviving %metadata-pull-hook
gall: reviving %metadata-push-hook
gall: reviving %notify
out=[acked=%.y path=/updates]
subscribe wire not unique
%notify
/hark
[p=~wolref-podlex q=%hark-store]
error in %notify
%watch-not-unique
! subscribe wire not unique
! %notify
! /hark
! [p=~wolref-podlex q=%hark-store]
gall: reviving %observe-hook
gall: reviving %sane
gall: reviving %weather
docket: fetching %http glob for %landscape desk
kiln: beginning install into %landscape from [~siddef %landscape]
kiln: installing %webterm locally
docket: fetching %http glob for %webterm desk
kiln: beginning install into %webterm from [~siddef %webterm]
kiln: installing %bitcoin locally
gall: reviving %btc-wallet
>   '%btc-wallet recompiled'
docket: fetching %http glob for %bitcoin desk
kiln: beginning install into %bitcoin from [~siddef %bitcoin]
gall: reloading agents
gall: reloading %group-view
gall: dead agent reload: %file-server
gall: reloading %group-push-hook
gall: reloading %dojo
gall: reloading %contact-store
gall: reloading %graph-pull-hook
gall: reloading %chat-cli
gall: reloading %hark-store
gall: reloading %contact-pull-hook
gall: reloading %group-store
gall: reloading %ping
gall: reloading %hark-graph-hook
out=[acked=%.y path=/updates]
subscribe wire not unique
%hark-graph-hook
/graph
[p=~wolref-podlex q=%graph-store]
error in %hark-graph-hook
%watch-not-unique
! subscribe wire not unique
! %hark-graph-hook
! /graph
! [p=~wolref-podlex q=%graph-store]
gall: reloading %clock
gall: reloading %sane
gall: reloading %notify
gall: reloading %btc-wallet
>   '%btc-wallet recompiled'
gall: reloading %dm-hook
gall: reloading %spider
[%thread-not-started ~[~.docket-0v5.53voj.3chii.gqhbl.knq0i.7tm6f]]
[%thread-not-started ~[~.docket-0v4.l7joo.jgp37.2h4g7.t9ttm.bgrf0]]
[%thread-not-started ~[~.docket-0v3.sgsg0.j43bc.vpqsl.74n31.8okfd]]
[%thread-not-started ~[~.docket-0v1.hoi9h.pp2ce.cigld.lhnem.nthav]]
gall: reloading %s3-store
gall: reloading %azimuth-tracker
gall: reloading %herm
gall: reloading %chat-store
gall: reloading %observe-hook
gall: reloading %graph-push-hook
gall: reloading %group-pull-hook
gall: reloading %invite-store
gall: reloading %metadata-hook
gall: reloading %invite-hook
gall: reloading %metadata-store
gall: reloading %launch
gall: reloading %dbug
gall: reloading %chat-hook
gall: reloading %eth-watcher
gall: reloading %metadata-pull-hook
gall: reloading %graph-store
gall: reloading %acme
gall: reloading %hood
gall: reloading %weather
gall: reloading %contact-hook
gall: reloading %hark-chat-hook
gall: reloading %contact-view
gall: reloading %metadata-push-hook
gall: reloading %settings-store
gall: reloading %hark-group-hook
gall: reloading %contact-push-hook
gall: reloading %chat-view
gall: dead agent reload: %glob
gall: dead agent reload: %goad
gall: reloading %lens
gall: reloaded agents
docket: thread cancelled; retrying
%cancelled
docket: fetching %http glob for %webterm desk
docket: thread cancelled; retrying
%cancelled
docket: fetching %http glob for %landscape desk
docket: thread cancelled; retrying
%cancelled
docket: fetching %http glob for %garden desk
docket: thread cancelled; retrying
%cancelled
docket: fetching %http glob for %bitcoin desk
eyre: replacing existing binding at /spider
error in %group-push-hook
%arvo-response
! /lib/default-agent/hoon:<[63 3].[63 5]>
! "unexpected system response %clay to %group-push-hook on wire /helper/push-hook/resource-conversion"
! /lib/default-agent/hoon:<[62 3].[63 5]>
! /lib/push-hook/hoon:<[366 11].[366 38]>
! /lib/push-hook/hoon:<[365 9].[367 21]>
! /sys/vane/gall/hoon:<[1.392 9].[1.392 47]>
crud: %drip-fail event failed
drip failed
[%poke %wake]
%load
wire=/sys/cor/eyre/~wolref-podlex/home/~2021.3.1..14.44.07..4a1b.a311.c603.b879
  bar-stack
~[
  ~[/gall/use/hood/0w1.74B7D/~wolref-podlex/drum/home/eyre /dill //term/1]
  ~[
    /gall/use/hood/0w1.74B7D/~wolref-podlex/kiln/ota/~siddef/kids/103/merge-home
    /dill
    //term/1
  ]
  ~[
    /gall/use/hood/0w1.74B7D/~wolref-podlex/kiln/ota/~siddef/kids/103/merge-home
    /dill
    //term/1
  ]
  ~[
    /clay/merge/home/~siddef/kids/mate
    /gall/use/hood/0w1.74B7D/~wolref-podlex/kiln/ota/~siddef/kids/103/merge-home
    /dill
    //term/1
  ]
  ~[//behn]
]
take: failed
/sys/vane/gall/hoon:<[1.833 3].[1.849 5]>
/sys/vane/gall/hoon:<[1.834 3].[1.849 5]>
/sys/vane/gall/hoon:<[1.836 3].[1.849 5]>
/sys/vane/gall/hoon:<[1.838 3].[1.849 5]>
/sys/vane/gall/hoon:<[1.842 3].[1.849 5]>
[ %gall-take-failed
  /sys/cor/eyre/~wolref-podlex/home/~2021.3.1..14.44.07..4a1b.a311.c603.b879
]
/sys/vane/gall/hoon:<[1.843 3].[1.849 5]>
/sys/vane/gall/hoon:<[1.844 3].[1.849 5]>
/sys/vane/gall/hoon:<[1.845 3].[1.849 5]>
/sys/vane/gall/hoon:<[531 5].[540 7]>
/sys/vane/gall/hoon:<[533 5].[540 7]>
/sys/vane/gall/hoon:<[536 13].[536 47]>
/sys/vane/gall/hoon:<[555 5].[570 39]>
/sys/vane/gall/hoon:<[557 5].[570 39]>
/sys/vane/gall/hoon:<[558 5].[570 39]>
/sys/vane/gall/hoon:<[559 5].[570 39]>
/sys/vane/gall/hoon:<[560 5].[570 39]>
/sys/vane/gall/hoon:<[561 5].[570 39]>
/sys/vane/gall/hoon:<[562 7].[562 58]>
gall: failed to build agent %eyre
out=[acked=%.y path=/clients]
subscribe wire not unique
%btc-wallet
/set-provider/~fogteb-hobtyv
[p=~fogteb-hobtyv q=%btc-provider]
error in %btc-wallet
%watch-not-unique
! subscribe wire not unique
! %btc-wallet
! /set-provider/~fogteb-hobtyv
! [p=~fogteb-hobtyv q=%btc-provider]
; ~botwet not responding still trying
out=[acked=%.n path=/clients/~wolref-podlex]
subscribe wire not unique
%btc-wallet
/set-provider/~fogteb-hobtyv/priv
[p=~fogteb-hobtyv q=%btc-provider]
error in %btc-wallet
%watch-not-unique
! subscribe wire not unique
! %btc-wallet
! /set-provider/~fogteb-hobtyv/priv
! [p=~fogteb-hobtyv q=%btc-provider]
; ~botwet is ok
~wolref-podlex:dojo>
```

**Comment by Fang-** [comment] 2021-09-30 15:12
Yes, this looks like a duplicate of #5270, with `%eyre` in place of `%debug`. The other output isn't related, and shouldn't be a big problem I don't think. Try the workaround in the other issue!

**Comment by jalehman** [comment] 2021-09-30 15:43
Oh, I was thrown off by it being called `%eyre`—guess I tried to start eyre as an agent once upon a time. Whoops. Trying now.

**Closed** 2021-09-30 18:17 UTC
