### ISSUE TITLE
Messages do not get sent to chats from Landscape + arvo: replacement event (for %hear) failed

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit#3111] opened 2020-07-08 20:18 UTC
**Describe the bug**

- My messages do not get sent to chats in Landscape. They stay greyed out. 
- I repeatedly received `arvo: replacement event (for %hear) failed`. I know that this usually happens after a breach and clears up, but I breached over a week ago and this is still a problem.
- I was able to send messages for a little bit before I encountered this problem and after my breach.

**Screenshots**

<img width="1166" alt="Screen Shot 2020-07-08 at 12 55 16 PM" src="https://user-images.githubusercontent.com/10265578/86964016-476f2c00-c11a-11ea-97d5-e53dc7f50384.png">

**Desktop (please complete the following information):**
- OS: e.g. MacOS 10.15.4
- Planet is running on GCP
 - Browser: Chrome
 - Base hash: 0vc.5mb6v.nqu78.n190s.qdfcr.5o28s.kcf0q.nuem2.9d4p8.06sp7.dhk61

**Additional context**

I was missing an OTA before. I then forced the OTA merge, and have the most recent base hash. But the problem persists, including the `arvo: replacement event (for %hear) failed` message.

The messages **do** send properly from the CLI. Interestingly, I can also see my unsent messages from Landscape in the CLI; this does not happen in the other direction, though.

**Comment by rmariani** [comment] 2020-07-08 20:27
Ok, looks like the messages are indeed sending from Landscape, but I cannot see them send on Landscape and I cannot see any other messages on Landscape.

<img width="1155" alt="Screen Shot 2020-07-08 at 1 26 50 PM" src="https://user-images.githubusercontent.com/10265578/86966878-b0f13980-c11e-11ea-9add-a125f421be54.png">

**Comment by matildepark** [comment] 2020-07-13 17:57
I am guessing you lost your channel but you could still poke, thus if you refreshed they would show up.

**Comment by matildepark** [comment] 2020-07-13 17:58
If so, this is a dupe of #1862 and this can be closed in favour of it.

**Closed** 2020-07-13 20:17 UTC
Labels: landscape
