### ISSUE TITLE
"Publish" module is stuck at showing `1` event, even though no notebooks have unread indicators

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#2577] opened 2020-03-20 16:15 UTC
**Describe the bug**
When I navigate to my 'Home', the Publish tile renders the number `1`, indicating there should be one unread notebook entry in my list of notebooks. When I navigate to each notebook, and go back to the home screen, I still see the number `1`.

**To Reproduce**
1. I'm unsure how I got to this state! No idea how to reproduce.

Here's a log of what I'm seeing when I navigate to the Publish tile with DevTools running:

```
channel.js:199 eventSource error: Event {isTrusted: true, type: "error", target: EventSource, currentTarget: EventSource, eventPhase: 2, …}
eventSource.onerror @ channel.js:199
error (async)
connectIfDisconnected @ channel.js:198
sendJSONToChannel @ channel.js:152
subscribe @ channel.js:96
bind @ index.js:1
initializePublish @ index.js:1
start @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
~publish:1 GET http://165.22.41.44:8080/~/channel/1584720187388-1e2006 net::ERR_NETWORK_CHANGED
1584720187388-1e2006:1 GET http://165.22.41.44:8080/~/channel/1584720187388-1e2006 404 (missing)
react_devtools_backend.js:6 eventSource error: Event {isTrusted: true, type: "error", target: EventSource, currentTarget: EventSource, eventPhase: 2, …}
r @ react_devtools_backend.js:6
eventSource.onerror @ channel.js:199
error (async)
connectIfDisconnected @ channel.js:198
sendJSONToChannel @ channel.js:152
subscribe @ channel.js:96
bind @ index.js:1
initializePublish @ index.js:1
start @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
```

**Expected behavior**
When I see any number on a Home tile, I expect it to map to exactly the number of unread channels in the module. When I click into the module and view the contents of its objects, I expect the displayed number to decrement or go away completely, if everything has been seen.

**Screenshots**
![Kapture 2020-03-20 at 12 10 04](https://user-images.githubusercontent.com/1195363/77183148-47341d80-6aa4-11ea-9736-2048016a70af.gif)

**Desktop (please complete the following information):**
MacOS 10.15.3 (19D76)
Chrome 80.0.3987.132 (Official Build) (64-bit)
[%base-hash 0vf.djnhb.aguv9.3u4hg.54bj5.4e6mi.abspq.99s36.p5fro.qmv7l.65gau]
[%home-hash 0v15.rcv4e.udg67.9ju7s.83nks.k0dgb.h259f.cgst5.o035m.o9jus.9ob2l]

**Comment by matildepark** [comment] 2020-03-20 16:19
Does Publish’s number show unread notes ... or invites? And are group invites hidden by Publish FE? If invites, and yes, this issue will be a thing. We want it to show unread notes … we can talk about this in an hour and amend, probably.

—
~haddef-sigwen
https://urbit.org

**Comment by vvisigoth** [comment] 2020-03-20 16:20
Yeah, I have a phantom "2" unreads.

**Comment by matildepark** [comment] 2020-03-20 16:22
To elaborate: my gut level question is “When you create a notebook, add it to a group, and hit submit, does it send an invite that the FE is just hiding so that you use the Groups join flow? And is the tile showing invites it knows about, not unreads?”

—
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment] 2020-05-06 14:13
Duplicate of #2501.

**Closed by matildepark** 2020-05-06 14:13 UTC
Labels: OS1, publish
