### ISSUE TITLE
Urbit CLI usage doesn't show `-c` option

### ISSUE THREAD

**Issue by nchammas** [urbit/urbit#489] opened 2015-11-02 03:03 UTC
I installed Urbit via Homebrew and started working my way through the [launch guide](http://urbit.org/docs/user/launch).

The guide mentions a `-c` switch which doesn't show up in Urbit's command-line usage:

```
$ urbit
Usage: urbit [options...] computer
-w name       Immediately upgrade to ~name
-t ticket     Use ~ticket automatically
-I galaxy     Start as ~galaxy
-F            Fake keys
-L            Local-only network
-n host       Set unix hostname
-p ames_port  Set the HTTP port to bind to
-v            Verbose
-D            Recompute from events
-P            Profiling
-M            Memory madness
-f            Fuzz testing
-k stage      Start at Hoon kernel version stage
-Xwtf         Skip last event
```

I assume it's supposed to be there.

**Comment by juped** [comment] 2015-11-02 03:05
Duplicate of #472!

I apologize for our weird repository bifurcation - the situation is not ideal.

**Closed by juped** 2015-11-02 03:05 UTC
Labels: duplicate

**Comment by nchammas** [comment] 2015-11-02 03:09
Oh, word. Apologies about the dup. Searching for "-c" didn't turn up any results.
