### ISSUE TITLE
Duplicate Ships In Invite Search Results

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#3954] opened 2020-11-18 21:23 UTC
**Describe the bug**
Every time I go to invite someone to my group, I see two ships of the exact same name in the search results.

**To Reproduce**
1. Go to group
2. Click on add people.
3. Paste in their ship name
4. See duplicated results.

**Expected behavior**
A single result of the correct name.

**Screenshots**
![image](https://user-images.githubusercontent.com/51895363/99589695-fcabcd80-29b1-11eb-8ac5-88b910490737.png)

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Browser Chrome
 - Base hash of your urbit ship. Run `+trouble` in Dojo to see this.
Currently two hashes simultaneously.

**Smartphone (please complete the following information):**
 - Base hash of your urbit ship. Run `+trouble` in Dojo to see this.

**Additional context**

**Comment by matildepark** [comment] 2020-11-18 21:25
Duplicate of urbit/landscape#144, which really should be here as this is a livenet issue, so this one takes precedence.

**Comment by tylershuster** [comment] 2020-11-18 21:55
I fixed this before, I can take it again

**Comment by matildepark** [comment] 2020-11-18 21:57
In the **next few hours**?

`Accept`

`Decline`

**Comment by tylershuster** [comment] 2020-11-18 21:59
`Challenge Accepted`

**Comment by custom-jonathan** [comment] 2020-11-18 22:00
🎉

**Closed** 2020-11-19 03:50 UTC
Labels: landscape
