### ISSUE TITLE
Crud Error

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2647] opened 2020-04-01 21:57 UTC
I'm getting this every once in awhile, and I'm not sure how to read it:

```
crud: %eyre-no-channel event failed
id='1585107267467-8e2586'
```

**Comment by Fang-** [comment] 2020-12-11 00:59
Closing as duplicate of #3196. (Actually, that one is a duplicate of this, but there's more discussion there.)

**Closed by Fang-** 2020-12-11 00:59 UTC
Labels: eyre
