### ISSUE TITLE
Cannot reach [star].arvo.network

### ISSUE THREAD

**Issue by pimato** [urbit/urbit#1240] opened 2019-04-14 20:42 UTC
Hallo Urbit Community,

I am trying to reach my star via donbus.arvo.network but it doesn`t work.
The only thing I did was to configure my IP address via `:dns|ip`.

Do I still need to configure my DNS Settings to reach the website?

I can`t also use the Urbit IOS app, probably for the same reasons described above.

**Comment by msutherl** [comment] 2019-04-17 18:20
@pimato I think this is caused by issues with `~bus`. We're looking into it.

Can you also double-check that port 80 is open on your machine? You won't be able to access your ship via HTTP if it's bound to 8080.

**Comment by jtobin** [comment] 2019-05-02 12:57
@pimato did you manage to get this cleared up afterwards?

**Comment by jtobin** [comment] 2019-05-12 01:34
@pimato I'll close this for now -- feel free to reopen if it's still an issue.

**Closed by jtobin** 2019-05-12 01:34 UTC
