### ISSUE TITLE
Joining chat from landscape isn't reflected in console

### ISSUE THREAD

**Issue by ronreg-ribdev** [urbit/urbit#1849] opened 2019-10-18 09:07 UTC
Earlier I noticed a bug wherein I joined ~dopzod/urbit-help from landscape, and then moved over to the console chat UI. I could type into the console, but my messages didn't show up in the chat, either in the console or in landscape. I had to type `;join ~dopzod/urbit-help` to join the chat in the console a 2nd time before I could type in the console and have my messages reflected in both places.

**Comment by Fang-** [comment] 2019-10-18 13:55
Hmm, cannot reproduce (on a local network). Joining some channel from the web UI gives the expected notifications in console (`new`, and an automated glyph `set`), and posting to it works fine from both web and console.

The chat-cli doesn't auto-update its target to match that though. Maybe you just needed to do `;~dopzod/urbit-help` (or simply `;@` or whatever glyph was auto-bound) before sending? `;join` also sets you messaging target to the thing you joined, so maybe that was the real fix.

**Comment by matildepark** [comment] 2020-06-30 23:02
ping @Fang-, given no additional reports and a decent hypothesis, this seems closable.

**Comment by Fang-** [comment] 2020-07-01 00:05
Closing then. Thanks for filing anyway, @ronreg-ribdev! lmk if this still gives you trouble.

**Closed by Fang-** 2020-07-01 00:05 UTC
Labels: chat
