### ISSUE TITLE
Interrupt: address out of loom

### ISSUE THREAD

**Issue by mckpm** [urbit/urbit#1014] opened 2018-07-17 00:49 UTC
I typed something by mistake into my urbit, which crashed.  I think it was just C-c.  This is vere 0.5.1.

```
~macpur-salpyx:dojo>
recover: dig: intr

bail: oops
address 0x7fa0b24b64c0 out of loom!
loom: [0x36000000 : 0xb6000000)

bail: oops
bailing out
address 0x41e751 out of loom!
loom: [0x36000000 : 0xb6000000)

bail: oops
bailing out
urbit: ../noun/manage.c:627: u3m_bail: Assertion `0' failed.
                                                            fish: “build/urbit macpur-salpyx” terminated by signal SIGSEGV (Address boundary error)
```
But, my urbit then booted just fine and I couldn't make it happen again.  ¯\\\_(ツ)\_/¯

**Comment by ccesare** [comment] 2019-02-06 14:56
I've been getting this error on local builds since 0.7.0 just trying to boot my planet, although I only see one `bail: oops`.

```
~
urbit 0.7.2
boot: home is ###
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/109.264.896
address 0x1fffffffc out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in ../noun/events.c:126

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file ../noun/manage.c, line 650.
```

I don't get the error on an older build (0.6.0).

**Comment by joemfb** [comment] 2019-02-06 15:36
Urbit intercepts memory errors (SIGSEGV) and uses them to page it's persistent memory image (the Loom). So "address out of loom" means we got an actual memory error, not one that we should intercept.

You should have a core dump after a crash like that (you may need to fiddle with `ulimit` first). Can you open that core file, print the backtrace, and post it here?

- with `gdb` (if you compiled with `gcc`): `gdb path/to/urbit/binary path/to/core`
- with `lldb` (if you compiled with `clang`): `lldb -c /path/to/core`

Once the debugger opens, type `bt` to print the backtrace.

Also, what is your OS?

**Comment by jtobin** [comment] 2019-06-21 06:25
Closing as this one lacks reproduction details & hasn't been followed up on.

**Closed by jtobin** 2019-06-21 06:25 UTC
Labels: bail, bug, memory
