### ISSUE TITLE
contacts: member list visual jank

### ISSUE THREAD

**Issue by liam-fitzgerald** [urbit/urbit#3245] opened 2020-08-01 05:09 UTC
See image, the scroll container does not take up the full size it is supposed to. 

Occurring on OS X Chrome
![Screen Shot 2020-08-01 at 3 06 13 pm](https://user-images.githubusercontent.com/46801558/89094578-c1888d00-d408-11ea-88ff-70c2da57066a.png)

cc: @tylershuster

**Comment by tylershuster** [comment] 2020-08-01 13:10
Dupe of #3244 ?

Can't reproduce. What's your Chrome version, and how did it reach this state? Just regular old: Go to groups, click UC ?

**Comment by tylershuster** [comment] 2020-08-01 13:18
And how far down did you scroll before it happened? They do take an instant to appear, but that's part of the lazy-loading process. But if you got a screenshot that means it took more than an instant...

**Comment by liam-fitzgerald** [comment] 2020-08-01 13:48
Happens regardless of how much I scroll, but seems to occur fairly infrequently and only on UC. Will try to get a better repro for you. 
—
~hastuc-dibtux

**Comment by matildepark** [comment] 2020-08-04 18:48
Dupe of #3244, both of these shouldn't be open ...

**Closed by matildepark** 2020-08-04 18:48 UTC
Labels: landscape
