### ISSUE TITLE
|mount fails on publish-comment

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2760] opened 2020-04-17 13:21 UTC
I'd like to mount my home directory just to keep my publish files safe in case I have to breach. So I ran `|mount %` that ran for a while before printing

```
  <[3.106 7].[3.106 72]>
/~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay:<[430 7].[465 9]>
/~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay:<[433 7].[465 9]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[433 20].[433 47]>
/~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay:<[385 5].[394 7]>
/~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay:<[386 7].[386 18]>
/~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay:<[385 5].[394 7]>
/~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay:<[387 5].[394 7]>
/~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay:<[388 5].[394 7]>
/~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay:<[389 5].[394 7]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[393 14].[393 44]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[393 21].[393 43]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[1.897 5].[1.910 22]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[1.899 5].[1.910 22]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[1.901 5].[1.910 22]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[1.902 5].[1.910 22]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[1.902 15].[1.910 22]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[1.903 5].[1.910 22]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[1.903 15].[1.903 46]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[2.184 5].[2.185 57]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[2.185 5].[2.185 57]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[2.175 5].[2.175 40]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[2.175 27].[2.175 39]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/ford
  <[4.822 18].[4.822 59]>
-find.grow
ford: %slim failed:
ford: %ride failed to compute type:
\/ford: %cast failed to ride /~ravmel-ropdyl/home/0/mar/publish/comment/hoon d\/
  uring +grow:
\/                                                                            \/
ford: %cast failed while trying to cast from publish-comment to mime:
ford: failed to %cast
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[2.168 44].[2.168 54]>
%ford-fail
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[2.168 30].[2.168 55]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[2.240 19].[2.240 53]>
  /~ravmel-ropdyl/home/~2020.4.14..14.46.42..a62e/sys/vane/clay
  <[2.240 16].[2.240 53]>
```

The stack trace is clipped — but I think the last part is probably the most important.

**Comment by liam-fitzgerald** [comment] 2020-04-17 13:29
I've seen this! It's a dupe of #2731 and should be fixed when #2736 OTAs

**Comment by galenwp** [comment] 2020-04-17 13:37
Oh nice. Thanks!

**Closed** 2020-04-17 16:27 UTC

**Comment by ryjm** [comment] 2020-05-05 03:38
has this gone out yet? i'm also seeing this error. are there any workarounds at the moment?
