### ISSUE TITLE
|uninstall doesn't also suspend the app

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6242] opened 2023-01-23 19:01 UTC
- |uninstall %bitcoin
- Observe the desk is uninstalled
- Run +vat %bitcoin
- Observe the desk is still marked running
- You need to then run |suspend

This is bad because it means kelvin upgrades will block on the "uninstalled" bitcoin that's still marked running.

**Comment by Fang-** [comment] 2023-01-24 15:16
Probably duplicate of #6154.

**Comment by vvisigoth** [comment] 2023-02-14 20:28
@belisarius222 @yosoyubik is anyone actively working on this or can I put this in the grab bag?

**Comment by yosoyubik** [comment] 2023-02-15 12:59
@vvisigoth I don't think anybody is working on this (or https://github.com/urbit/urbit/issues/6154) at the moment

**Closed** 2023-03-15 20:58 UTC
Labels: bug, community contribution
