### ISSUE TITLE
Error with example-tapp-subscribe.hoon: %error-tapp-no-sole

### ISSUE THREAD

**Issue by famousj** [urbit/urbit#1884] opened 2019-10-24 13:54 UTC
I started a fakezod, ran `|start %example-tapp-subscribe` and got this:

```
activated app home/example-tapp-subscribe
[%tapp-init %example-tapp-subscribe]
tapp command failed in app/example-tapp-subscribe
  %crash
/~zod/home/0/lib/tapp/hoon:<[102 34].[102 36]>
%default-tapp-no-sole
/~zod/home/0/lib/tapp/hoon:<[102 7].[102 36]>
/~zod/home/0/lib/tapp/hoon:<[101 5].[103 53]>
/~zod/home/0/lib/tapp/hoon:<[100 5].[103 53]>
/~zod/home/0/lib/tapp/hoon:<[526 18].[526 63]>
/~zod/home/0/lib/tapp/hoon:<[523 9].[529 11]>
/~zod/home/0/lib/tapp/hoon:<[522 9].[529 11]>
/~zod/home/0/lib/tapp/hoon:<[521 9].[529 11]>
> |start %example-tapp-subscribe
>=
[linked to [p=~zod q=%example-tapp-subscribe]]
```

**Comment by philipcmonk** [comment] 2019-10-24 16:13
That's ugly, but expected. The system is trying to open a console
connection to the app, but the app doesn't support it. There's a way to
silence that "error", but it's kind of weird as well. We should clean up
that system some time.

**Comment by ohAitch** [comment] 2019-10-24 16:16
Cutting the stack trace off with !. after %default-tapp-no-sole seems maybe
desirable? And %crash is just redundant.

**Comment by ohAitch** [comment] 2019-10-24 16:21
Rephrasing to sth like %console-unimplemented-rejecting-connection may also
be more neutral

Alternately one could add a sole-effect a lá  nohup  to the effect of
"daemon mode app booted", which prompts drum to unlink.

**Comment by philipcmonk** [comment] 2019-10-24 16:24
What should happen is that whoever is receiving that negative reap (drum?)
should just not print it.

**Comment by ohAitch** [comment] 2019-10-24 16:26
That's reasonable, tho I'm still lobbying for "condense to one line of 'not
a sole app yo' print" rather than ignoring outright

**Comment by famousj** [comment] 2019-10-24 16:30
So, if I'm reading this thread right, everything more-or-less worked, i.e. the app `|start`-ed.

**Comment by philipcmonk** [comment] 2019-10-24 16:33
That's correct, it started correctly.

@ohaitch I'd say it should print nothing because there was no error, but I
don't feel strongly about that.

**Comment by ohAitch** [comment] 2019-10-24 16:36
I'd be concerned about it completely losing crashes in subscriptions that
~tried~ to implement sole and failed

Like, "bid for interactivity rejected, |knob etc for details" would point
you in the right direction if you /had/ been trying to clone dojo or w/e.
(Alternately, maybe |start implying |link should be a keyword parameter
instead of the default?)

**Comment by joemfb** [comment] 2019-10-24 17:34
I think the best fix here is to remove the automatic /sole subscription. Apps that want to be subscribed by default could just poke :hood.

**Comment by joemfb** [comment] 2019-10-25 01:14
Closing as duplicate of #1408

**Closed by joemfb** 2019-10-25 01:14 UTC
