### ISSUE TITLE
Dojo Peer

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1832] opened 2019-10-16 19:54 UTC
No idea what this is, so I'm putting it here so I can reference it later.

```
[%dojo-peer-replaced 2]
[unlinked from [p=~minder-folden q=%dojo]]
/~minder-folden/home/0/app/dojo/hoon:<[1.160 24].[1.161 21]>
[ %poke
  [ %det
    ler=[own=84 his=876]
    haw=0v4.tebrl.hi6s5.po33j.8e70o.cbr1g
    ted=[%mor p=~[[%ins p=31 q=~-7]]]
  ]
]
/~minder-folden/home/0/app/dojo/hoon:<[1.160 38].[1.161 21]>
/~minder-folden/home/0/app/dojo/hoon:<[1.145 9].[1.146 28]>
/~minder-folden/home/0/app/dojo/hoon:<[1.146 9].[1.146 28]>
/~minder-folden/home/0/app/dojo/hoon:<[1.146 17].[1.146 28]>
/~minder-folden/home/0/app/dojo/hoon:<[1.112 5].[1.119 7]>
/~minder-folden/home/0/app/dojo/hoon:<[1.113 5].[1.119 7]>
/~minder-folden/home/0/app/dojo/hoon:<[1.115 5].[1.119 7]>
/~minder-folden/home/0/app/dojo/hoon:<[1.116 13].[1.116 28]>
/~minder-folden/home/0/app/dojo/hoon:<[1.065 5].[1.077 27]>
/~minder-folden/home/0/app/dojo/hoon:<[1.068 5].[1.077 27]>
/~minder-folden/home/0/app/dojo/hoon:<[1.069 5].[1.077 27]>
/~minder-folden/home/0/app/dojo/hoon:<[1.073 5].[1.077 27]>
/~minder-folden/home/0/app/dojo/hoon:<[1.073 9].[1.073 37]>
/~minder-folden/home/0/app/dojo/hoon:<[1.073 13].[1.073 37]>
/~minder-folden/home/0/app/dojo/hoon:<[827 5].[835 31]>
/~minder-folden/home/0/app/dojo/hoon:<[828 5].[835 31]>
/~minder-folden/home/0/app/dojo/hoon:<[829 5].[835 31]>
/~minder-folden/home/0/app/dojo/hoon:<[830 5].[835 31]>
/~minder-folden/home/0/app/dojo/hoon:<[830 9].[830 60]>
/~minder-folden/home/0/app/dojo/hoon:<[830 13].[830 60]>
[%drum-coup-fail ~minder-folden 1 p=~minder-folden q=%dojo]
[linked to [p=~minder-folden q=%dojo]]
```

**Comment by joemfb** [comment] 2019-10-16 19:59
Something you typed crashed the dojo parser, which caused it to be unlinked from your console. It's automatically re-linked though, so the only casualty should be your history.

**Comment by jtobin** [comment] 2019-10-17 05:37
This is effectively a duplicate of #1495, so I'll close this one.

**Closed by jtobin** 2019-10-17 05:37 UTC
