### ISSUE TITLE
Event log is written to agressively

### ISSUE THREAD

**Issue by xy2iii** [urbit/urbit#2837] opened 2020-05-02 08:29 UTC
Hello!

Playing around with the REPL, I noticed that there was a write to disk every time I typed something, which I found was the [event log](https://urbit.org/docs/glossary/eventlog/)

By observing the writes to the event log, `egz.hope`, I found that it was written to every keystroke.

To reproduce:

1. Create a new env with `urbit -F zod`.
2. In another terminal, get the event's log size: if you are in the `zod/` directory, do `ls -l zod/.urb/egz.hope`.
3. Type something in the REPL.
4. Get the event's log size again with `ls -l zod/.urb/egz.hope`: it will have increased.

After reading the [event log](https://urbit.org/docs/glossary/eventlog/) page, I don't know if this behavior is intended. A disk write on every keystroke slows down the REPL, notably when trying to paste into it.

**Information**
OS: NixOS stable, reproduced on Debian
Version: 0.10.4

Thank you for your time!

**Comment by lukechampine** [comment] 2020-05-02 15:01
This is intended behavior. If you kill your dojo prompt and restart, you'll see that it restores the contents of the prompt prior to the crash.

IMO this is a bit overkill, but it really does showcase Urbit's commitment to persistence. I think the idea is that, rather than sacrifice reliability for performance, we should push for hardware (such as Intel Optane) that can achieve the persistence characteristics that are so obviously needed.

**Comment by ohAitch** [comment] 2020-05-02 18:59
There are two levels here: never displaying a keystroke before it's
persisted, which is essential ACID, and treating a 10-line paste as
individual keystrokes persisted serially, which is incidental and the
"aggressively" bug. Expected, or at least desired, behavior, is for them to
be committed in batches, with accumulated terminal output printed after
each batch hits disk.

There are separate performance issues with the dojo parser, and in
particular pasting being quadratic due to each intermediate input being
fully parsed, which disk persistence would not address - try running your
fakezod against a ramdisk/tmpfs to see which is the bigger issue. Needless
to say DO NOT DO THIS with a real/noncomet urbit you care about.

(One obvious way to make parsing nonquadratic is to send a separate "parse"
event, only at times the event queue is empty. A hack that somewhat works
for single-line pastes is to insert a single quote, arrow left, paste, and
delete the quote: iirc the parsing is only run on appends.)

**Comment by belisarius222** [comment] 2020-05-02 20:20
We could add an event that includes a list of keypresses.  That could be nice for external scripting, and I don't think it would require any hacks or break the model.

It's also worth noting that we could do various forms of latency compensation in which the runtime could optimistically display the expected effects of an event before its actual effects have been emitted.  We can't do this with Ames packet acks, but it should be fine in the terminal.

In the console, the runtime could display the most recently typed letters immediately, store the terminal state from before those provisionally applied effects, and then when the actual effects are emitted, confirm the provisionally displayed effects if they're the same as what we expected, or roll back to the stored previous state if they differ.

—
~rovnys-ricfer
https://urbit.org

**Comment by ohAitch** [comment] 2020-05-02 20:28
I suppose yeah, it even already uses an operational-transformation latency
compensation protocol *between* the terminal driver and dojo, cf web dojo.
Having it just deliver the keystrokes in a separate event(/thread?? with
the tty being effectively a moon) would be sufficient.

**Comment by belisarius222** [comment] 2020-05-02 20:37
@ xy2iii you might be surprised to learn that writing to disk is actually not what makes dojo slow.  On most machines, disk writes are 5-10ms, which is low enough to be within a 60fps frame rate.  Most of the latency comes from parsing, as @ohAitch mentioned.  This parsing has been faster and slower at different times as other things change.  Right now it's slow enough to cause noticeable typing lag, which is unpleasant.  A year and a half ago, after some performance work from @eglaysher, dojo mostly had no typing lag.

So even if we don't do any latency compensation, I'd argue the real problem here is just that Dojo is slow.  Disk writes are intended and unproblematic.  The problem as described in the issue title and reproduction is not a bug, so I'm closing this.  Rest assured, we will fix the Dojo typing lag.

**Closed by belisarius222** 2020-05-02 20:37 UTC
Labels: bug

**Comment by ohAitch** [comment] 2020-05-03 03:41
100-200fps framerate = 120 character paste would still take around a second P:

(but yeah it's not the low hanging fruit)
