### ISSUE TITLE
Groups Rendering Issue

### ISSUE THREAD

**Issue by nartes-fasrum** [urbit/urbit#2567] opened 2020-03-19 23:43 UTC
**Describe the bug**
For some groups managed by the user, switching from Group A to Group B results in a channel from Group A being rendered as a channel in Group B. Subsequent switches back from Group A to Group B produce additional instances of the channel.

**To Reproduce**
1. Go to ~groups/
2. Click on a group managed by the user
3. Click on another group managed by the same user
4. Observe the rendering bug

**Expected behavior**

**Screenshots**
[Screencast of issue.](https://imgur.com/a/uLTgOXN)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Brave
 - Base hash of your urbit ship: 0v19.ibduh.62jie.3rk7j.ojsiq.4bmhv.m7cus.c8cu5.rhoq7.rs3pp.f0eri

**Comment by matildepark** [comment] 2020-03-20 00:02
Can't reproduce in my dev environment so far, which is odd ...

**Comment by loganallenc** [comment] 2020-03-31 18:16
This bug is crazy. I can't reproduce either.

**Comment by nartes-fasrum** [comment] 2020-04-13 14:04
Still seeing this on the .uucan hash. Asked around in the affected chat on 3 Apr for some more data points and had mixed responses - Chrome & Chromium browsers on macOS, nixOS, and Debian were affected in some cases while Safari on macOS was not.

**Comment by matildepark** [comment] 2020-04-28 15:37
@nartes-fasrum I imagine this is not browser-specific, it's more to do with which groups are being jumped between and what edge case is being produced such that the Group Detail component is passing an additional item between iterations of itself. This is a weird one, but if you can provide as much information as possible as whether this affects jumping between *any* two groups, or two groups with the same owner, or if either are you ... you get the idea.

**Comment by liam-fitzgerald** [comment] 2020-06-19 07:48
@nartes-fasrum can you confirm that this was fixed with the latest OTA?

**Comment by liam-fitzgerald** [comment] 2020-07-14 14:16
confirmed out of band to be closed

**Closed by liam-fitzgerald** 2020-07-14 14:16 UTC
Labels: groups, landscape
