### ISSUE TITLE
publish: Can't tell which notebooks are unread

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2501] opened 2020-03-14 06:07 UTC
**Describe the bug**
Can't tell which notebooks are unread.  Maybe it's too subtle for me or uses colors I can't see (deuteranomalous).

**To Reproduce**
1. Go to Home and see 3 notifications in publish
2. Go to publish and don't see anything to distinguish notebooks

**Expected behavior**
Be able to see where the unread posts/comments are.

**Screenshots**
<img width="628" alt="Screen Shot 2020-03-13 at 11 04 35 PM" src="https://user-images.githubusercontent.com/5553176/76676269-107b7600-657f-11ea-832f-1c0f95edcda5.png">

Partial list (actual list is too long for one screen and don't want to display non-public notebooks):
<img width="316" alt="Screen Shot 2020-03-13 at 11 02 06 PM" src="https://user-images.githubusercontent.com/5553176/76676253-d4e0ac00-657e-11ea-894b-1cf7227f05d1.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Base hash of your urbit ship. 8ehjl

**Comment by Fang-** [comment] 2020-03-16 13:40
> Maybe it's too subtle for me or uses colors I can't see (deuteranomalous).

Pretty sure there's just no indicators in the UI yet.

**Comment by vvisigoth** [comment] 2020-03-19 16:32
We have an open discussion on this in Asana with @urcades Just flagging because we probably won't do anything with this until we've got a comprehensive notifications design.

**Comment by matildepark** [comment] 2020-04-28 15:32
To be clear the issue in question here is unread counts being shown on the tile with no visible unreads in the app.

**Comment by galenwp** [comment] 2020-04-28 21:20
I also can't seem to make the unread count go down on individual notebooks.
And while I'm at it I'd really love to 'mark all as read'...

**Comment by matildepark** [comment] 2020-05-06 14:12
This is caused by #2856; related is #2818; blocking it is implementing archived notebook support.

**Comment by matildepark** [comment] 2020-08-06 01:49
Poking this because this is still live on the network in the @galenwp guise — notebooks aren't being set as read when you navigate to them; there is no 'mark all as read' functionality (may require back-end work, though, if we don't want to `.map` API calls, I know that sounds rough).

**Comment by tacryt-socryp** [comment] 2020-08-06 06:26
I recommend either postponing work on this until publish is moved to graph-store in the next few weeks, or doing it entirely on the frontend...

**Comment by matildepark** [comment] 2020-08-06 20:57
See #3259 for *most* of this, I think the rest requires some back-end graphin'.

**Comment by tylershuster** [comment] 2020-10-27 15:56
This is obsolete, right? Or at least superseded by https://github.com/urbit/landscape/issues/122

**Comment by matildepark** [comment] 2020-10-27 16:52
@tylershuster the root cause of this issue was that archived notebooks were invisible to the user but still showed unread counts in the tile, because the tile count didn't distinguish. The unread count was provided by the back-end so it wasn't an easy fix, so we removed unread counts entirely from the tiles. The fix for this, IMO, is the graph-store migration + the archive story.

**Comment by matildepark** [comment] 2020-11-19 05:47
With graph-store + hark unread counts are now opt-in and exclude archived content.

**Closed by matildepark** 2020-11-19 05:47 UTC
Labels: landscape, publish
