### ISSUE TITLE
OS1 Chat: Starts scrolled up halfway up the screen on mobile

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2778] opened 2020-04-21 22:10 UTC

**Comment by matildepark** [comment] 2020-04-21 22:11
Duplicate of #2508?

**Comment by loganallenc** [comment] 2020-04-21 22:52
Not really, no.

**Closed** 2020-05-06 00:58 UTC
Labels: OS1, chat

**Comment by matildepark** [comment] 2020-05-26 16:58
@galenwp Is this the scroll behaviour you were talking about out of band? Or are you annoyed by https://github.com/urbit/urbit/issues/2864?

**Comment by galenwp** [comment] 2020-05-26 21:01
yeah, i think it's basically this. i open a chat, it starts in some weird position scrolled up.

**Comment by matildepark** [comment] 2020-05-26 21:06
All chats or just chats with images? Is it #2883?

**Comment by galenwp** [comment] 2020-05-26 21:22
okay, i think it's chats with images — but i also notice that i can't scroll the container if i'm not touching text

**Comment by galenwp** [comment] 2020-05-26 21:23
And sometimes it seems like I can't scroll up at all.

**Comment by matildepark** [comment] 2020-08-10 20:26
FTR this is still occurring. #3242 may fix. @galenwp (and others) ping if you see this after the next OTA.
