### ISSUE TITLE
Redundant galaxy IP fetching

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1414] opened 2019-08-01 22:02 UTC
As if this wasn't noisy enough yet, I'm seeing the following in my CLI every five minutes:

```
ames: czar at fyn.urbit.org: not found (b)
ames: czar at fyn.urbit.org: not found (b)
ames: czar at dut.urbit.org: not found (b)
ames: czar at fyn.urbit.org: not found (b)
ames: czar at ter.urbit.org: not found (b)
```

Note how the lookup for ~fyn gets printed three times, implying that the lookup gets _done_ three times. Not sure how that happened, it should really only be running that once for every galaxy.

**Comment by joemfb** [comment] 2019-08-01 23:57
This is a duplicate of #1383 -- fixed in #1392. At least, the duplicate printfs are fixed. I'm not concerned about duplicate lookups, as they're asynchronous.

**Closed by joemfb** 2019-08-01 23:57 UTC
