### ISSUE TITLE
Haven't been able to join a notebook for about two months

### ISSUE THREAD

**Issue by somlus-savlev** [urbit/urbit#2206] opened 2020-01-29 14:49 UTC
Hello, somlus-savlev here. 

Somewhere along the line (about 2 months ago, probably 2-3 weeks after the last network breach), the notebook ~minder-folden/the-new-era stopped updating altogether for me, so I unsubscribed and then could never resubscribe.  I get quite a long error seen here:

https://pastebin.com/XLWsWQiV

when I type in the usual command in dojo:

:publish|subscribe ~minder-folden %the-new-era

Unsubscribing with

:publish|unsubscribe ~minder-folden %the-new-era

and then resubscribing similarly does not work.  Any ideas on how to get reconnected or what is going on here? I see ~minder-folden just fine and communicate regularly with him in his /party chat.

**Comment by philipcmonk** [comment] 2020-01-29 19:11
Can you run `+timers` and give the output?  @belisarius this may be a stuck flow.

**Comment by sdubyam** [comment] 2020-01-29 22:32
You bet, here you go:

https://pastebin.com/BjYbMSUN

**Comment by risruc-habteb** [comment] 2020-01-30 14:16
I'm seeing the same issue with the same notebook.
I noticed through chat that I haven't gotten updates in about 1 month, so decided to try and unsub/resub.

Here is the dojo output upon unsubcribing and attempting to resubscribe.
https://hastebin.com/rehijasifa.pl

**Comment by custom-jonathan** [comment] 2020-01-30 14:34
If there's anything you need `~minder-folden` to run, let me know and I'll try it out.

**Comment by belisarius222** [comment] 2020-01-30 23:10
Hm, not sure what would cause the 'ack for nonexistent subscription' crash.  Maybe an Ames error-handling gone wrong, or even a Gall error-handling gone wrong?

That does seem like a lot of timers, on a lot of different Ames flows.  @philipcmonk do you have an idea of what that indicates?

**Comment by risruc-habteb** [comment] 2020-01-31 00:45
fwiw, here is my +timers output.
https://hastebin.com/pucicokizu.coffeescript

**Comment by pepijndevos** [comment] 2020-02-01 14:54
I'm also unable to join the Hoon school notebook:
```
:publish &publish-action [%subscribe ~rapfyr-diglyt %hoon-school-assignments]
out={[p=[wire=/collection/hoon-school-assignments ship=~rapfyr-diglyt term=%publish] q=[acked=%.n path=/collection/hoon-school-assignments]]}
subscribe wire not unique
%publish
/collection/hoon-school-assignments
[p=~rapfyr-diglyt q=%publish]
error in %publish
%watch-not-unique
! subscribe wire not unique
! %publish
! /collection/hoon-school-assignments
! [p=~rapfyr-diglyt q=%publish]
> :publish &publish-action [%subscribe ~rapfyr-diglyt %hoon-school-assignments]
>=
```

**Comment by nabulator** [comment] 2020-02-06 16:23
I have the same error as @pepijndevos

**Comment by philipcmonk** [comment] 2020-02-06 19:55
This and #2176 are probably the same thing.  Something is causing the subscription to think it's being duplicated.  This is a bug in either the ames (the acknowledgment for the first subscription is not getting through, ie "stuck flow"), gall (an old subscription is not getting cleaned up?  or something else?), or the app itself mismanaging subscriptions.  Since it happens for both chat and publish, it's less likely to be the application, but it's possible that it's just doing the same pattern.

Unfortunately, I'm not sure when someone will have a chance to deal with this.  Since it affects so many people, it should be a high priority.

Does anybody have a consistent reproduction (ie a way to cause this to happen from a fresh ship)? 
 If not, some of the recent debugging tools we've built should be helpful for this, so could someone who has this problem send me their pier (philip at tlon io)?  I won't run it on the live net, so you don't have to keep your pier off (do turn it off while copying it, of course).  It's preferable if it can be a ship that hasn't been running for too long, but anything will do.

**Comment by somlus-savlev** [comment] 2020-02-08 17:03
philip I will send you my pier but unfortunately it has been running a long time.  Please expect a dropbox link to be sent to you shortly.

**Comment by risruc-habteb** [comment] 2020-03-09 19:15
FYI, it appears I fixed this with a |gall-wash
Wish I'd thought to try that sooner.

**Comment by custom-jonathan** [comment] 2020-03-09 19:54
I just tried `|gall-wash` on my backup planet ~talleg-botsug and got this:

```
> |gall-wash
%cx /~talleg-botsug/home/~2020.3.9..19.53.52..6355/gen/hood/gall-wash/hoon
scry failed for
ford: %hood failed for /~talleg-botsug/home/0/gen/hood/gall-wash/hoon:
ford: %core on /~talleg-botsug/home/0/gen/hood/gall-wash/hoon failed:
~talleg-botsug:dojo> 
```

**Comment by risruc-habteb** [comment] 2020-03-10 02:13
Err.. that's because the command is |wash-gall
Apologies. I will ninja edit the post above to avoid misleading anyone else.

**Comment by joemfb** [comment] 2020-03-10 02:41
@philipcmonk, that should be a no-op now as of static-gall, right?

**Comment by philipcmonk** [comment] 2020-03-10 05:17
Yes.  Does the placebo effect work if you know it's a placebo?

**Comment by risruc-habteb** [comment] 2020-03-10 11:44
Interesting.
I tried to unsubscribe and re-subscribe immediately before.
- Stream of errors as usual.
Ran |wash-gall 
- processed without any output.
Ran subscribe command again
- processed without any output, successfully.

**Comment by pepijndevos** [comment] 2020-03-10 12:30
Do I need to run the latest master for this to work? I'm on 0.10.3 and it's still broken for me.

**Comment by wolfmcnally** [comment] 2020-04-16 07:19
I just started my first ship today and am able to join and start chats, but I am not able to join or start notebooks.

```
  out
{ [p=[wire=/permissions ship=~boldur-wolfen term=%permission-store] q=[acked=%.y path=/updates]]
  [p=[wire=/invites ship=~boldur-wolfen term=%invite-store] q=[acked=%.y path=/invitatory/publish]]
  [p=[wire=/subscribe/~wicdev-wisryt/bulletin-board ship=~wicdev-wisryt term=%publish] q=[acked=%.y path=/notebook/bulletin-board]]
}
subscribe wire not unique
%publish
/subscribe/~wicdev-wisryt/bulletin-board
[p=~wicdev-wisryt q=%publish]
error in %publish
%watch-not-unique
! subscribe wire not unique
! %publish
! /subscribe/~wicdev-wisryt/bulletin-board
! [p=~wicdev-wisryt q=%publish]
> :publish|subscribe ~wicdev-wisryt %bulletin-board
>=
```

**Comment by sopmep-malpub** [comment] 2020-04-20 14:16
Another data point. I also am unable to join any notebooks.

```error in %publish
%arvo-response
! /~sopmep-malpub/home/0/lib/default-agent/hoon:<[63 3].[63 5]>
! "unexpected system response %g to %publish on wire /out/~wicdev-wisryt/publish/subscribe/~wicdev-wisryt/bulletin-board"
! /~sopmep-malpub/home/0/lib/default-agent/hoon:<[62 3].[63 5]>
! /~sopmep-malpub/home/0/app/publish/hoon:<[382 7].[382 28]>
! /~sopmep-malpub/home/0/app/publish/hoon:<[381 5].[415 7]>
! /~sopmep-malpub/home/0/app/publish/hoon:<[380 5].[415 7]>
! /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/gall:<[1.236 9].[1.236 47]>
error in %publish
%arvo-response
! /~sopmep-malpub/home/0/lib/default-agent/hoon:<[63 3].[63 5]>
! "unexpected system response %g to %publish on wire /out/~somlus-savlev/publish/subscribe/~somlus-savlev/hoontards-the-notebook"
! /~sopmep-malpub/home/0/lib/default-agent/hoon:<[62 3].[63 5]>
! /~sopmep-malpub/home/0/app/publish/hoon:<[382 7].[382 28]>
! /~sopmep-malpub/home/0/app/publish/hoon:<[381 5].[415 7]>
! /~sopmep-malpub/home/0/app/publish/hoon:<[380 5].[415 7]>
! /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/gall:<[1.236 9].[1.236 47]>```

```> +trouble
[ [%base-hash 0vv.f2us6.8jmr3.7j210.fcjlo.mked1.ginbl.aeg9n.dcsqm.bhmo1.h6m4a]
  [%home-hash 0vv.f2us6.8jmr3.7j210.fcjlo.mked1.ginbl.aeg9n.dcsqm.bhmo1.h6m4a]
  [%our ship=~sopmep-malpub point='2294363348' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~ramnes point='13524' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

I have tried:

- `;leave`ing the notebook in chat and then rejoining
- unsubscribing via `:publish &publish-action [%unsubscribe <ship> <notebook>]` and then resubscribing
- `|wash-gall`
- `:publish %state-surgery`
- restarting urbit

**Comment by ukd1** [comment] 2020-05-06 22:54
> This and #2176 are probably the same thing. Something is causing the subscription to think it's being duplicated. This is a bug in either the ames (the acknowledgment for the first subscription is not getting through, ie "stuck flow"), gall (an old subscription is not getting cleaned up? or something else?), or the app itself mismanaging subscriptions. Since it happens for both chat and publish, it's less likely to be the application, but it's possible that it's just doing the same pattern.
> 
> Unfortunately, I'm not sure when someone will have a chance to deal with this. Since it affects so many people, it should be a high priority.
> 
> Does anybody have a consistent reproduction (ie a way to cause this to happen from a fresh ship)?
> If not, some of the recent debugging tools we've built should be helpful for this, so could someone who has this problem send me their pier (philip at tlon io)? I won't run it on the live net, so you don't have to keep your pier off (do turn it off while copying it, of course). It's preferable if it can be a ship that hasn't been running for too long, but anything will do.

fyi this happened to me on a fresh planet today. I commented over here with a log  - https://github.com/urbit/urbit/issues/2040#issuecomment-624930164

**Comment by sopmep-malpub** [comment] 2020-05-13 13:23
I'm wondering what a "normal" amount of output for `timers` should be. When I run `+timers`, I get nearly 4,000 lines of output. Is there some way to clear out this backlog?

**Comment by wderose** [comment] 2020-07-05 22:46
My ship is also looping on `subscribe wire not unique` and want to share my info:
```
subscribe wire not unique
%chat-hook
/mailbox/~ragtec-dispel/star-admin
[p=~ragtec-dispel q=%chat-hook]
error in %chat-hook
%watch-not-unique
! subscribe wire not unique
! %chat-hook
! /mailbox/~ragtec-dispel/star-admin
! [p=~ragtec-dispel q=%chat-hook]
\/%contact-hook: received 2nd watch-ack on [[i=%~.out t=[i=~.~ragtec-dispel t=[i=~.contact-hook t=/contacts/~ragtec-dispel/star-admin]]] [p=~ragtec-dispel q=%contact-hook] /contacts/~ragtec-dispel/star-\/
  admin]
\/                                                                                                                                                                                                        \/
\/%contact-hook: received 2nd watch-ack on [[i=%~.out t=[i=~.~ragtec-dispel t=[i=~.contact-hook t=/contacts/~ragtec-dispel/star-admin]]] [p=~ragtec-dispel q=%contact-hook] /contacts/~ragtec-dispel/star-\/
  admin]
\/                                                                                                                                                                                                        \/
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
error in %permission-hook
%fact
! closing subscription
! nest-fail
< ... omitted ... >
error in %group-hook
%fact
! closing subscription
! nest-fail
^Z
[received keyboard stop signal, exiting]
```

Info:
```
urbit 0.10.4
loom: mapped 2048MB
lite: arvo formula 56587b84
lite: core 715fdde3
lite: final state 715fdde3
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/874.807.296
boot: installed 262 jets
work: play 163820835

> +trouble
[ [%base-hash 0vs.9288r.bdja5.ic2br.jigbg.0kduq.stbiu.npcsj.mtsk0.dhf80.l4gq1]
  [%home-hash 0vf.rb91p.nkkml.a6nkd.3uis0.5vsrn.rboje.f8f39.2tsn4.fsm0b.7i6j3]
  [%our ship=~lopdev point='16307' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~dev point='179' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by matildepark** [comment] 2020-08-06 18:50
@wderose FWIW you may want to try 0.10.8, I believe 0.10.5 fixed some issues with key propagation that would prevent connectivity (though some engineers may correct me if that only affects first boot?). You also seem to have some issue with permission-hook not being configured to allow you to join a chat, which should be fixed as of new group store. (Also your comment appears to do with Chat, not Publish, which complicates potential causes.)

For all prior commenters, this ticket originated before a Publish rewrite that deployed in March; some of these issues are related to breached owners' content, some are related to Ames or Gall (hopefully fewer after the PR made earlier in the ticket). It's unclear how many of these comments are related; or have been resolved, silently; and how many found resolution after new Groups streamlined the join flow and incidents where permission-store and group-store were out of sync.

We're working on streamlining the subscription logic into a single library; and of course migrating our applications into one store. I do encourage you to continue to share incidents here if they recur in the meantime. But ensure you are running the latest binary; check your +trouble base or kids hash against https://www.whatsthelatestbasehash.com/; and let us know if this persists. For bulletin board, it should now be as easy as joining Urbit Community and pressing 'join' beside the notebook, for a new ship.

**Comment by matildepark** [comment] 2020-08-06 21:34
Related issues at the time of the ticket's opening: #2511, #2509. And again, for those since — consider filing a fresh ticket so we can separate these cases and debug them independently with you.

**Closed by matildepark** 2020-08-06 21:34 UTC
Labels: connectivity, landscape, publish
