### ISSUE TITLE
Unread notifications not being cleared

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#1633] opened 2019-08-20 20:54 UTC
On some of my chat channels, there's an indicator for new messages and I can't tell how to clear it.  I'm guessing there were a few messages from long ago that I didn't read, so they didn't get cleared.  If that's the case, then we should add logic that says "if I read message `n`, mark all messages less than or equal to `n` as read".

An acceptable workaround would be a "mark as read" button.

**Comment by Fang-** [comment] 2019-08-20 21:32
Probably a duplicate of #1388 ?

**Comment by vvisigoth** [comment] 2019-08-20 21:36
@loganallenc

**Comment by vvisigoth** [comment] 2019-09-10 00:55
This is being addressed in @loganallenc 's rewrite of chat.

**Comment by jtobin** [comment] 2019-12-20 15:19
I'm going to close this as it pertains to the deprecated :talk / :hall, and has likely been resolved.

**Closed by jtobin** 2019-12-20 15:19 UTC
Labels: bug, landscape
