### ISSUE TITLE
Server dropping TCP connection causes cttp.c to hang instead of giving 504 to %eyre

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#784] opened 2016-11-01 19:29 UTC
To reproduce, run `nc -l 1111` in a separate shell, in `:dojo` `+http://localhost:1111`, and `^D` the `nc` process after it receives the HTTP headers. The Urbit request will hang indefinitely, across `vere` reboots, until a different request to the same host completes. Desired behavior would be a 504 upon detecting that the underlying TCP socket has closed.

(The majority of this issue has been split out into #838, which aborts instead of hanging, and is less consistently reproducible. This issue has been edited down to step "3." of the old list of cases)

This is the likely source of [`%eyre` getting stuck on `vi-pump-blocked`](http://urbit.org/fora/posts/~2017.4.17..04.07.40..a663~/). If the 504 was generated, the request could possibly be retried a couple times, with persistent errors being returned to the API requester.

**Comment by hoclun-rigsep** [comment] 2017-02-05 20:55
Update running fakezod with urbit/f5c877a and ohAitch/mark-dashboard (c96d6de):

First time I tried to produce type 3 error, vere dumped core with something about a linked list (lost in scrollback, doh!) 

Haven't been able to reproduce core dump. Subsequent behavior is inconsistent. First attempt at a normal +http  fails with `[%dojo-lame %sigh-httr]` but then seems to work after that. More type 3 runs get me `%dy-no-prompt` and

     [ %ford-mystery
    ~[
     /g/~zod/use/dojo/~zod/inn/hand
     /g/~zod/use/hood/~zod/out/dojo/drum/phat/~zod/dojo
     /d
     //term/1
     ]
    ]

I just got an `out of loom` crash running `+http://localhost:1111` as well but this is not consistent. At least once this happened without `nc` listening.

**Comment by joemfb** [comment] 2019-01-18 07:02
Closing as obsolete, %eyre receives a 504 when `nc` is closed in this test scenario.

**Closed by joemfb** 2019-01-18 07:02 UTC
Labels: %eyre, bug

**Comment by ohAitch** [comment] 2019-01-18 07:04
:D

#838 is definitely also fine right?

**Comment by joemfb** [comment] 2019-01-18 07:12
I can't reproduce any crashes in those scenarios. Can you?
