### ISSUE TITLE
chat: messages repeating, scroll position jumps

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#2508] opened 2020-03-14 19:40 UTC
**Describe the bug**

While reading the subset of the backlog that chat will show to me (scroll position somewhere in the middle), new messages loading at the bottom of the page causes the scroll position to jump unpredictably. Additionally, some of the new messages were rendered multiple times. 

**To Reproduce**

I'm not sure how to reproduce.

**Expected behavior**

New messages should load once, without affecting the scroll position while reading the backlog.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome 79.0.3945.130 
 - Base hash of your urbit ship. 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl

**Additional context**

#2105 persists. Most of the time, more backlog does *not* load for me when I scroll to the top of the chat window. Occasionally, it does load.

**Comment by vvisigoth** [comment] 2020-03-19 16:25
@matildepark backlog not loading aside, is this a dupe of https://github.com/urbit/urbit/issues/1999 ?

**Comment by matildepark** [comment] 2020-03-19 16:26
I think it's related to our weird scroll height problems.

**Comment by loganallenc** [comment] 2020-03-31 18:22
Scroll position still jumps on mobile with the latest scroll OTA, but messages are no longer repeated.

**Comment by loganallenc** [comment] 2020-04-21 22:14
This particular issue was specfic to the OTA and won’t recur.

**Closed** 2020-04-21 22:14 UTC
Labels: OS1, chat, landscape
