### ISSUE TITLE
Deleted notebook remains in sidebar

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#4231] opened 2021-01-06 14:26 UTC
**Describe the bug**
I created a notebook, realized I didn't want it, and now it remains in my sidebar. I can try to join it, but it spins forever.

**To Reproduce**
1. Create a notebook in a group
2. Delete it

**Expected behavior**
To never see the notebook again

**Screenshots**
<img width="272" alt="Screen Shot 2021-01-06 at 6 24 21 AM" src="https://user-images.githubusercontent.com/1467211/103779124-25cb0080-4fe8-11eb-8875-3ffaef2dba04.png">

**Comment by Fang-** [comment] 2021-01-06 15:01
Looks like a duplicate of #4160.

**Comment by matildepark** [comment] 2021-01-06 15:24
Duplicate of #4160.

**Closed by matildepark** 2021-01-06 15:24 UTC
Labels: landscape
