### ISSUE TITLE
Builds for libs included in dojo fail silently

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1547] opened 2018-08-30 15:12 UTC
In the dojo, including a library that has compilation errors with `/+` and then trying to invoke it results in a `-find` error. If you evaluate `.`, you will see a stack trace `tang` got added to the subject. It just doesn't get printed for you, like it used to.

**Comment by joemfb** [comment] 2020-07-01 00:29
Looks to be a duplicate of #1452.

/cc @belisarius222

**Comment by belisarius222** [comment] 2020-07-01 00:30
Yes, it is.  Closing.

**Closed by belisarius222** 2020-07-01 00:30 UTC
