### ISSUE TITLE
July 23rd/22nd OTAs both wiped most of my Publish subscriptions

### ISSUE THREAD

**Issue by nrhtr** [urbit/urbit#3151] opened 2020-07-23 00:29 UTC
**Describe the bug**
The last two OTAs seem to have applied cleanly, except for the fact that many of my Publish subscriptions no longer show up in Landscape. After the first OTA, I re-joined a few but this latest OTA has wiped them again.

I still have all my group memberships, and this only appears to affect the Publish app. Rejoining each of the notebooks works to resolve this but it's a pain.

**To Reproduce**
1. Have Publish subscriptions.
2. Get an OTA
3. Notice missing notebooks.

**Expected behavior**
Publish subscriptions should not disappear.

**Screenshots**

Only a few UC notebooks remain. I'm not sure why these ones in particular. I think it was the same set that survived the last OTA, also.

<img width="261" alt="Screen Shot 2020-07-23 at 10 16 05 am" src="https://user-images.githubusercontent.com/74261/88241728-4e776c00-ccce-11ea-9b08-7769dfbeddde.png">

Chrome dev console:

<img width="622" alt="Screen Shot 2020-07-23 at 10 25 16 am" src="https://user-images.githubusercontent.com/74261/88241880-d493b280-ccce-11ea-9a6d-bbb8239e1a5d.png">

My group memberships:

<img width="214" alt="Screen Shot 2020-07-23 at 10 26 36 am" src="https://user-images.githubusercontent.com/74261/88241959-14f33080-cccf-11ea-8285-c286aa068085.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome
 - Base hash: The dojo command returns **0v0**, but Landscape shows **cbsa1**

**Additional context**

**Comment by matildepark** [comment] 2020-09-29 18:08
Dupe of #3079.

**Closed by matildepark** 2020-09-29 18:08 UTC
Labels: landscape
