### ISSUE TITLE
|rein - can't start multiple agents not on manifest

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit#5416] opened 2021-11-11 11:27 UTC
**Describe the bug**
I've got a couple of agents I've added to `%base` on a fakezod - `pokeme.hoon` and `pokeit.hoon`, and when I run `|rein %base [& %pokeme] [& %pokeit]` it only starts the last one (and stops the first if it's already running).

**To Reproduce**
Steps to reproduce the behaviour:
1. add a couple of agents to `%base`
2. try start them both with rein
3. observe only the last one get started

**Expected behaviour**
should be able to force start multiple agents not already on manifest

**System (please supply the following information, if relevant):**
 - OS: Arch linux
 - Vere v1.7
 - Your ship's `%base` hash 0v1a.4e05m.1ua85.9aujj.9hf8i.545rk.rsh2o.pbpnq.5nfu0.sgdea.0pn02

**Comment by Fang-** [comment] 2021-11-11 14:43
Should be fixed by #5407 once that gets released.

**Comment by sidnym-ladrut** [comment] 2022-06-18 02:59
Ping @tinnus-napbus, @Fang-: it looks like this can be closed.

**Comment by Fang-** [comment] 2022-06-18 08:30
Confirmed. Other issues with `|rein` still afoot though.

**Closed by Fang-** 2022-06-18 08:30 UTC
Labels: bug
