### ISSUE TITLE
Notifications dot when there are no notifications

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#4002] opened 2020-11-23 17:54 UTC
**Describe the bug**
I often see the notifications dot when there aren't actually any unread notifications.

**To Reproduce**
I can't figure out a completely reliable reproduction for this. It *seems* like what happens is that it always works after a refresh. Notifications are cleared when read, the tile indicators are correct. 

Then, at some point, the dot stops going away and the tile indicators seem stuck. I haven't closed my laptop or disconnected. It seems to reliably happen after having Landscape open for a bit.

**Expected behavior**
The dot should reflect unreads in the notifications screen.

**Screenshots**
<img width="1073" alt="Screen Shot 2020-11-23 at 9 51 48 AM" src="https://user-images.githubusercontent.com/1467211/99997363-ed41d100-2d71-11eb-902c-cb4f3fe080ea.png">
<img width="1073" alt="Screen Shot 2020-11-23 at 9 52 11 AM" src="https://user-images.githubusercontent.com/1467211/99997374-f03cc180-2d71-11eb-94b3-cba1d80321a7.png">

**Comment by matildepark** [comment] 2020-11-23 17:55
Duplicate of #3977.

**Closed by matildepark** 2020-11-23 17:55 UTC
Labels: landscape
