### ISSUE TITLE
lost urbit-help backlog on OTA

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2461] opened 2020-03-13 05:14 UTC
My urbit-help backlog ended at ~2020.2.21, and then picked up again after OTA -- and actually after the first message I sent post-OTA, which doesn't show up for me, but ~wicdev reported that he saw on his ship.

**Comment by joemfb** [comment] 2020-03-13 06:10
I haven't tracked down the dates yet, but appear too have had a similar OTA-update experience.

**Comment by loganallenc** [comment] 2020-03-13 06:51
Did your subscriptions eventually establish properly and send down messages when expected?

**Comment by belisarius222** [comment] 2020-03-13 16:00
New messages come in fine.  I think my ship actually received the "missing" backlog in the CLI just after OTA, but the old messages never showed up in web chat.

**Comment by loganallenc** [comment] 2020-03-13 16:36
I saw that too on my ship (like three messages that got to cli and not web) and am unsure of why or how that could happen.

**Comment by loganallenc** [comment] 2020-03-31 18:25
Closing as this was an OTA issue.

**Closed by loganallenc** 2020-03-31 18:25 UTC
Labels: OS1, chat

**Comment by ohAitch** [comment] 2020-03-31 21:52
Do we know the cause of it, or is it a reasonable assumption that it'll
recur on some future OTAs?
