### ISSUE TITLE
loom corruption on next/vere

### ISSUE THREAD

**Issue by mrdomino** [urbit/urbit#5565] opened 2022-01-26 02:34 UTC
**Describe the bug**
Piers created on `next/vere` as of e4616828c1b07274ec1508dc3177814921040343 encounter loom corruption after significant use.

**To Reproduce**
Steps to reproduce the behaviour:
1. `nix-build -A urbit`
2. `[…]/urbit -F zod -B bin/solid.pill`
3. Exit process with `C-d`, then restart vere
4. `|mount %`
5. Exit process with `C-d`
6. `[…]/urbit zod`, which fails with: `Assertion '!"loom: corrupt"' failed in noun/allocate.c:144`

**System (please supply the following information, if relevant):**
 - OS: noticed on macOS (M1 arch)

**Notify maintainers**
@joemfb @mcevoypeter 

EDITED: fixed repro instructions

**Comment by mcevoypeter** [comment] 2022-01-26 16:10
I'm unable to reproduce on Arch Linux (arch: x86_64, kernel: linux-hardened 5.15.16). @mrdomino, could you attach the corrupt pier here so I can take a closer look?

**Comment by joemfb** [comment] 2022-01-26 16:14
My m1 mac has a larger page size:

```
$ getconf PAGESIZE
16384
```

I'm running my actual planet on it, no idea why it hasn't blown up yet.

**Comment by mrdomino** [comment] 2022-01-26 17:55
Pier is here: https://www.wholezero.org/zod.tar.gz

We determined that vere is also using 16384 page size; further discussion in Tlon infra channel starting here:

<web+urbitgraph://group/~dabben-larbet/tlon/graph/~bolbex-fogdys/infrastructure/170141184505464113661579382635972526080>

**Comment by mrdomino** [comment] 2022-01-26 18:01
My repro instructions were incorrect; you have to shut down once after initial boot, then start up, then `|mount %`, then shut down again. Then on next boot the loom is corrupt.

**Comment by mcevoypeter** [comment] 2022-01-26 19:39
Using the amended repro instructions, I'm able to reproduce locally with a system page size of 4K.

**Comment by mcevoypeter** [comment] 2022-01-27 18:36
### Current strategy <a href="current"></a>

If the snapshot contains no pages on boot, then we mark all pages in the loom
as dirty. No write protections are applied and so the entire loom is also
writable at this point. This means that the first snapshot will contain *all*
pages in the home road regardless of whether each page was written or not.

A page will only become write-protected if it's:
1. destined for the snapshot i.e. saved to the patch file in
`_ce_patch_save_page()`, which is invoked for each dirty page when a snapshot
is taken.
2. restored from the snapshot in `_ce_image_blit()`.
This means that we never enable write protections on the majority of pages
because the only pages that fulfill either of these criteria are those pages
that lie within the bounds of the home road when the first snapshot is taken.

All pages are marked as dirty upon the first boot (i.e. when the snapshot is
empty), but on all subsequent boots, the only way that a page is marked dirty
is by `u3e_fault()`, which will only run for a given page if that page was
written *and* and that page was write-protected. Unfortunately, only pages that
are in the initial snapshot will ever become write-protected, so we're only
tracking a subset of the pages.

This, by the way, likely explains the "loom: corrupt" error that occurs on a
boot subsequent to running `|mount %`: a page restored from the snapshot
refers to a page that *should* have been in the snapshot but which isn't because
it was never write-protected, never marked as dirty, and therefore never ended
up in the snapshot.

A solution to this problem would be to mark all pages in the loom as dirty on
every boot--not just on boot when the snapshot is empty--but then our system
degrades to simply saving every page in the home road to the snapshot when it's
taken, which would make the use of the page tracking system obsolete.

### Previous strategy

When descending into the outermost inner road from the home road in `u3m_leap()`, we disable write protections on all inner road pages. When ascending to the home road in `u3m_fall()`, we enable write protections on all clean pages in the loom.

This strategy does not yield a corrupt loom when using the command sequence that
corrupts the loom using the [current stragetgy](#current).

**Comment by joemfb** [comment] 2022-01-27 19:14
Thanks for investigating and writing this up.

> the first snapshot will contain all pages in the home road regardless of whether each page was written or not.

This isn't quite right: the snapshot is split into two segments (stack, heap), bounded by the appropriate road pointers (see calls to `u3m_water()`). So it'll include all used pages, but contiguous free space in the middle is not saved.

I think the bug is that we're not marking that contiguous free space as dirty when we restore a snapshot, but only on first boot (see my original proposal comment: https://github.com/urbit/urbit/pull/5477#issuecomment-997160929).  We should unconditionally call `u3e_foul()` in `u3e_live()`, before attempting to restore the snapshot (which will protect pages and and mark them clean).

This is my fault, I failed to notice that we weren't doing this in my code review.

**Comment by joemfb** [comment] 2022-01-27 19:44
Just tested this out, and I can no longer reproduce. I'll PR the change.

**Comment by mcevoypeter** [comment] 2022-01-27 19:50
Did you simply pull `u3e_foul()` out of the if statement in `u3e_live()`? I did (and modified `u3e_fault()` to ignore already dirty pages), and I'm stuck on an infinite loop at boot:
```console
[nix-shell:~/code/urbit_]$ urbit zod                                         
~                                                                                                                                                          
urbit 1.8                                                                                                                                                  
boot: home is /home/peter/code/urbit_/zod                                                                                                                  
loom: mapped 2048MB                                                                                                                                        
lite: arvo formula 27e494c5                                                                                                                                
lite: core 7b144622                                                          
lite: final state 7b144622                                                                                                                                 
loom: mapped 2048MB                                                                                                                                        
boot: protected loom                                                                                                                                       
live: loaded: MB/265.945.088     
```

**Comment by joemfb** [comment] 2022-01-27 20:06
I pulled it out of the conditional and moved it above snapshot restoration. No need to modify the fault handler.

**Comment by mrdomino** [comment] 2022-02-03 05:09
Been running with #5572  on a few ships across M1 mac and raspberry pi, no issues so far.

**Comment by joemfb** [comment] 2022-06-04 02:34
Closing as fixed.

**Closed by joemfb** 2022-06-04 02:34 UTC
Labels: bug
