### ISSUE TITLE
Negative number for notifications in browser tab

### ISSUE THREAD

**Issue by deploradude** [urbit/urbit#4311] opened 2021-01-20 13:39 UTC
**Describe the bug**

I have a negative number of notifications in my browser banner.

**To Reproduce**

Browser.

Nothing

Don't need to.

**Expected behavior**

Expect to have a minimum of zero notifications.

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also screenshot your browser's dev console. Here are [Chrome's docs](https://developers.google.com/web/tools/chrome-devtools/open) for using this feature.

![image](https://user-images.githubusercontent.com/66261425/105181802-4328c000-5afa-11eb-8100-638b3ceea93e.jpeg)

![image](https://user-images.githubusercontent.com/66261425/105181812-4754dd80-5afa-11eb-88f8-f686fc9749c2.png)

![image](https://user-images.githubusercontent.com/66261425/105181825-4b80fb00-5afa-11eb-9d44-64a4ae6b1cfa.png)

![image](https://user-images.githubusercontent.com/66261425/105181848-50de4580-5afa-11eb-8116-8115fe1b83a6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 10.15.3]

Mac 11.1

Brave 1.18.78

 - Base hash of your urbit ship. Run `+trouble` in Dojo to see this.

Base: ago33

home: 241j9

**Smartphone (please complete the following information):**
 - Base hash of your urbit ship. Run `+trouble` in Dojo to see this.

**Additional context**

**Comment by matildepark** [comment] 2021-01-20 16:36
Duplicate of #4295.

**Closed by matildepark** 2021-01-20 16:36 UTC
