### ISSUE TITLE
Checkpoint corruption and unreliable replay failures

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#6053] opened 2022-11-04 22:10 UTC
On replay of a particular ship (pier available), the checkpoints were corrupted. The bhk checkpoints also failed and so the entire ship needed to be replayed from the beginning. When a replay fails, because the replay is not incrementally written to disk, it must be completely started over. This results in having to batch replay in smaller and smaller batches until the stop failing. Eventually in this case, I was able to replay the ship 1m events at a time.

@zalberico

**Comment by zalberico** [comment] 2022-11-04 22:32
Thanks @baudtack I edited the title to be more explicit - I'd also like to flesh these out more with specific details of what went down and generally try to do this in future issue reports too.

> On replay of a particular ship (pier available), the checkpoints were corrupted. The bhk checkpoints also failed and so the entire ship needed to be replayed from the beginning.

- What was the nature of the initial failure?
- Do we have info about what it looked like when you trying to start it up? 
- About what lead to or caused the failure?
- How did you know the checkpoints were corrupted, when you tried each of them what was the output?

> When a replay fails, because the replay is not incrementally written to disk, it must be completely started over. This results in having to batch replay in smaller and smaller batches until the stop failing. Eventually in this case, I was able to replay the ship 1m events at a time.

I think this is a good hypothesis, but want more of specifics of what happened in case we're wrong.
 - What do you do to replay the ship? What specific command?
 - When it fails how does it fail? What does it output?
 - When you batch it, how are you batching it (specifically what arg?)
 - How long does it take for each section and in total?

In this specific case it also looked like eleanor was missing channels in her group when it came back online? Was that expected or did it not entirely recover?

There are a few things we want out of this one:
1. What failure caused the ship to need to be replayed in the first place so we can fix that.
2. Checkpoints should not corrupt themselves and we want to know why and fix that.
3. When replaying without checkpoints, that should not require a human to manually batch - it should be running a single command and allowing it to complete.

@mcevoypeter had mentioned this may be the cause of the corrupt checkpoints: https://github.com/urbit/urbit/pull/6003 but that's only one of the three things in this case.

**Comment by mcevoypeter** [comment] 2022-11-05 22:52
> When replaying without checkpoints, that should not require a human to manually batch - it should be running a single command and allowing it to complete.

As far as I understand it, the reason that we have to replay in batches is because there is no single binary that's suitable for playing an entire event log due to jet mismatches[^1]. As a result, we have to replay a portion of a ship's event log until replay fails, then continue on from the created checkpoint with the next suitable version of the binary. @joemfb is the person to talk to about this if you need more details.

[^1]: "Jet mismatch" is a vague term, one that I still don't have a good explanation for.

**Comment by mcevoypeter** [comment] 2022-11-05 22:54
As an aside, I use "checkpoint" and "snapshot" interchangeably, although I prefer the latter whenever possible.

**Comment by joemfb** [comment] 2022-11-06 00:24
This batching is not the binary switching from jet mismatches, but partial replay with `-n` to work around `bail:meme` and related error conditions. The fix for this is "replay error handling", planned and tracked internally.

A jet mismatch is the condition in which a given jet does not correctly implement the operation specified by the nock formula which it accelerates -- ie, a jet which computes the wrong result for some input.

**Comment by joemfb** [comment] 2022-11-06 00:26
I should further note that fully general replay error handling depends on a memory-efficient meld, among other things. But much can be done without that.

**Comment by zalberico** [comment] 2022-11-06 19:51
> As far as I understand it, the reason that we have to replay in batches is because there is no single binary that's suitable for playing an entire event log due to jet mismatches[1](#user-content-fn-1-7c4fda4a19ed7a0a707ddc1893965b00).

Thanks - as @joemfb mentioned this is an additional issue that's separate from replay crashing because it runs out of memory while running.

It looks like this is related to the following:
 - #5046
 - #5836 

The summary of issues:
 - Checkpoint corruption for unknown reason
 - Replay fails because it runs out of memory (doesn't batch itself properly while running)
 - Replay requires multiple binary versions and manual intervention.

Ideally:
 - The checkpoints don't get corrupted (and we understand why they currently getting corrupted), we can take a look at the broken pier @baudtack saved for this.
 - You can run replay with a single command and it runs in a way that doesn't use up memory and crash
 - Related to above, replay handles the different require binaries automatically and is just one command to run.

> The fix for this is "replay error handling", planned and tracked internally.
@joemfb do you know where this lives internally? It's something I can formalize in an issue (probably in the new runtime repo as we start building that out).

**Comment by zalberico** [comment] 2023-02-01 00:43
We're handling this in the vere repo now.

https://github.com/urbit/vere/issues/157
https://github.com/urbit/vere/issues/187

**Closed by zalberico** 2023-02-01 00:43 UTC
Labels: bug
