### ISSUE TITLE
^d while looking at dojo command history does not quit

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#853] opened 2017-06-22 12:28 UTC
Press up arrow in the dojo to look at your previous command.

````
^d
````

Nothing happens (except bell code).

**Comment by joemfb** [comment] 2017-06-22 14:59
When the buffer isn't empty, ctrl-d forward-deletes one character. If you're at the end of a non-empty buffer, it chimes.

See here: https://github.com/urbit/arvo/blob/maint-20170614/lib/drum.hoon#L554

**Comment by Fang-** [comment] 2018-01-13 15:05
Closing because intended behavior.

**Closed by Fang-** 2018-01-13 15:05 UTC
