### ISSUE TITLE
Chat markdown PR broke emoji rendering 😰

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#2828] opened 2020-04-30 04:19 UTC

**Comment by matildepark** [comment] 2020-04-30 04:56
Can't reproduce

![image](https://user-images.githubusercontent.com/20846414/80673484-6055c400-8a7d-11ea-8746-86106a06442b.png)

**Comment by loganallenc** [comment] 2020-04-30 05:49
![image](https://user-images.githubusercontent.com/1377557/80676457-c7c34200-8a84-11ea-959f-4e27108a5f76.jpeg)

**Comment by loganallenc** [comment] 2020-04-30 05:58
On mobile

**Comment by liam-fitzgerald** [comment] 2020-04-30 06:27
codemirror doesn't seem to play nice with iOS. Hopefully when indigo-react components land, we can swap it out for the MarkdownEditor.

**Comment by matildepark** [comment] 2020-04-30 14:45
That’s ... also codemirror though

**Comment by matildepark** [comment] 2020-07-13 18:16
From [CodeMirror release notes](https://codemirror.net/doc/releases.html), as of 5.55.0 / June 21:

- The editor no longer overrides the rendering of zero-width joiners (allowing combined emoji to be shown).

Next release of Landscape should patch this since we `npm install` on release.

**Comment by matildepark** [comment] 2020-07-23 14:07
Unfortunately still an issue, so I was wrong about that potential remedy.

**Comment by matildepark** [comment] 2020-10-23 02:56
Fixed in #3774.

**Closed by matildepark** 2020-10-23 02:56 UTC
Labels: chat, landscape
