### ISSUE TITLE
:publish stack traces on subscribe

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2463] opened 2020-03-13 05:20 UTC
I think the subscription succeeded, since I can see at least one post in the notebook, but this did happen.

```
[%mailbox-kick i=%~.mailbox t=[i=~.~minder-folden t=/welcome]]
error in %publish
%arvo-response
! /~rovnys-ricfer/home/0/lib/default-agent/hoon:<[63 3].[63 5]>
! 
  \/"unexpected system response %g to %publish on wire /out/~littel-wolfur/publish/colle\/
    ction/the-furtive-fang"
  \/                                                                                    \/
! /~rovnys-ricfer/home/0/lib/default-agent/hoon:<[62 3].[63 5]>
! /~rovnys-ricfer/home/0/app/publish/hoon:<[370 7].[370 28]>
! /~rovnys-ricfer/home/0/app/publish/hoon:<[369 5].[403 7]>
! /~rovnys-ricfer/home/0/app/publish/hoon:<[368 5].[403 7]>
! /~rovnys-ricfer/home/0/lib/dbug/hoon:<[112 23].[112 50]>
! /~rovnys-ricfer/home/0/lib/dbug/hoon:<[112 5].[113 17]>
! /~rovnys-ricfer/home/0/lib/dbug/hoon:<[111 5].[113 17]>
! /~rovnys-ricfer/home/~2020.3.13..03.45.04..b671/sys/vane/gall:<[1.213 9].[1.213 47]>
error in %publish
%arvo-response
! /~rovnys-ricfer/home/0/lib/default-agent/hoon:<[63 3].[63 5]>
! 
  \/"unexpected system response %g to %publish on wire /out/~littel-wolfur/publish/colle\/
    ction/the-furtive-fang"
  \/                                                                                    \/
! /~rovnys-ricfer/home/0/lib/default-agent/hoon:<[62 3].[63 5]>
! /~rovnys-ricfer/home/0/app/publish/hoon:<[370 7].[370 28]>
! /~rovnys-ricfer/home/0/app/publish/hoon:<[369 5].[403 7]>
! /~rovnys-ricfer/home/0/app/publish/hoon:<[368 5].[403 7]>
! /~rovnys-ricfer/home/0/lib/dbug/hoon:<[112 23].[112 50]>
! /~rovnys-ricfer/home/0/lib/dbug/hoon:<[112 5].[113 17]>
! /~rovnys-ricfer/home/0/lib/dbug/hoon:<[111 5].[113 17]>
! /~rovnys-ricfer/home/~2020.3.13..03.45.04..b671/sys/vane/gall:<[1.213 9].[1.213 47]>
```

**Comment by belisarius222** [comment] 2020-03-13 05:26
Here's another stack trace, when I subscribed to another notebook.  Not sure if related.
```
  out
{ [   p
    [ wire=/subscribe/~sicbud-hathes/salvation-in-digital-heaven
      ship=~sicbud-hathes
      term=%publish
    ]
    q=[acked=%.n path=/notebook/salvation-in-digital-heaven]
  ]
  [ p=[wire=/collection/urbit-pi ship=~botter-nidnul term=%publish]
    q=[acked=%.y path=/collection/urbit-pi]
  ]
  [ p=[wire=/collection/sigils ship=~somlus-savlev term=%publish]
    q=[acked=%.n path=/collection/sigils]
  ]
  [ p=[wire=/collection/coronavirus-journal ship=~bacret-worwyc term=%publish]
    q=[acked=%.y path=/collection/coronavirus-journal]
  ]
  [ p=[wire=/collection/urbit-nits ship=~siprel term=%publish]
    q=[acked=%.y path=/collection/urbit-nits]
  ]
  [ p=[wire=/invites ship=~rovnys-ricfer term=%invite-store]
    q=[acked=%.y path=/invitatory/publish]
  ]
  [ p=[wire=/collection/the-autistic-mercury ship=~norbet-sommud term=%publish]
    q=[acked=%.y path=/collection/the-autistic-mercury]
  ]
  [ p=[wire=/collection/tonal ship=~poldec-tonteg term=%publish]
    q=[acked=%.y path=/collection/tonal]
  ]
  [ p=[wire=/collection/history-of-mathematics ship=~pattus-malsec term=%publish]
    q=[acked=%.y path=/collection/history-of-mathematics]
  ]
  [ p=[wire=/collection/digital-liberty ship=~posput-borfes term=%publish]
    q=[acked=%.y path=/collection/digital-liberty]
  ]
  [ p=[wire=/collection/atomic-age ship=~lagrev-nocfep term=%publish]
    q=[acked=%.y path=/collection/atomic-age]
  ]
  [ p=[wire=/permissions ship=~rovnys-ricfer term=%permission-store]
    q=[acked=%.y path=/updates]
  ]
  [ p=[wire=/subscribe/~wicdev-wisryt/bulletin-board ship=~wicdev-wisryt term=%publish]
    q=[acked=%.y path=/notebook/bulletin-board]
  ]
  [ p=[wire=/subscribe/~siprel/urbit-nits ship=~siprel term=%publish]
    q=[acked=%.n path=/notebook/urbit-nits]
  ]
  [   p
    [wire=/collection/anonymous-urbit-inspired-fiction ship=~ravmel-ropdyl term=%publish]
    q=[acked=%.y path=/collection/anonymous-urbit-inspired-fiction]
  ]
  [ p=[wire=/subscribe/~littel-wolfur/the-furtive-fang ship=~littel-wolfur term=%publish]
    q=[acked=%.y path=/notebook/the-furtive-fang]
  ]
  [ p=[wire=/collection/uruk-updates ship=~siprel term=%publish]
    q=[acked=%.y path=/collection/uruk-updates]
  ]
  [ p=[wire=/collection/escape-from-takeda ship=~hastuc-dibtux term=%publish]
    q=[acked=%.y path=/collection/escape-from-takeda]
  ]
  [ p=[wire=/collection/urbit-only-exclusive-tweets ship=~palfun-foslup term=%publish]
    q=[acked=%.y path=/collection/urbit-only-exclusive-tweets]
  ]
  [ p=[wire=/collection/bulletin-board ship=~wicdev-wisryt term=%publish]
    q=[acked=%.y path=/collection/bulletin-board]
  ]
}
subscribe wire not unique
%publish
/subscribe/~sicbud-hathes/salvation-in-digital-heaven
[p=~sicbud-hathes q=%publish]
error in %publish
%watch-not-unique
! subscribe wire not unique
! %publish
! /subscribe/~sicbud-hathes/salvation-in-digital-heaven
! [p=~sicbud-hathes q=%publish]
~rovnys-ricfer:dojo> 

```

**Comment by philipcmonk** [comment] 2020-03-13 05:41
@ixv

Seeing a lot of these as well.  Somehow a `%done` is going to the app.  We need to figure out why, but also link-listen-hook just accepts these and throws them away, so we could probably do the same thing.

**Comment by matildepark** [comment] 2020-05-11 23:01
Duplicate of #2851.

**Closed by matildepark** 2020-05-11 23:01 UTC
Labels: OS1, publish
