### ISSUE TITLE
New planet generation troubles

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#828] opened 2017-03-25 21:23 UTC
Hello!

I own a star and have wanted to test out planet generation, to see how I might begin to issue planets to friends and otherwise.

I referenced the documentation [here](http://urbit.org/docs/using/shell/) which explains the syntax needed to determine a planet's key.

Using `+ticket`, I generate a new planet/key pair and use this info to initialize a planet in another console. (this entire time, the star is running).

Once I've waited several minutes for the process to end, I receive a comet, so I assume the process has failed for some reason. I tried this process several times, and have been unable to create a working planet. I've double-checked the syntax multiple times and don't appear to be misspelling anything.

Here is a gist depicting the error from the star side:
https://gist.github.com/edouerd/4b1df33c5d937db335ff055a18c6b3ec

and the console information from the planet side: 
https://gist.github.com/edouerd/258ade2643ce7f8b6fa33c2c9adbe1b9

**Comment by cgyarvin** [comment] 2017-03-25 21:42
Ray or Anton, do you see an obvious problem here?  If not, I might need to play with the star myself...

**Comment by juped** [comment] 2017-03-25 21:51
This is infuriatingly familiar - I've seen it before. But I don't remember how I fixed it and can't find it with a quick search

**Comment by galenwp** [comment] 2017-03-25 22:14
Such a strange stack trace.  I’m fairly sure people have managed to issue planets during this continuity era…

**Comment by cgyarvin** [comment] 2017-03-25 22:14
Can confirm, the error being in clay is weird

**Comment by cgyarvin** [comment] 2017-03-25 23:28
Looks like we need Edouard's star -- anyone volunteer to debug this?

**Comment by edouerd** [comment] 2017-03-27 20:13
Happy to email the star at any time, just let me know 👍

**Comment by keatondunsford** [comment] 2017-03-27 21:00
I think at least partly like this is the same error from `ames` not being synced to ~fed's new key. So everything just freaks out. It's probably the case since maybe ~bus and therefore ~sabbus aren't synced to the new ames change?

@Fang- and I were able to stop this particular ames thing from popping up by just manually changing the key ourselves in our ship.

But it's probably mostly something else of course.

**Comment by edouerd** [comment] 2017-03-27 21:03
Is there a dummy-proof outline of the steps the two of you took? i.e. which
directories to copy/paste/etc. from, in which order were steps taken, etc.

Only slightly wary of having star and planet crash and burn! 🎊
ᐧ


↪︎ é.u.
↪︎ edouard.us

**Comment by keatondunsford** [comment] 2017-03-27 21:08
Basically it would make sense to me is ~sabbus didn't get the ames sync from ~bus or ~zod, but since you're trying to boot a planet off latest maintenance which does include the change, your star freaks out and can't talk to your planet. And so maybe the boot sequence just defaults to a comet or something (which seems weird).

Assuming your star isn't dead (it just sounds like you're getting these constant repeated `kick: lost %hear on //ames` errors, just make sure your star is mounted with `|mount %` at the Dojo, then open up `path/to/sabbus/home/arvo/ames.hoon` in whatever text editor you use. Search to find ~fed or go to line 381, and replace the line with the key `0w0` with the line here:

https://github.com/urbit/arvo/blob/maint-20160818/arvo/ames.hoon#L381

Your star should notice the change once you save the file and `|reload` the vane automatically, and the error should stop. And then you should be able to make planets that can talk to ~sabbus! But let me know if they don't.

**Comment by edouerd** [comment] 2017-03-27 21:12
Rad, thank you so much keat!

Star is in fact not dead, so here's hoping this fix works — will report
back when the surgery is complete.
ᐧ


↪︎ é.u.
↪︎ edouard.us

**Comment by keatondunsford** [comment] 2017-03-27 21:14
You bet!

**Comment by edouerd** [comment] 2017-03-27 23:30
Reporting back — the fix keaton suggested worked well, and prevented any errors from cropping up when I attempted to boot the same planet I had been attempting before. That said, after the boot sequence, I ended up with a comet, so it's looking like nothing was fixed from that end.

I issued a planet/key over to keaton and galen, and while keaton was booting a planet, I received a stack of errors you can view here:

https://gist.github.com/edouerd/1df157d86e09ec09b42609cdbc858cbf

Some additional notes from :talk —

```
~livsyx-lavmel) pasting the stack trace would be great. and just add that it
~livsyx-lavmel) popped up when i tried to boot the planet from my machine.
~livsyx-lavmel) mention though that the key sync fixed the ames thing from your
-------[11.020]
~livsyx-lavmel) original post.
```

**Comment by galenwp** [comment] 2017-03-28 22:00
Sorry we're so slow on this one.  I'll try to boot my planet this afternoon.  That stack trace is so confusing.

**Comment by edouerd** [comment] 2017-03-28 23:23
No need to apologize, I'm sure it's ever-busy around y'alls parts.

Just reporting back to let you know that sabbus will be online for a bit tonight, starting now.

Weirdly enough, as soon as ~sabbus connected to the network, it began to experience weird outputs similar to those I've already pasted.

It seems to be able to post to :talk fine though, very strange indeed.

**Comment by galenwp** [comment] 2017-03-29 19:55
Okay, this is pretty strange.  I tried booting that planet, and it basically just got stuck hanging:

https://gist.github.com/galenwp/bc8e1dd0de01779fcfd535f19d862775

The really weird thing here is:

```
ames: czar at bus.urbit.org: not found (a)
ames: czar at zod.urbit.org: not found (a)
ames: czar at bus.urbit.org: not found (a)
ames: czar at zod.urbit.org: not found (a)
ames: czar at bus.urbit.org: not found (a)
ames: czar at zod.urbit.org: not found (a)
ames: czar at bus.urbit.org: not found (a)
ames: czar at zod.urbit.org: not found (a)
```

As well as the fact that it looks like I get dropped in to a comet before this happens.  Not only am I dropped in to a comet, but I also see a `; ~sabbus is your neighbor`.

Did you see star-side errors?  I'm considering booting a star myself just to see if I can reproduce.  Hard to tell why this would be star-specific.  Maybe I should start a moon...

**Comment by edouerd** [comment] 2017-03-29 19:58
I haven't been receiving any errors other than the long stack traces that are generated (that I've been pasting as I receive them), sabbus appears to send text to ;urbit-meta and otherwise, and boots properly and hasn't exhibited any 'off' behavior.

**Comment by galenwp** [comment] 2017-03-29 19:59
Right, so you didn't see any further stack traces when I booted that planet ~24h ago?

**Comment by edouerd** [comment] 2017-03-29 20:02
Nothing whatsoever! Star is online now, and in -meta, if you'd like to speak there

**Comment by galenwp** [comment] 2017-03-29 20:33
It appears that you have a `%kids` desk, but is it synced to your `%home` or `%base`?

**Comment by edouerd** [comment] 2017-03-29 20:51
how might I go about checking that? will look at docs to see if I can find an answer before you reply

**Comment by joemfb** [comment] 2017-03-29 21:50
Sometime this afternoon, my comet printed ~60 lines of 

```
ames: czar at zod.urbit.org: not found (a)
```

I've never seen that before. But I can't imagine how it could be related ...

**Comment by galenwp** [comment] 2017-03-29 21:52
Interesting.

**Comment by joemfb** [comment] 2017-03-29 21:53
To clarify: I've seen the message, but only printed once, never in a sequence like that.

**Comment by galenwp** [comment] 2017-03-29 21:54
Printed 'once', but 60 times?

**Comment by joemfb** [comment] 2017-03-29 21:57
*needs to work on his clarifications...*

I mean that the error message is printed anytime DNS lookup fails, and, with Comcast, that happens frequently. The message only prints once on failure, and I've never seen it repeated like that until this afternoon.

**Comment by galenwp** [comment] 2017-03-29 22:13
It's okay. That makes sense now. 

It's unlikely that these things are related (a weird clay crash and this DNS thing), but maybe they are.

**Comment by jtobin** [comment] 2019-06-19 05:15
Closing as this hasn't been updated in awhile, and it's unclear whether it's still relevant.

**Closed by jtobin** 2019-06-19 05:15 UTC
Labels: confusing
