### ISSUE TITLE
omnibox doesn’t search when on iOS mobile

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#3275] opened 2020-08-11 04:25 UTC
cc @matildepark

**Comment by matildepark** [comment] 2020-08-11 04:27
Can reproduce.

**Comment by tacryt-socryp** [comment] 2020-08-11 05:08
Also, omnibox zooms in when focus is applied to the text input on iOS. Really jarring.

**Comment by matildepark** [comment] 2020-08-11 19:16
LOL you're not going to believe this — duplicate of #3278.

Viewport I'll see what needs doing.

**Closed by matildepark** 2020-08-11 19:16 UTC
