### ISSUE TITLE
seg faults when using https

### ISSUE THREAD

**Issue by botter-nidnul** [urbit/urbit#2032] opened 2019-12-05 14:37 UTC
I've gotten multiple segmentation faults, on two different planets on two different servers, that seem to only happen when I'm using landscape over https

address 0x159 out of loom!
loom: [0x36000000 : 0xb6000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
                                                  Segmentation fault

**Comment by galenwp** [comment] 2019-12-05 15:17
Yeah, this is happening to me quite persistently as well

**Comment by galenwp** [comment] 2019-12-05 15:25
And, fwiw, it doesn't happen when connecting directly to the IP without https.

**Comment by vvisigoth** [comment] 2019-12-05 17:15
@joemfb are you on this? I think you're in the best position to scope this out.

I'm going to try to run this with a debug build and see if I can crash it.

**Comment by galenwp** [comment] 2019-12-07 19:10
@joemfb I wonder whether it has something to do with the first few requests. Once @vvisigoth set up `~ravmel` with a debug build, it no longer happens.

**Comment by nrhtr** [comment] 2019-12-07 20:59
I can confirm I had 2 or 3 segfaults initially. I don't believe I've changed anything and it's now working.

**Comment by joemfb** [comment] 2019-12-07 21:47
@vvisigoth, @ravmel, do you know what commit you're running? I guess it's possible that a mere debug build made some unsafe memory access effectively safe, but I wonder if the difference is actually the IPC fixes.

**Comment by baudtack** [comment] 2019-12-12 21:54
I am also experiencing this. I notice it only actually triggers when going to the login page via https.

**Comment by joemfb** [comment] 2019-12-12 23:18
From a debugging session with @baudtack:

```
Thread 1 "urbit" received signal SIGSEGV, Segmentation fault.
0x0000000000445611 in _http_hgen_send (gen_u=0x2c4e590) at vere/http.c:440
440     vere/http.c: No such file or directory.
(gdb) info locals
h2o_u = <error reading variable h2o_u (Cannot access memory at address 0x159)>
__func__ = "_http_hgen_send"
```

Our pointer to the server's libh2o config struct is `0x159`, and dereferencing that causes the SIGSEGV. That config struct is linked to the server struct, which is linked to the connection struct, which is linked to the request struct. Something in that chain has obviously gone bad. I'll keep digging.

Thanks, @baudtack!

**Comment by joemfb** [comment] 2019-12-16 19:47
fixed in #2101

**Comment by bmavity** [comment] 2020-01-06 18:18
I'm still getting this, are we sure it's fixed?

**Comment by philipcmonk** [comment] 2020-01-06 18:51
Word on the street is this happens when you run as root -- @joemfb could that cause a problem?

Or actually, looks like 0.10.2 still hasn't gone out, so #2101 hasn't been deployed yet.

**Comment by bmavity** [comment] 2020-01-06 19:23
Ahh, excellent. I'll wait and see what happens with 0.10.2.

**Comment by seekr** [comment] 2020-03-04 03:05
so i had a planet running on a vps (with https) and it was fine. then I tried to start another planet on same vps but I'm getting Segmentation fault (core dumped)

````
~
urbit 0.10.3
boot: home is /home/sigmes/urbit-linux64-v0.10.3/xxxxxxxxxxxxxxx
loom: mapped 2048MB
lite: arvo formula 69dfe787
lite: core 31c5cfd7
lite: final state 31c5cfd7
Segmentation fault (core dumped)
`````

I'm wondering if this is related this issue

**Comment by joemfb** [comment] 2020-03-06 00:11
@seekr, this is not related, your crash is happening much earlier in the startup process.

Do you have the core file? On linux, it'd usually be in your working directory, or home directory. If you have it, we should be able to get a stack trace out of it.

**Comment by joemfb** [comment] 2020-07-24 18:15
Closing per #2101 and the absence of subsequent reports.

**Closed by joemfb** 2020-07-24 18:15 UTC
Labels: bug, vere
