### ISSUE TITLE
Mentioning an @p doesn't work if followed by punctuation

### ISSUE THREAD

**Issue by timlucmiptev** [urbit/urbit#4247] opened 2021-01-08 15:33 UTC
**Describe the bug**
If you try to write `~timluc-miptev` in chat to mention me, but follow it with a comma or other punctuation (e.g. `@timluc-miptev, what's up man?`), Landscape doesn't create the mention/notification.

**Comment by matildepark** [comment] 2021-01-08 16:37
Duplicate of #4183.

**Closed by matildepark** 2021-01-08 16:37 UTC
Labels: landscape
