### ISSUE TITLE
:begin does not accept just a country code

### ISSUE THREAD

**Issue by ERnsTL** [urbit/urbit#236] opened 2015-01-07 23:23 UTC
Greetings, I just went through :begin and was asked a few questions for the %lord form, including the country/location question.

Here is the transcript:

        Where are you?  This is totally optional, but we'd like to
        know your vague general location.  You can enter nothing at
        all, just a country code, or country and postal code.
        Location at
        invalid input
        Location at/1000

So I would conclude that :begin does not currently accept just a country code.

If you think this issue is irrelevant at this stage, feel free to close it ;-) Just posting it because on the path toward a version "1.0", also usability improvements count for user acceptance.

**Comment by gkelly** [comment] 2015-01-07 23:24
You can enter `at/`.

**Comment by cgyarvin** [comment] 2015-01-07 23:25
Thanks Garret!  Neither the current :begin flow nor the prompt
infrastructure that drives it is likely to survive much longer.  But
still...

**Comment by mattearnshaw** [comment] 2015-01-10 19:01
Duplicate of #232

**Comment by galenwp** [comment] 2015-05-17 18:32
no more country codes in begin.

**Closed by galenwp** 2015-05-17 18:32 UTC
Labels: dojo
