### ISSUE TITLE
chat: no indication of current chat in sidebar

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#1876] opened 2019-10-22 20:53 UTC
<img width="171" alt="Screenshot 2019-10-22 13 50 42" src="https://user-images.githubusercontent.com/1609955/67332023-60c04180-f4d3-11e9-80cc-e856a2aafa52.png">

**Comment by jtobin** [comment] 2019-10-24 01:25
Closing this one as a dupe of #1861.

**Closed by jtobin** 2019-10-24 01:25 UTC
Labels: chat, landscape
