### ISSUE TITLE
"swap" related bug?

### ISSUE THREAD

**Issue by 153** [urbit/urbit#4035] opened 2020-11-27 23:57 UTC
I downloaded urbit for my Slackware Linux distro. 

When I attempted to launch a comet ( `./urbit -c goatse` ), I was given an error and told to see `urbit.org/using/install/#about-swap-space`. This anchor `#about-swap-space` does not seem to exist on the page.

**Comment by tylershuster** [comment] 2020-11-28 00:30
Dupe of #3627

**Closed** 2020-11-28 01:21 UTC
Labels: landscape
