### ISSUE TITLE
Unable to run commands in dojo

### ISSUE THREAD

**Issue by ryjm** [urbit/urbit#3075] opened 2020-06-30 19:26 UTC
**Describe the bug**
Can't run anything in dojo, getting `ford: gone (+call)` when i try to do anything (even navigating to landscape). Seems like the dummy ford vane somehow got reloaded into the ship state? I was running some hood commands `|reload`, `|reboot` before this happened. Maybe they were loaded from the old ship state before the OTA?
**To Reproduce**
Steps to reproduce the behaviour:
Run `|reload %f` on a ship that was updated to the most recent OTA.

**Comment by ryjm** [comment] 2020-06-30 19:31
looking through the scroll back, it was a `|reload %f` that did it.

**Comment by belisarius222** [comment] 2020-06-30 19:36
Those commands might be broken now. I'll check. In the meantime, I wonder if we could try to save your ship by pushing down a new OTA to it. Who's your sponsor?

—
~rovnys-ricfer
https://urbit.org

**Comment by ryjm** [comment] 2020-06-30 19:37
amazing, thank you! my sponsor is ~middev

**Comment by ryjm** [comment] 2020-06-30 19:46
just confirmed that this is reproducible with `|reload %f` by running it on ~lisdun-modsup.

**Comment by ryjm** [comment] 2020-06-30 20:19
tried manually triggering an OTA by changing `%kids` in ~middev (just added a line to ford.hoon), but that doesn't seem to have helped.

**Comment by belisarius222** [comment] 2020-06-30 20:25
Are you sure your ship applied the OTA before this?  If it did, your ford.hoon should be only fifteen lines or so, instead of 6,000.

—
~rovnys-ricfer
https://urbit.org

**Comment by ryjm** [comment] 2020-06-30 20:30
yeah it definitely was applied, that's where those `ford: gone` lines are coming from.

**Comment by belisarius222** [comment] 2020-06-30 20:37
Oh, right. The strange thing here is that running a dojo command would trigger a Ford build at all. Old, pre-fusion dojo used Ford, but post-fusion dojo doesn't try to talk to Ford at all. This makes me wonder if your dojo somehow reverted to the old one, or never properly upgraded.

I wonder if we could get something like a |verb trace out of your ship by hacking the runtime ...

—
~rovnys-ricfer
https://urbit.org

**Comment by ryjm** [comment] 2020-06-30 20:43
it seems like herb sort of works, but it can't run any dojo commands:

WARNING <module> 442 - unrecognized response
<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1><p>There was an error while handling the request for &quot;/&quot;.</p><code>/~littel-wolfur/home/0/app/lens/hoon:&lt;[38 3].[63 64]&gt;<br />/~littel-wolfur/home/0/app/lens/hoon:&lt;[37 3].[63 64]&gt;<br />/~littel-wolfur/home/0/app/lens/hoon:&lt;[35 3].[63 64]&gt;<br />/~littel-wolfur/home/0/app/lens/hoon:&lt;[34 3].[63 64]&gt;<br />  /~littel-wolfur/home/~2020.6.19..07.43.31..a859/sys/vane/gall<br />  &lt;[1.287 9].[1.287 37]&gt;<br /></code></body></html>

**Comment by ryjm** [comment] 2020-06-30 20:43
That gall clay path is strange... seems like it's referencing an old version.

**Comment by ohAitch** [comment] 2020-06-30 23:14
Wait how does post-fusion dojo not talk to ford at all

Does /+ still work?

**Comment by philipcmonk** [comment] 2020-06-30 23:28
I expect you're going to need to inject a reset event, i think that's possible to do.

**Comment by philipcmonk** [comment] 2020-06-30 23:30
Or I don't know, maybe it's not?  Maybe we could inject a new hoon.hoon and maybe that'll trigger gall to send a reset?

**Comment by belisarius222** [comment] 2020-07-01 00:17
Seems worth a try.

—
~rovnys-ricfer
https://urbit.org

**Comment by ryjm** [comment] 2020-07-01 00:22
managed to break two other planets in a similar way - it seems like you can get your ship into a state where it's still using the old ford, even if your home hash is up to date. unfortunately, ran out of planets to test on. 

how would i go about injecting a new hoon.hoon? can't get it in through herb or an OTA

**Comment by philipcmonk** [comment] 2020-07-01 01:18
FWIW I recommend people never run `|reload %f` now.  `|reset` is what you want, you need the whole update to succeed or fail.

@ryjm do you have any desks mounted?

**Comment by ryjm** [comment] 2020-07-01 01:24
> FWIW I recommend people never run `|reload %f` now. `|reset` is what you want, you need the whole update to succeed or fail.
> 

worth mentioning that this can break too your ship too if you ctrl-C it

> @ryjm do you have any desks mounted?

yeah, my home desk.

**Comment by philipcmonk** [comment] 2020-07-01 01:39
Great, try downloading this file and running urbit with `-I path/to/new-hoon.event` (that's a capital i).  https://drive.google.com/file/d/1evb3aVzCqtp7a5FTzqGK7JXqF9hs7q6A/view?usp=sharing

For posterity, this is what I used to generate the file:

```
=a &mime &hoon (cat 3 ' ' .^(@t %cx %/sys/hoon/hoon))
=b [//sync/0v1i.n3o33 `task:able:clay`[%into %home | [/sys/hoon/hoon `a]~]]
.new-hoon/event b
```

I *think* if you don't have any desks mounted you can use `%$` instead of `%home`, but that would put it in `%base` before fusion, and that's not as direct.

**Comment by ryjm** [comment] 2020-07-01 02:01
Thanks! Didn't take though - tried both %$ and %home.

**Comment by philipcmonk** [comment] 2020-07-01 02:05
What happened, did it try to commit/reset/compile?  If it looks like it did nothing, you can run with `-v` to turn on `|verb` without a dojo.

**Comment by ryjm** [comment] 2020-07-01 02:08
```
injecting event: [0 %sync '0v1i.n3o33' 0]
http: live (insecure, public) on 8081
http: live (insecure, loopback) on 12322
["" %unix %into //sync/0v1i.n3o33 ~2020.7.1..02.05.36..3c5d]
["|" %pass [%c %c] [%info /both] ~[//sync/0v1i.n3o33]]
["" %unix %wake //behn ~2020.7.1..02.05.42..5eb7]
["|" %give %b %wake i=/a/pump/~master-morzod/45 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~master-morzod/45] ~[/ames]]
ames: czar zod.urbit.org: ip .35.247.119.159
["" %unix %live //http-server/0v6.ldvta ~2020.7.1..02.05.42..6381]
["" %unix %wake //behn ~2020.7.1..02.05.42..7aed]
["|" %give %b %wake i=/g/use/ping/~dev/ping-wait/~dev/~2020.7.1..02.05.22..91d5 t=~[/d //term/1]]
["||" %pass [%g %g] [[%deal [~littel-wolfur ~dev] %ping %poke] /use/ping/~littel-wolfur/out/~dev/ping/ping-send/~dev] ~[/d //term/1]]
["|||" %pass [%g %a] [%plea /sys/way/~dev/ping] ~[/g/use/ping/~littel-wolfur/out/~dev/ping/ping-send/~dev /d //term/1]]
["||||" %pass [%a %b] [%wait /pump/~dev/0] ~[/ames]]
ames: czar dev.urbit.org: ip .35.227.173.38
["" %unix %wake //behn ~2020.7.1..02.05.42..8693]
["|" %give %b %wake i=/g/use/ping/~middev/ping-wait/~middev/~2020.7.1..02.05.29..e546 t=~[/d //term/1]]
[ "||"
  %pass
  [%g %g]
  [[%deal [~littel-wolfur ~middev] %ping %poke] /use/ping/~littel-wolfur/out/~middev/ping/ping-send/~middev]
  ~[/d //term/1]
]
["|||" %pass [%g %a] [%plea /sys/way/~middev/ping] ~[/g/use/ping/~littel-wolfur/out/~middev/ping/ping-send/~middev /d //term/1]]
["||||" %pass [%a %b] [%wait /pump/~middev/4] ~[/ames]]
["" %unix %wake //behn ~2020.7.1..02.05.42..8f93]
["|" %give %b %wake i=/a/pump/~master-morzod/25 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~master-morzod/25] ~[/ames]]
["" %unix %wake //behn ~2020.7.1..02.05.42..9445]
["|" %give %b %wake i=/a/pump/~master-morzod/9 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~master-morzod/9] ~[/ames]]
["" %unix %wake //behn ~2020.7.1..02.05.43..b0cf]
["|" %give %b %wake i=/a/pump/~dev/0 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~dev/0] ~[/ames]]
["" %unix %hear //ames ~2020.7.1..02.05.43..d4f8]
["|" %give %a %done i=/g/sys/way/~dev/ping t=~[/g/use/ping/~littel-wolfur/out/~dev/ping/ping-send/~dev /d //term/1]]
["||" %give %g [%unto %poke-ack] i=/g/use/ping/~littel-wolfur/out/~dev/ping/ping-send/~dev t=~[/d //term/1]]
["|||" %pass [%g %b] [%wait /use/ping/~dev/ping-wait/~dev/~2020.7.1..02.06.13..d4f8] ~[/d //term/1]]
["|" %pass [%a %b] [%rest /pump/~dev/0] ~[/ames]]
["" %unix %wake //behn ~2020.7.1..02.05.43..e044]
["" %unix %wake //behn ~2020.7.1..02.05.43..e349]
["|" %give %b %wake i=/a/pump/~middev/4 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~middev/4] ~[/ames]]
["" %unix %hear //ames ~2020.7.1..02.05.44..0f07]
["|" %give %a %done i=/g/sys/way/~middev/ping t=~[/g/use/ping/~littel-wolfur/out/~middev/ping/ping-send/~middev /d //term/1]]
["||" %give %g [%unto %poke-ack] i=/g/use/ping/~littel-wolfur/out/~middev/ping/ping-send/~middev t=~[/d //term/1]]
["|||" %pass [%g %b] [%wait /use/ping/~middev/ping-wait/~middev/~2020.7.1..02.06.14..0f07] ~[/d //term/1]]
["|" %pass [%a %b] [%rest /pump/~middev/4] ~[/ames]]
["" %unix %blew //term/1 ~2020.7.1..02.05.45..0058]
["|" %pass [%d %g] [[%deal [~littel-wolfur ~littel-wolfur] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %wake //behn ~2020.7.1..02.05.45..0ee5]
["" %unix %wake //behn ~2020.7.1..02.05.45..120f]
["|" %give %b %wake i=/a/pump/~nortex-ramnyd/4 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~nortex-ramnyd/4] ~[/ames]]
ames: czar pub.urbit.org: ip .35.230.48.78
["" %unix %wake //behn ~2020.7.1..02.05.45..1857]
["" %unix %wake //behn ~2020.7.1..02.05.45..1b80]
["|" %give %b %wake i=/a/pump/~ragned-riplep/4 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~ragned-riplep/4] ~[/ames]]
ames: czar def.urbit.org: ip .35.230.109.40
["" %unix %wake //behn ~2020.7.1..02.05.45..202e]
["|" %give %b %wake i=/a/pump/~dolsep-sarpem/0 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~dolsep-sarpem/0] ~[/ames]]
ames: czar feb.urbit.org: ip .34.82.25.47
["" %unix %wake //behn ~2020.7.1..02.05.45..24e9]
["|" %give %b %wake i=/a/pump/~mister-todteg/4 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~mister-todteg/4] ~[/ames]]
["" %unix %wake //behn ~2020.7.1..02.05.45..29b4]
["|" %give %b %wake i=/a/pump/~dolsep-sarpem/4 t=~[/ames]]
["||" %pass [%a %b] [%wait /pump/~dolsep-sarpem/4] ~[/ames]]
["" %unix %wake //behn ~2020.7.1..02.05.45..2e2d]
```
and then a bunch of ames stuff

**Comment by philipcmonk** [comment] 2020-07-01 02:27
Hmm, most likely your clay has a queue that it can't get through.  I tried creating an event to force reset the arvo kernel from outside arvo, but it looks like we don't actually have a way to do that.  IMO that would be a good feature.

I'm not sure if there's a way out of this except a breach.  The problem with the old Ford Turbo system was updates would sometimes be partially applied, which is what Ford Fusion prevents.  But Turbo got one last laugh.

**Comment by ryjm** [comment] 2020-07-01 02:35
damn! okay, i have a bunch of app state i'd like to export though - i can see it in the debug dashboard. if i just copy the state, is there a clever way to load it back in? could i use herb's import logic possibly?

**Comment by philipcmonk** [comment] 2020-07-01 02:39
I don't know how much scrollback you have, but do you have `gall: %rote scry failed` in it somewhere?  I just saw that in someone else's and that's what made the update fail.  On Fusion, if your app fails to update, the commit is aborted, which is usually what you want but obviously caused a problem while transitioning away from Turbo.

You mean copy the state by just putting `.` or something in the debug dashboard state inspector?  If your state is small enough to do that then yeah, you can copy that and you should be able to paste that as a noun.  Then you just need a way to load it into the new app, which will vary depending on the app.

**Comment by ryjm** [comment] 2020-07-01 02:44
perfect.

all my scrollback is lost now, but i'm pretty sure i know the culprit - i had srrs running, and with the removal of the old ford ruins it failed to compile. so i'm guessing gall tried to update it and failed, and since gall didn't have the change to update hood, running one of those commands probably used old ford and screwed with everything.

**Comment by philipcmonk** [comment] 2020-07-01 02:49
Oh yeah, that's probably it.  The solution would have been to make srrs compile and then run`|reset`, but with ford reloaded out of existence, I don't know how to do that

**Comment by philipcmonk** [comment] 2020-07-01 02:50
also @ixv and @liam-fitzgerald know more about how to preserve data across breaches

**Comment by belisarius222** [comment] 2020-07-01 02:51
Could we try replacing :srrs with a default app?  You could use the same exact code as in :invite-view.

—
~rovnys-ricfer
https://urbit.org

**Comment by philipcmonk** [comment] 2020-07-01 02:53
The problem is that he's reloaded the new dummy ford while everything else is running the old system, so pretty much anything he does turns into a failed ford message.  And we can't seem to inject stuff into clay, probably the queue got stuck (and can't |cancel without ford).

**Comment by belisarius222** [comment] 2020-07-01 02:54
As for force-reloading arvo from Vere … there is the external +load arm that the runtime can access.  It might not be too hard to add something like -I that runs that arm.  It would need to reload the vanes too, though, so I'm not sure that by itself would work...

—
~rovnys-ricfer
https://urbit.org

**Comment by belisarius222** [comment] 2020-07-01 02:56
Yeah, I'm not sure I know a way out of this, unfortunately.

—
~rovnys-ricfer
https://urbit.org

**Comment by ryjm** [comment] 2020-07-01 03:02
i'm noticing i can evaluate arbitrary hoon in the debug dashboard... could i force a reload from there? it's probably silo'd from the rest of arvo though huh...

**Comment by philipcmonk** [comment] 2020-07-01 03:03
yeah the output is just sent the browser, no way to get an IO move out

**Comment by ryjm** [comment] 2020-07-01 03:08
figured, oh well! thanks for all the help with this guys. once more into the breach...

**Comment by liam-fitzgerald** [comment] 2020-07-01 03:09
I've just run into this on my own ship (sans `%reload %f`). Managed to hack around it with `rm -rf hastuc-dibtux/home/* && cp -r ./urbit/pkg/arvo/* hastuc-dibtux/home` and then running `|commit %home` in dojo. I wonder if you put the whole desk into an event if you could save it

**Comment by sibwyl-batrep** [comment] 2020-07-01 09:25
Haven't done anything like @ryjm , but can't input anything in Dojo too...
Moreover, can’t access the landscape of the (locally) running ship. Localhost gives 404.
got the FordFusion OTA and rebooted after that. Sync was successful, but i can’t even input +trouble .

Console is all about "some-ship is ok".
But I've never get this stuff earlier:
```
acme: unable to retrieve self-hosted domain validation token via sibwyl-batrep.arvo.network. please confirm your urbit has network connectivity.
[ p=404
    q
  ~[
    [p='server' q='nginx/1.17.10']
    [p='date' q='Wed, 01 Jul 2020 07:46:00 GMT']
    [p='content-type' q='text/plain; charset=utf-8']
    [p='content-length' q='21']
    [p='connection' q='keep-alive']
  ]
  r=[~ [p=21 q='default backend - 404']]
]
acme: retrying certificate request in ~h1
```
Well, yes, vps which hosted my ship's arvo.network is dead, I know that, but I moved the ship to the local machine and everything worked fine with localhost.

**Comment by sibwyl-batrep** [comment] 2020-07-01 11:35
> I've just run into this on my own ship (sans `%reload %f`). Managed to hack around it with `rm -rf hastuc-dibtux/home/* && cp -r ./urbit/pkg/arvo/* hastuc-dibtux/home` and then running `|commit %home` in dojo. I wonder if you put the whole desk into an event if you could save it
Tried your thing, @liam-fitzgerald , (macOS Catalina, zsh) and the console gave me:
`no matches found: ./urbit/pkg/arvo/*`

**Comment by belisarius222** [comment] 2020-07-01 16:22
Instead of `./urbit/pkg/arvo/*`, you'll need to clone this git repo and use `/path/to/repo/pkg/arvo/*`.  The idea is to delete all the files in the Unix mount folder of your ship's %home desk, then copy new files into that mount folder, then tell your ship about them by running `|commit %home` in the dojo.

**Comment by sibwyl-batrep** [comment] 2020-07-01 17:12
@belisarius222 done the cloning. Removed the files, copied stuff from urbit-master.
After booting the ship replayed some events and started showing me:
```
ames: ~dopzod: hear last dupe [~dopzod 110 107 107]
ames: ~dopzod: send dupe message ack 56 ok=%.y
and similar
```
But input/dojo is still unresponsive. :(
Don't wanna breaaaaaaaach.........

**Comment by belisarius222** [comment] 2020-07-01 17:19
I wonder if we could inject an %into event with -I to tell Arvo about the new filesystem.

—
~rovnys-ricfer
https://urbit.org

**Comment by sibwyl-batrep** [comment] 2020-07-01 17:23
@belisarius222 Also tried (prior to replacing home) the @philipcmonk injection event. Didn't help either. But my log seems to be different from @ryjm one:

`ames: live on 0
injecting event: [0 %sync '0v1i.n3o33' 0]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..45c8]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..4e9a]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..5419]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..5ca9]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..6264]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..683d]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..70d9]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..768f]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..7d1c]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %blew //term/1 ~2020.7.1..15.29.12..851f]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %boat //boat ~2020.7.1..15.29.18..ad26]
["" %unix %born //newt/0ve.q8rai ~2020.7.1..15.29.18..b838]
["" %unix %born //behn/0ve.q8rai ~2020.7.1..15.29.18..b838]
["" %unix %born //http-server/0ve.q8rai ~2020.7.1..15.29.18..b838]
http: live (secure, public) on 443
http: live (insecure, public) on 80
http: live (insecure, loopback) on 12321
["" %unix %born //http-client/0ve.q8rai ~2020.7.1..15.29.18..b839]
["" %unix %blew //term/1 ~2020.7.1..15.29.18..b839]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %hail //term/1 ~2020.7.1..15.29.18..b839]
["|" %pass [%d %g] [[%deal [~sibwyl-batrep ~sibwyl-batrep] %hood %poke] /] ~[//term/1]]
["||" %give %g [%unto %poke-ack] i=/d t=~[//term/1]]
["" %unix %into //sync/0v1i.n3o33 ~2020.7.1..15.29.18..bd6b]
["|" %pass [%c %c] [%info /both] ~[//sync/0v1i.n3o33]]
["||" %pass [%c %f] [%build /commit/home/inserts] ~[/c/both //sync/0v1i.n3o33]]
["|||" %give %f %made i=/c/commit/home/inserts t=~[/c/both //sync/0v1i.n3o33]]
["||||" %pass [%c %f] [%build /commit/home/diffs] ~[/c/both //sync/0v1i.n3o33]]
["|||||" %give %f %made i=/c/commit/home/diffs t=~[/c/both //sync/0v1i.n3o33]]
["||||||" %pass [%c %f] [%build /commit/home/casts] ~[/c/both //sync/0v1i.n3o33]]
["|||||||" %give %f %made i=/c/commit/home/casts t=~[/c/both //sync/0v1i.n3o33]]
["||||||||" %pass [%c %f] [%build /commit/home/mutates] ~[/c/both //sync/0v1i.n3o33]]
["|||||||||" %give %f %made i=/c/commit/home/mutates t=~[/c/both //sync/0v1i.n3o33]]
["||||||||||" %pass [%c %f] [%build /commit/home/checkout] ~[/c/both //sync/0v1i.n3o33]]
["|||||||||||" %give %f %made i=/c/commit/home/checkout t=~[/c/both //sync/0v1i.n3o33]]
["||||||||||||" %pass [%c %f] [%build /commit/home/ergo] ~[/c/both //sync/0v1i.n3o33]]
["|||||||||||||" %give %f %made i=/c/commit/home/ergo t=~[/c/both //sync/0v1i.n3o33]]
["||||||||||||||" %give %c %note i=/d t=~[//term/1]]
[ "||||||||||||||"
  %slip
  %c
  %drip
  ~[
    /f/clay-sub/~sibwyl-batrep/home/~2020.7.1..05.54.48..f545
    /g/sys/cor/invite-hook/~sibwyl-batrep/home/~2020.7.1..05.54.48..f545
    /g/use/hood/~sibwyl-batrep/drum/home/invite-hook
    /d
    //term/1
  ]
]
[ "|||||||||||||||"
  %pass
  [%b %b]
  [%wait /drip/705]
  ~[
    /f/clay-sub/~sibwyl-batrep/home/~2020.7.1..05.54.48..f545
    /g/sys/cor/invite-hook/~sibwyl-batrep/home/~2020.7.1..05.54.48..f545
    /g/use/hood/~sibwyl-batrep/drum/home/invite-hook
    /d
    //term/1
  ]
]
`

**Comment by sibwyl-batrep** [comment] 2020-07-02 05:01
Anyway, thanks for the help to everyone. Breaching.

**Comment by matildepark** [comment] 2020-08-24 20:46
@philipcmonk @belisarius222 Seems like both parties in this ticket just ended up breaching. Closing.

**Closed by matildepark** 2020-08-24 20:46 UTC
Labels: bug
