### ISSUE TITLE
Still Can't Accept DMs

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#4241] opened 2021-01-07 15:36 UTC
**Describe the bug**
When I click "accept" on DMs, I get the spinner, but never get to he redirect screen nor the actual DM.

**To Reproduce**
1. Go to notifications
2. Click on accepts
3. Wait forever
4. Wait some more
5. Navigate away from notifications, come back later, and the DM invite is still there.

**Expected behavior**
Accept the DM, get taken to the conversation, see their message.

**Screenshots**
![image](https://user-images.githubusercontent.com/51895363/103911432-a44c9e80-50cb-11eb-87c9-01adde4ca279.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave with "open in window" bookmark
 - Base hash of your urbit ship. p24ih

**Additional context**
I tried searching around for an answer, but I haven't been breaking things as much so I haven't been as active in here as I usually am. Sorry if I missed the solution that's already been provided.

**Comment by matildepark** [comment] 2021-01-08 17:18
Isn't this a flagday thing?

**Comment by custom-jonathan** [comment] 2021-01-08 18:09
I didn't use flagday, myself. Seems like I'm not able to accept new ones from folks who might be reaching out to me for the first time (like, asking for a group invite instead of going through my public group for example).

**Comment by matildepark** [comment] 2021-01-08 18:11
Do you see anything in JS console or Dojo when you press "Accept"? I can accept DMs from randos on my ship, wondering if we have any feedback here.

**Comment by custom-jonathan** [comment] 2021-01-08 18:17
I had one DM left that I hadn't deleted. Just clicked accept. Landscape took me to Redirecting where it's been hanging out for awhile. Dojo said ~lanet is ok. Then nothing. In the browser console I see this:

```
Uncaught (in promise) /app/hark-store/hoon:<[392 7].[392 39]>
/app/hark-store/hoon:<[390 7].[392 39]>
/app/hark-store/hoon:<[584 5].[584 39]>
/app/hark-store/hoon:<[583 3].[585 39]>
/app/hark-store/hoon:<[582 3].[585 39]>
/app/hark-store/hoon:<[388 7].[392 39]>
/app/hark-store/hoon:<[386 5].[393 7]>
/app/hark-store/hoon:<[385 5].[393 7]>
/app/hark-store/hoon:<[398 10].[398 45]>
/app/hark-store/hoon:<[398 5].[398 45]>
/app/hark-store/hoon:<[397 5].[398 45]>
/app/hark-store/hoon:<[481 7].[481 30]>
/app/hark-store/hoon:<[480 5].[482 35]>
/app/hark-store/hoon:<[478 5].[482 35]>
/app/hark-store/hoon:<[476 5].[482 35]>
/app/hark-store/hoon:<[475 9].[482 35]>
/app/hark-store/hoon:<[482 5].[482 35]>
/app/hark-store/hoon:<[480 5].[482 35]>
/app/hark-store/hoon:<[478 5].[482 35]>
/app/hark-store/hoon:<[476 5].[482 35]>
/app/hark-store/hoon:<[475 9].[482 35]>
/app/hark-store/hoon:<[475 5].[482 35]>
/app/hark-store/hoon:<[473 5].[482 35]>
/app/hark-store/hoon:<[468 7].[468 45]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[469 5].[469 37]>
/app/hark-store/hoon:<[467 5].[469 37]>
/app/hark-store/hoon:<[466 5].[469 37]>
/app/hark-store/hoon:<[465 5].[469 37]>
/app/hark-store/hoon:<[461 11].[461 41]>
/app/hark-store/hoon:<[461 6].[461 41]>
/app/hark-store/hoon:<[461 5].[461 66]>
/app/hark-store/hoon:<[459 5].[461 66]>
/app/hark-store/hoon:<[458 5].[461 66]>
/app/hark-store/hoon:<[320 22].[320 39]>
/app/hark-store/hoon:<[314 5].[332 7]>
/app/hark-store/hoon:<[313 5].[332 7]>
/app/hark-store/hoon:<[274 10].[274 48]>
/app/hark-store/hoon:<[274 5].[274 48]>
/app/hark-store/hoon:<[273 5].[274 48]>
/app/hark-store/hoon:<[266 24].[266 59]>
/app/hark-store/hoon:<[265 5].[268 7]>
/app/hark-store/hoon:<[264 3].[269 15]>
/app/hark-store/hoon:<[263 3].[269 15]>
/app/hark-store/hoon:<[262 3].[275 5]>
/app/hark-store/hoon:<[261 3].[275 5]>
/sys/vane/gall/hoon:<[1.375 9].[1.375 37]>
```

**Comment by matildepark** [comment] 2021-01-08 18:26
That's just a positive assertion for read status. Kinda loud though.

**Comment by custom-jonathan** [comment] 2021-01-08 18:34
After pressing accept, I went back to my group and tried posting something. Stayed grayed out. Ran `:spider|kill` again, and there were some print outs, and then I could post again to landscape. But nothing else showed up.

**Comment by matildepark** [comment] 2021-01-08 18:35
Sounding like #4211...we're waiting for the graph from people who may be offline and it tanks your ship.

**Comment by custom-jonathan** [comment] 2021-01-08 18:36
Who are these weirdos who turn their ships off?

Good to know, though.

**Comment by gilletteonmeheleparim** [comment] 2021-01-09 22:37
who are the weirdos who keep their computers wake when they sleep

**Comment by matildepark** [comment] 2021-01-20 22:14
Treating this as a duplicate of #4211.

**Closed by matildepark** 2021-01-20 22:14 UTC
Labels: landscape
