### ISSUE TITLE
eth-watcher appears to be broken

### ISSUE THREAD

**Issue by patosullivan** [urbit/urbit#6376] opened 2023-03-07 19:49 UTC
My ship and many others are seeing this message in the dojo:

```
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[ %a
    p
  [   i
    [ %o
        p
      [ n=[p='jsonrpc' q=[%s p='2.0']]
        l=~
          r
        [   n
          [ p='error'
              q
            [%o p=[n=[p='message' q=[%s p='invalid argument 0: hex number with leading zero digits']] l=~ r=[n=[p='code' q=[%n p=~.-32602]] l={} r={}]]]
          ]
          l={}
          r={[p='id' q=[%s p='block by number']]}
        ]
      ]
    ]
    t=~
  ]
]
'revoke perms for'
'revoke perms for'
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[ %a
    p
  [   i
    [ %o
        p
      [ n=[p='jsonrpc' q=[%s p='2.0']]
        l=~
          r
        [   n
          [ p='error'
              q
            [%o p=[n=[p='message' q=[%s p='invalid argument 0: hex number with leading zero digits']] l=~ r=[n=[p='code' q=[%n p=~.-32602]] l={} r={}]]]
          ]
          l={}
          r={[p='id' q=[%s p='block by number']]}
        ]
      ]
    ]
    t=~
  ]
]
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[ %a
    p
  [   i
    [ %o
        p
      [ n=[p='jsonrpc' q=[%s p='2.0']]
        l=~
          r
        [   n
          [ p='error'
              q
            [%o p=[n=[p='message' q=[%s p='invalid argument 0: hex number with leading zero digits']] l=~ r=[n=[p='code' q=[%n p=~.-32602]] l={} r={}]]]
          ]
          l={}
          r={[p='id' q=[%s p='block by number']]}
        ]
      ]
    ]
    t=~
  ]
]
```

**Comment by justinlynn** [comment] 2023-03-07 19:49
https://etherscan.io/block/16777172 has a StateRoot with a leading zero value 0x02213ba0655933c7eccf8e768e20cc0afc1ab8d91b98b1db3ab03d9bb5aaf792 ... that block was at about t+4:48

**Comment by justinlynn** [comment] 2023-03-07 20:37
https://github.com/ethereumjs/ethereumjs-util/issues/79 is similar to the issue we're facing.

```
echo 'POST / HTTP/1.1
Host: eth-mainnet.urbit.org:8545
Content-Type: application/json
Content-Length: 104

[{"params":["0x0100062d",false],"id":"block by number","jsonrpc":"2.0","method":"eth_getBlockByNumber"}]' | nc eth-mainnet.urbit.org 8545
``
fails. However
```
echo 'POST / HTTP/1.1
Host: eth-mainnet.urbit.org:8545
Content-Type: application/json
Content-Length: 104

[{"params":["0x100062d",false],"id":"block by number","jsonrpc":"2.0","method":"eth_getBlockByNumber"}]' | nc eth-mainnet.urbit.org 8545
```
succeeds.

The fix is likely to send the minimal hex representation of the block number in a way similarly implemented in the linked ticket above.

**Comment by justinlynn** [comment] 2023-03-07 20:49
previously sync'd block 16.726.815 has hex representation 0xff3b1f, which rolls over to 0d16778797 or 0x0100062d... if we're encoding to 16-bit aligned hex that would explain that. Most blocks previously since eth_getBlockByNumber support would've been 48-bit aligned, which happens to be a minimal hex representation.

**Comment by justinlynn** [comment] 2023-03-07 21:14
I'm starting on a patch for this, will comment with PR shortly. Suspect it's circa https://github.com/urbit/urbit/blob/develop/pkg/base-dev/lib/ethereum.hoon#L977-L982

**Comment by justinlynn** [comment] 2023-03-07 21:16
@patosullivan Should I base the PR on currently released zuse or develop, given that it's blocking eth-watcher on production ships?

**Comment by arthyn** [comment] 2023-03-07 21:17
hmm probably current zuse I would think?

**Comment by justinlynn** [comment] 2023-03-07 21:21
Thanks @arthyn , will do - just to be clear which git commitish?

**Comment by arthyn** [comment] 2023-03-07 21:23
I think master always reflects the last production deploy so that should be good

**Comment by mopfel-winrux** [comment] 2023-03-07 21:33
I'm getting the following when trying to boot a new planet

```
Running with no STDIN
~
urbit 1.22
boot: home is /urbit/s**********
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.22.pill
boot: retrieving ~s********'s public keys
[%point-take-dawn %incomplete-json]
boot: failed to retrieve public keys
```

Not sure its related or not.

**Comment by Fang-** [comment] 2023-03-07 22:03
There might have been an issue with our Infura proxy. I have rebooted it, which usually resolves any weirdness with it. Not sure `%incomplete-json` is something we've seen from this exactly, but let's see what it does.

**Comment by Fang-** [comment] 2023-03-07 22:04
Infura did have some downtime recently, but nothing going on right now...

**Comment by pkova** [comment] 2023-03-07 22:17
Confirmed that booting a fresh planet works normally again.

**Comment by justinlynn** [comment] 2023-03-07 22:28
Booting fresh comet fails for me in the same way - submitted https://github.com/urbit/urbit/pull/6377 (which I'm sure is quite non-optimal - I'm new to hoon - but patched base resolves stuck eth-watcher on livenet and is a minimal patch which should not impact other users of num-to-hex or render-hex-bytes until further discussion can be had)

**Comment by justinlynn** [comment] 2023-03-07 23:54
Will this be considered for hotfix/ota release per https://github.com/urbit/urbit/pull/6377#pullrequestreview-1329673217 ? Should this issue be closed or remain open until the fix is released?

**Comment by justinlynn** [comment] 2023-03-08 00:12
Per https://github.com/urbit/urbit/pull/6378 already on ~zod and picked over into develop. Thanks all. Resolving.

**Comment by jfranklin9000** [comment] 2023-03-08 01:02
Just noting here that when you get one of these messages you actually get two at the same time.

**Comment by tinnus-napbus** [comment] 2023-03-08 01:29
confirming the deployed hotfix fixed it for me - I'm now up-to-date with the eth block

**Comment by justinlynn** [comment] 2023-03-08 01:44
@tinnus-napbus thanks, great to hear - can I ask what your ship's ota provider is?

**Comment by pkova** [comment] 2023-03-08 02:36
The `%base` hash is **0v10.q9db5.aml7l.ae1ms.bmerv.pntmp.rgaij.jd169.2mf1f.3cehv.510t6**

https://groups.google.com/a/urbit.org/g/dev/c/rGSrMzTZq9U

This should be fixed, let's leave the issue open for a little bit just in case.

**Comment by zalberico** [comment] 2023-03-08 03:02
Nice work @justinlynn 🎉

**Comment by tinnus-napbus** [comment] 2023-03-08 03:12
I get from binnec and it's `0v1p.ooo8t.nhjh4.rbaa5.a74dm.oqk5g.u73bo.6ija4.000t9.lii59.bp21m` rn @justinlynn

**Comment by justinlynn** [comment] 2023-03-08 05:06
Thank you @zalberico and @tinnus-napbus

**Comment by patosullivan** [comment] 2023-03-08 18:14
My ship is subscribed to ~marnec-dozzod-marzod and I still haven't received this update. I've got another ship that's subscribed directly to ~zod and it hasn't received it. Did this hit zod and marnec?

**Comment by hanryc-tirpur** [comment] 2023-03-08 18:54
@patosullivan same here. ~zod and ~binzod are still sending me `0vg.96l75.27q05.t21bt.f1nvi.guqr7.k1nff.aap4j.vuveb.5abgn.iqhac`

**Comment by h33p** [comment] 2023-03-09 15:49
I could get the update from `~marzod`, however, it seems that urbit's roller is out of date:

Trying to boot an L1 planet:

```
~
urbit 1.22
boot: home is /home/urbit/piers/monnys-riphet
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.22.pill
boot: retrieving ~monnys-riphet's public keys
[%point-take-dawn %incomplete-json]
```

```
curl -X POST "https://roller.urbit.org/v1/azimuth" -d "{\"params\":{\"ship\":\"~monnys-riphet\"},\"id\":\"\",\"jsonrpc\":\"2.0\",\"method\":\"getPoint\"}"
{"id":null,"error":{"code":-32000,"message":"Resource not found"},"jsonrpc":"2.0"}
```

Another planet whose bootkey was generated on march 7 (a couple hours after eth-watcher bug surfaced)

```
curl -X POST "https://roller.urbit.org/v1/azimuth" -d "{\"params\":{\"ship\":\"~sansug-sapdef\"},\"id\":\"\",\"jsonrpc\":\"2.0\",\"method\":\"getPoint\"}"
{"id":null,"error":{"code":-32000,"message":"Resource not found"},"jsonrpc":"2.0"}
```

**Comment by pkova** [comment] 2023-03-09 19:30
The roller has now been updated.

```
curl -X POST "https://roller.urbit.org/v1/azimuth" -d "{\"params\":{\"ship\":\"~monnys-riphet\"},\"id\":\"\",\"jsonrpc\":\"2.0\",\"method\":\"getPoint\"}"
{"id":"","jsonrpc":"2.0","result":{"dominion":"l1","ownership":{"transferProxy":{"address":"0x0000000000000000000000000000000000000000","nonce":0},"votingProxy":{"address":"0x0000000000000000000000000000000000000000","nonce":0},"spawnProxy":{"address":"0x0000000000000000000000000000000000000000","nonce":0},"managementProxy":{"address":"0x0000000000000000000000000000000000000000","nonce":0},"owner":{"address":"0x6d5154f6e76174de86fb612d47fcfa727a5c927b","nonce":0}},"network":{"keys":{"life":"1","suite":"1","auth":"0xaf9621291d64f97a6672838009a3dde2dfce42c3157694962bca26f75f406570","crypt":"0x8ddd8a049e45965819ab1407053393ac510947b443c2ba2d4f74c5d6621b4d6e"},"sponsor":{"has":true,"who":40379},"rift":"0"}}}
```

**Comment by h33p** [comment] 2023-03-09 22:36
> The roller has now been updated.
> 
> ```
> curl -X POST "https://roller.urbit.org/v1/azimuth" -d "{\"params\":{\"ship\":\"~monnys-riphet\"},\"id\":\"\",\"jsonrpc\":\"2.0\",\"method\":\"getPoint\"}"
> {"id":"","jsonrpc":"2.0","result":{"dominion":"l1","ownership":{"transferProxy":{"address":"0x0000000000000000000000000000000000000000","nonce":0},"votingProxy":{"address":"0x0000000000000000000000000000000000000000","nonce":0},"spawnProxy":{"address":"0x0000000000000000000000000000000000000000","nonce":0},"managementProxy":{"address":"0x0000000000000000000000000000000000000000","nonce":0},"owner":{"address":"0x6d5154f6e76174de86fb612d47fcfa727a5c927b","nonce":0}},"network":{"keys":{"life":"1","suite":"1","auth":"0xaf9621291d64f97a6672838009a3dde2dfce42c3157694962bca26f75f406570","crypt":"0x8ddd8a049e45965819ab1407053393ac510947b443c2ba2d4f74c5d6621b4d6e"},"sponsor":{"has":true,"who":40379},"rift":"0"}}}
> ```

Wonderful, it boots now!

**Comment by justinlynn** [comment] 2023-03-10 02:06
Seems like this is resolved, except for the distribution issues which are probably best addressed as a separate issue. Thoughts?

**Comment by pkova** [comment] 2023-03-13 14:03
I'll resolve this and take care of the distribution issues with the roller.

**Closed by pkova** 2023-03-13 14:03 UTC
Labels: bug

**Comment by Conviare** [comment] 2023-03-13 14:37
should I just wait for your OTA fix?
this should also fix azimuth-block and zuse issues?


eth-watcher failed; will retry
%rpc-result-incomplete-batch
[ %a
    p                                                                                                                                 
  ~[                                                                                                                                  
    [ %o                                                                                                                              
        p                                                                                                                             
      { [p='jsonrpc' q=[%s p='2.0']]                                                                                                  
        [ p='error'                                                                                                                   
          q=[%o p={[p='message' q=[%s p='invalid argument 0: hex number with leading zero digits']] [p='code' q=[%n p=~.-32602]]}]    
        ]                                                                                                                             
        [p='id' q=[%s p='block by number']]                                                                                           
      }                                                                                                                               
    ]                                                                                                                                 
  ]                                                                                                                                   
]                                                                                                                                     
; ~middev is ok
; ~lanlyd is ok
; ~hodreb-racdem is ok
; ~hodreb-racdem not responding still trying
; ~middev not responding still trying
; ~lanlyd not responding still trying
; ~lagrev-nocfep not responding still trying
; ~hodreb-racdem is ok
; ~middev is ok
; ~lanlyd is ok
; ~hatryx-lastud is ok
> +azimuth-block
16.777.098
> +vat %base
%base
  /sys/kelvin:      [%zuse 417]
  base hash:        0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
  %cz hash:         0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~marzod
  source desk:      %kids
  source aeon:      136
  kids desk:        %kids
  pending updates:  ~[[%zuse 415]]
::

**Comment by pkova** [comment] 2023-03-13 14:55
It looks like you're on an old version of `urbit-os`. You should [update your runtime](https://operators.urbit.org/manual/os/updates#runtime-updates) and then run `|bump` from the dojo.

**Comment by Conviare** [comment] 2023-03-13 15:09
tried |bump 

richardlb@richard-hpcompaqelite8300sff:~$ /home/richardlb/snap/port/common/.config/Port/minrun-ticdev-/.run next --loom 32
~
urbit 1.22
boot: home is /home/richardlb/snap/port/common/.config/Port/minrun-ticdev-
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
loom: mapped 4096MB
boot: protected loom
live: loaded: GB/1.028.685.824
boot: installed 652 jets
vere: up to date
richardlb@richard-hpcompaqelite8300sff:~$ /home/richardlb/snap/port/common/.config/Port/minrun-ticdev-/.run --loom 32
~
urbit 1.22
boot: home is /home/richardlb/snap/port/common/.config/Port/minrun-ticdev-
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
loom: mapped 4096MB
boot: protected loom
live: loaded: GB/1.028.685.824
boot: installed 652 jets
vere: checking version compatibility
ames: live on 38109
conn: listening on /home/richardlb/snap/port/common/.config/Port/minrun-ticdev-/.urb/conn.sock
eyre: canceling ~[//http-server/0v7.meg3s/1/2]
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12321
pier (107991919): live
ames: czar zod.urbit.org: ip .35.247.119.159
ames: czar ber.urbit.org: ip .35.226.110.63
ames: czar feb.urbit.org: ip .34.82.25.47
; ~feb not responding still trying
; ~feb is ok
~minrun-ticdev:dojo>
