### ISSUE TITLE
Silently being logged out

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2910] opened 2020-05-19 21:04 UTC
**Describe the bug**
When my cookie expires (I think) I'll be unable to send messages to landscape. Then, when refreshing, I'm logged out.

We should really just boot you to the login screen instead of doing this silently.

I feel like this is a dupe, but couldn't find the original — where I would have commented

**Comment by matildepark** [comment] 2020-05-19 21:06
Duplicate of #1617.

**Closed by matildepark** 2020-05-19 21:06 UTC
Labels: OS1
