### ISSUE TITLE
mislabled subscription button

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2470] opened 2020-03-13 13:02 UTC
**Describe the bug**
button says "join chat" instead of "subscribe"

**To Reproduce**
Subscribing to a notebook

**Expected behavior**
Subscribe label on button

![screenshot](https://i.imgur.com/iE3D4t4.png)

**Desktop (please complete the following information):**
 - OS: Mac10.11.6
 - Browser Brave
 - 0vn.26tqu.tk9vj.h3c5c.8m9j7.6rkbj.8jk0n.qmb6k.qj6ob.sepas.c9hj7

**Additional context**
Button says "join chat" when I'm trying to subscribe to a notebook

**Comment by Fang-** [comment] 2020-03-13 13:04
Closing as duplicate of #2457, will be fixed by #2458. Thanks for reporting regardless!

**Closed by Fang-** 2020-03-13 13:04 UTC
Labels: OS1

**Comment by custom-jonathan** [comment] 2020-03-13 13:22
Dang, that was fast. ::high five::
