### ISSUE TITLE
:begin output lines are in reverse order

### ISSUE THREAD

**Issue by ShaneWilton** [urbit/urbit#250] opened 2015-01-28 08:31 UTC
My apologies in advance for not knowing all of the terminology yet. I just ran :begin for the first time after a few months of inactivity, and noticed that the instructions were being printed out of order.

```
something wrong, hit ^D to cancel, then run the program again.
change this data once you've sent it to the server.  If you enter
Let's configure your identity.  Warning - it's nontrivial to
```

```
Your ticket: <censored>
can regenerate your ship from this entropy.
Enter a passphrase or other unusual text.  You (or your enemies)
```

I don't know enough about to the system to know if this happens elsewhere.

I'm running vere under OS X (10.9.5).

**Comment by galenwp** [comment] 2015-01-28 15:08
We just fixed `%gall` so moves are now passed around in the correct order. My guess is that `(turn (flop tak.res) |=(a=cord [%leaf (trip a)]))` is the offending line in `:begin`.

**Comment by galenwp** [comment] 2015-01-28 15:14
I think this should be fixed in https://github.com/urbit/urbit/commit/1b01d679e0a324fcb33668b3af8c70f5b8e93fde. Someone else want to confirm?

**Comment by othercriteria** [comment] 2015-01-30 06:27
Doesn't seem to be fixed for me. Tested on 6ac78a7f9a0e6bf3fad93a19a54176b475a27344. Got

    ~tobmel-lanpyl-tipbyr-tinsen--watsyx-lavnut-picmex-ribtyd/try=> :begin ~modnut-migryd
    something wrong, hit ^D to cancel, then run the program again.
    change this data once you've sent it to the server.  If you enter
    Let's configure your identity.  Warning - it's nontrivial to
    
                      -- Bunting, _Chomei at Toyama_
    
                for whom should I build?
                If I did not build for myself
    
    Launching ~modnut-migryd, one of 4.278.124.800 Urbit destroyers...
    [BLAH]

Grep-ing confirmed that `$URBIT/urb/zod/main/app/begin/core.hook` is deflopped, but `$URBIT/$PIER/$SUB/main/app/begin/core.hook` still has flops. Does `urbit.pill` or similar need to be updated?

**Comment by philipcmonk** [comment] 2015-01-30 06:56
Submarines pull their files from zod, so we would need to update zod to
test it. You can also test it locally by running a fake zod: bin/vere -F -I
~zod -c pier

**Comment by galenwp** [comment] 2015-03-13 18:25
This should be up to date since the most recent breach.

**Closed by galenwp** 2015-03-13 18:25 UTC
